import CustomerFinance from '@/components/customer-finance';
import {getTaxDefaults} from '@/lib/tax-settings';
import VatSummary from '@/components/vat-summary';
import type {VatSnapshot} from '@/lib/vat';
import Link from 'next/link';
import ProductDetails from '@/components/product-details';
import {notFound} from 'next/navigation';
import {requireUser} from '@/lib/auth';
import {entityFrom,fields,getMaster,options} from '@/lib/masters';
import {canRead,canWrite,permittedFields,allows} from '@/lib/permissions';
import {labels} from '@/lib/field-labels';
import MasterForm from '@/components/master-form';
import {customerActivity} from '@/lib/audit';
const tabs=['Overview','Quotations','Orders','Delivery Receipts','Invoices','AR','Payments','Products Purchased','Credit Information','Activity'];
export default async function RecordPage({params,searchParams}:{params:Promise<{entity:string;id:string}>;searchParams:Promise<{edit?:string;tab?:string;saved?:string}>}){
 const p=await params,entity=entityFrom(p.entity),actor=await requireUser(),s=await searchParams;
 if(!canRead(actor,entity))return <div className="panel"><h1>Access restricted</h1></div>;
 const creating=p.id==='new',editing=creating||s.edit==='1';
 if(editing&&(!canWrite(actor,entity)||(entity==='customers'&&!allows(actor,creating?'customers.create':'customers.edit'))))return <div className="panel"><h1>Access restricted</h1><p>You can view this directory but cannot edit its records.</p></div>;
 const record=creating?undefined:await getMaster(actor,entity,p.id);if(!creating&&!record)notFound();
 const taxConfig=entity==='products'&&editing?await getTaxDefaults(actor):undefined;
 const shown=permittedFields(actor,entity,fields(entity)).filter(k=>!(editing&&entity==='customers'&&k==='credit_limit'&&actor.permission_overrides?.['ar.credit.edit']==='deny'&&!actor.roles.includes('PRESIDENT_ADMIN')));
 if(!editing&&entity==='products'&&record){shown.push('created_at','updated_at');if('estimated_profit' in record)shown.push('estimated_profit','markup_percent','profit_margin_percent');}const opts=await options(actor,entity);const tab=tabs.includes(s.tab||'')?s.tab!:'Overview';
 if(entity==='products'&&!editing&&record)return <ProductDetails product={record} actor={actor} suppliers={opts} saved={s.saved==='1'}/>;
 return <><Link className="muted" href={`/masters/${entity}`}>← Back to {entity}</Link><div className="page-head" style={{marginTop:20}}><div><div className="eyebrow">{creating?'New record':String(record?.sku||record?.code)}</div><h1>{creating?`Add ${entity.slice(0,-1)}`:String(record?.name)}</h1>{record&&<span className={`badge ${record.active?'':'off'}`}>{record.active?'Active':'Inactive'}</span>}</div>{!editing&&canWrite(actor,entity)&&(entity!=='customers'||allows(actor,'customers.edit'))&&<Link className="button" href={`?edit=1`}>Edit record</Link>}</div>{s.saved&&<div className="success" role="status">Record saved. The change has been recorded in the audit history.</div>}{entity==='products'&&record&&allows(actor,'inventory.read')&&<p><Link className="button secondary" href={`/inventory?product=${record.id}`}>Stock & transaction history →</Link></p>}{entity==='products'&&!editing&&record&&'estimated_profit' in record&&<p className="notice">{String(record.profit_basis)} Markup = estimated profit ÷ entered cost; margin = estimated profit ÷ entered selling price. Zero denominators show —. These remain estimates, not accounting profit.</p>}{editing?<><p className="muted">{entity==='products'?'Enter the product details and approved prices. VAT INC / VAT EX is a supplier tag only.':'Keep one permanent record for each business. Deactivate records when they are no longer used.'}</p><MasterForm entity={entity} fields={shown} record={record} options={opts} taxConfig={taxConfig}/></>:<>{entity==='customers'&&<CustomerFinance actor={actor} id={p.id}/>}
{entity==='customers'&&<nav className="tabs" aria-label="Customer profile">{allows(actor,'sales.read')&&<Link href={'/sales?customer='+p.id}>Sales history</Link>}{tabs.filter(t=>t!=='Credit Information'||allows(actor,'customers.credit')).map(t=><Link className={tab===t?'selected':''} href={`?tab=${encodeURIComponent(t)}`} key={t}>{t}</Link>)}</nav>}{entity==='customers'&&tab==='Activity'?<section className="panel"><h2>Activity</h2><table><thead><tr><th>When</th><th>Action</th><th>Changed by</th></tr></thead><tbody>{(await customerActivity(actor,p.id)).map((r,i)=><tr key={i}><td>{new Date(String(r.created_at)).toLocaleString('en-PH',{timeZone:'Asia/Manila'})}</td><td>{String(r.action)}</td><td>{String(r.name)}</td></tr>)}</tbody></table><small>Latest 100 changes. Full history is retained.</small></section>:entity==='customers'&&tab!=='Overview'&&tab!=='Credit Information'?<section className="panel"><h2>{tab}</h2><p className="muted">Coming in Stage 2+</p></section>:<section className="panel"><h2>{tab==='Credit Information'?'Credit information':'Record details'}</h2>{tab==='Credit Information'&&!allows(actor,'customers.credit')?<p>Access restricted.</p>:<dl>{shown.filter(k=>!['selling_prices','selling_tax_treatment','selling_entry_mode','cost_tax_treatment','cost_input_vat_recoverable','selling_vat','cost_vat'].includes(k)&&k!=='active'&&!['vat_status','vat_rate'].includes(k)&&(tab!=='Credit Information'||['payment_terms','credit_limit','credit_notes','account_status'].includes(k))).map(k=><div key={k}><dt>{({estimated_profit:'Estimated profit / primary unit (PHP)',markup_percent:'Markup (%)',profit_margin_percent:'Profit margin (%)',created_at:'Created',updated_at:'Updated'} as Record<string,string>)[k]||(entity==='products'&&k==='name'?'Product name / description':labels[k])}</dt><dd>{k==='cost_input_vat_recoverable'?(record?.[k]===null?'Not configured':record?.[k]?'Yes':'No'):k.endsWith('_id')?String(opts.find(o=>o.id===record?.[k])?.name||record?.[k]||'—'):Array.isArray(record?.[k])?(record[k] as string[]).join('\n')||'—':String(record?.[k]??'')||'—'}</dd></div>)}</dl>}{entity==='customers'&&<p className="notice" style={{marginTop:25}}>Use the customer financial position links for authorized AR and Collection history.</p>}</section>}</>}</>;
}
