import Link from 'next/link';
import {requireUser} from '@/lib/auth';
import {allows} from '@/lib/permissions';
import {getAR,financeOptions} from '@/lib/finance-read';
import {businessDate} from '@/lib/finance';
import {money} from '@/components/dashboard-ui';
import FinanceForm from '@/components/finance-form';
export default async function ARDetail({params}:{params:Promise<{id:string}>}){const actor=await requireUser();if(!allows(actor,'ar.read'))return <h1>Access restricted</h1>;const {id}=await params,r=await getAR(actor,id),today=businessDate();const options=allows(actor,'collections.record')?await financeOptions(actor):null;return <><Link href="/accounts-receivable">← Accounts Receivable</Link><h1>{r.number} · {r.customer_name}</h1><section className="panel"><h2>{r.physical_number?'Physical SI '+r.physical_number:r.source_number}</h2><p>Invoice date: {r.invoice_date} · Terms: {r.terms} {r.custom_terms} · Due: {r.due_date}</p><p>Original: {money(r.original_amount)} · Cleared collections: {money(r.collected)} · Approved adjustments: {money(r.adjustments)}</p><h2>Outstanding balance: {money(r.balance)}</h2>{r.pending_checks!==undefined&&<p>Pending checks: {money(r.pending_checks)} (not settled)</p>}<span className="badge">{r.payment_status}</span>{r.due_indicator?<p>{r.due_indicator}</p>:r.days_overdue>0&&<p>Overdue — {r.days_overdue} days</p>}{Number(r.refund_due)>0&&<p className="notice">Refund Due / Customer Credit Pending: {money(r.refund_due)}. No refund has been executed.</p>}<nav className="tabs">{r.customer_id&&<Link href={'/masters/customers/'+r.customer_id}>Customer</Link>}{r.invoice_id&&allows(actor,'invoices.read')&&<Link href={'/commercial/'+r.invoice_id}>Invoice</Link>}{r.order_id&&allows(actor,'orders.read')&&<Link href={'/commercial/'+r.order_id}>Sales Order</Link>}{r.sale_id&&allows(actor,'sales.read')&&<Link href={'/sales/'+r.sale_id}>Sale</Link>}{r.customer_id&&allows(actor,'ar.statement')&&<Link href={'/statements?customer='+r.customer_id}>Statement</Link>}</nav></section>
 {options&&Number(r.balance)>0&&<section className="panel"><h2>Record Collection</h2><FinanceForm operation="collect" label="Record Collection" fixed={{ar_id:id}} destination="/collections/:id" fields={[{name:'amount',label:'Amount received',type:'number',required:true},{name:'received_date',label:'Collection date',type:'date',value:today,required:true},{name:'method_id',label:'Actual payment method',required:true,options:options.methods as {id:string;name:string;behavior:string}[]},...(options.accounts.length?[{name:'account_id',label:'Receiving account',options:options.accounts as {id:string;name:string}[]}]:[]),{name:'reference',label:'Payment reference (optional)'},{name:'check_bank',label:'Check bank',required:true},{name:'check_number',label:'Check number',required:true},{name:'check_date',label:'Check date',type:'date',required:true},{name:'notes',label:'Notes'}]}/></section>}
 {r.collections&&<section className="panel"><h2>Collection history</h2><table><thead><tr><th>Collection</th><th>Date</th><th>Amount</th><th>Payment / Status</th></tr></thead><tbody>{r.collections.map((c:Record<string,string>)=><tr key={c.id}><td><Link href={'/collections/'+c.id}>{c.number}</Link></td><td>{c.received_date}</td><td>{money(c.amount)}</td><td>{c.method} · {c.check_status||c.status}</td></tr>)}</tbody></table></section>}
 <section className="panel"><h2>Approved adjustments</h2>{r.adjustment_history.map((a:Record<string,string>)=><p key={a.id}>{a.return_number} · {money(a.amount)} · {a.reason} · {a.actor_name}</p>)}{allows(actor,'ar.adjust')&&<details><summary>Approve a return adjustment</summary><p>This does not change the invoice, issue a tax credit note, or execute a refund.</p><FinanceForm operation="adjust" label="Approve AR adjustment" fixed={{ar_id:id}} fields={[{name:'return_id',label:'Completed Return',required:true,options:(r.adjustable_returns||[]).map((v:Record<string,string>)=>({id:v.id,name:v.number}))},{name:'amount',label:'Approved amount',type:'number',required:true},{name:'effective_date',label:'Effective date',type:'date',value:today,required:true},{name:'reason',label:'Approval reason',required:true}]}/></details>}</section>
 {r.followups&&<section className="panel"><h2>Follow-up history</h2>{r.followups.map((f:Record<string,string>)=><p key={f.id}>{f.followup_date} · {f.note} {f.promise_date&&'Promise to pay: '+f.promise_date} · {f.actor_name}</p>)}</section>}{allows(actor,'ar.followup.add')&&<section className="panel"><h2>Add follow-up</h2><FinanceForm operation="followup" label="Save follow-up" fixed={{ar_id:id}} fields={[{name:'followup_date',label:'Follow-up date',type:'date',value:today,required:true},{name:'note',label:'Note'},...(allows(actor,'ar.promise.edit')?[{name:'promise_date',label:'Promise to pay (does not change due date)',type:'date'}]:[])]}/></section>}</>;}
