import {test,after} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {randomUUID} from 'node:crypto';
import {migrate} from '../lib/migrations';
import {query,transaction,closeDB} from '../lib/db';
import {stamp} from '../lib/sales-common';
import {dashboardData} from '../lib/dashboard-read';
import {saveMaster} from '../lib/masters';
import {saveSale,postSale} from '../lib/sales';
import {postMovement} from '../lib/inventory';
import {getSale} from '../lib/sales-read';
import type {Actor} from '../lib/permissions';
let directory:string;
const owner:Actor={id:randomUUID(),name:'TEST Dashboard Owner',email:'dashboard@example.test',roles:['PRESIDENT_ADMIN']};
test('Dashboard uses complete authorized data and performs no writes',async()=>{
 delete process.env.DATABASE_URL;directory=await mkdtemp(join(tmpdir(),'imperial-dashboard-'));process.env.LOCAL_DB_PATH=directory;await migrate();
 const restricted:Actor={id:randomUUID(),name:'TEST Restricted',email:'dashboard-restricted@example.test',roles:['WAREHOUSE'],permission_overrides:{'sales.read':'allow'}};
 await transaction(async db=>{await stamp(db,owner);for(const a of [owner,restricted])await db.query('INSERT INTO users(id,name,email,password_hash,roles,permission_overrides) VALUES($1,$2,$3,$4,$5,$6)',[a.id,a.name,a.email,'not-a-login-hash',a.roles,JSON.stringify(a.permission_overrides||{})]);});
 const p=await saveMaster(owner,'products',{sku:'TEST-DASH',name:'TEST Dashboard Product',brand:'TEST',category:'TEST',primary_uom:'PCS',secondary_uom:'',conversion:'',base_price:'500',supplier_adjustment:'0',standard_cost:'500',vat_status:'VAT',vat_rate:'0.12',retail_price:'700',contractor_price:'700',wholesale_price:'700',meter_price:'0',reorder_level:'1',supplier_id:'',notes:'TEST',active:true});
 await postMovement(owner,{request_id:randomUUID(),product_id:p,kind:'IN',occurred_at:new Date().toISOString(),quantity:'10',uom:'PCS',unit_cost:'500',reference:'TEST'});
 const id=await saveSale(owner,{request_id:randomUUID(),channel:'Retail',occurred_at:new Date().toISOString(),terms:'Cash',tax_config_version:1,lines:[{id:randomUUID(),product_id:p,quantity:'2',uom:'PCS',price:'700',vat_mode:'VAT Exclusive',tax_treatment:'VATable',discount:'0'}]});
 const sale=await getSale(owner,id);await postSale(owner,{id,version:sale.version,request_id:randomUUID()});
 const before=(await query('SELECT count(*)::text AS n FROM audit_log')).rows[0].n;
 const d=await dashboardData(owner);assert.equal(Number(d.totals?.today),1400);assert.equal(Number(d.totals?.month),1400);assert.equal(Number(d.inventoryValue),4000);assert.equal(Number(d.chart[0].profit),400);assert.equal(d.top[0].uom,'PCS');assert.equal(Number(d.top[0].quantity),2);
 const hidden=await dashboardData({...restricted,roles:['PRESIDENT_ADMIN']});assert.equal(hidden.totals,null);assert.equal(hidden.inventoryValue,null);assert.equal(hidden.customerCount,null);assert.deepEqual(hidden.chart,[]);assert.ok(!JSON.stringify(hidden).includes('1400'));
 assert.equal((await query('SELECT count(*)::text AS n FROM audit_log')).rows[0].n,before);
 await transaction(async db=>{await stamp(db,owner);await db.query('UPDATE users SET active=false WHERE id=$1',[restricted.id]);});await assert.rejects(()=>dashboardData(restricted));
});
after(async()=>{await closeDB();if(directory)await rm(directory,{recursive:true,force:true});});
