import {test,after} from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {quotationLine,calculateFees,documentTotals} from '../lib/quotation-calculations';
import {priceListRows,productForPriceList} from '../lib/quotation-form';
import {operationalConfig} from '../lib/operational-pricing';
import {migrate} from '../lib/migrations';
import {query,transaction,closeDB} from '../lib/db';
import {saveUser} from '../lib/users';
import {saveMaster} from '../lib/masters';
import {saveCommercial,actCommercial,createCommercialChild} from '../lib/commercial';
import {getCommercial} from '../lib/commercial-read';
import {quotationDocument} from '../lib/quotation-document';
import {quotationRender} from '../lib/quotation-pdf';
import {postMovement} from '../lib/inventory';
import {saleProductDefaults,saveSale} from '../lib/sales';
import {getSale} from '../lib/sales-read';
import {hashPassword} from '../lib/password';
import {stamp,type Row} from '../lib/sales-common';
import type {Actor} from '../lib/permissions';
const cfg={standard_rate:'0.12',version:1,effective_at:'2026-01-01T00:00:00Z'};
const line=(p:string,q:string,d:string,mode:'VAT Exclusive'|'VAT Inclusive'='VAT Exclusive')=>quotationLine(p,q,d,mode,'VATable',cfg,2);
test('Owner quotation examples have no VAT multiplier and retain exact intermediate values',()=>{for(const mode of ['VAT Exclusive','VAT Inclusive'] as const){assert.equal(line('3000','1','+25.5%',mode).gross_amount,'3765.00');assert.equal(line('15','1','-25-5-3',mode).gross_amount,'10.37');assert.equal(line('15','12.5','-25-5-3',mode).gross_amount,'129.59');assert.equal(line('15','12.5','-25-5-3',mode).vat_snapshot.exact_amount,'129.5859375');assert.equal(line('100','1','-10',mode).gross_amount,'90.00');assert.equal(line('15','1','-25-5-3',mode).vat_amount,'0.00');}const fees=calculateFees([{id:randomUUID(),description:'Delivery Fee',amount:'1500.50',vat_mode:'VAT Exclusive',tax_treatment:'VATable'},{id:randomUUID(),description:'Handling',amount:'20',vat_mode:'VAT Inclusive',tax_treatment:'VATable'}],cfg);assert.equal(documentTotals([line('15','1','-25-5-3'),line('15','12.5','-25-5-3')],fees).gross_total,'1660.45');assert.equal(documentTotals([line('0.004','1','0'),line('0.004','1','0')],[]).gross_total,'0.01');});
test('Independent UOM price lists never derive Contractor from Retail and preserve Keep Existing Prices',()=>{const p={primary_uom:'ROLL',secondary_uom:'METER',retail_price:'3800',contractor_price:'3500',meter_price:'38',selling_prices:{ROLL:{Retail:'3800',Contractor:'3500'},METER:{Retail:'38',Contractor:'35'}}};assert.equal(saleProductDefaults(p,'ROLL','Retail').price,'3800');assert.equal(saleProductDefaults(p,'ROLL','Contractor').price,'3500');assert.equal(saleProductDefaults(p,'METER','Contractor').price,'35');assert.equal(saleProductDefaults({...p,selling_prices:null},'METER','Contractor').price,'');const rows=[{id:'a',uom:'ROLL',price:'3333',unit_defaults:[{uom:'ROLL',prices:{Retail:'3800',Contractor:'3500'}}]}];assert.equal(priceListRows(rows,'Contractor')[0].price,'3500');assert.equal(rows[0].price,'3333');assert.equal(productForPriceList({unit_defaults:rows[0].unit_defaults},'Retail').unit_defaults[0].price,'3800');});
let dir='';after(async()=>{await closeDB();if(dir)await rm(dir,{recursive:true,force:true});});
test('Operational prices persist, are audited, preserve conversion snapshots and tag-only stock costs',async()=>{delete process.env.DATABASE_URL;dir=await mkdtemp(join(tmpdir(),'imperial-operational-'));process.env.LOCAL_DB_PATH=dir;await migrate();const owner:Actor={id:randomUUID(),name:'TEST Pricing Owner',email:'pricing@example.test',roles:['PRESIDENT_ADMIN']};await transaction(async db=>{await stamp(db,owner);await db.query('INSERT INTO users(id,name,email,password_hash,roles) VALUES($1,$2,$3,$4,$5)',[owner.id,owner.name,owner.email,await hashPassword('TEST operational long password'),owner.roles]);});const product={sku:'TEST-OP-PRICING',name:'TEST Operational Cable',brand:'TEST',category:'Wire',primary_uom:'ROLL',secondary_uom:'METER',conversion:'100',base_price:'3000',supplier_adjustment:'0',standard_cost:'3000',cost_entry_mode:'VAT Inclusive',vat_status:'VAT',vat_rate:'0.12',retail_price:'3800',contractor_price:'3500',wholesale_price:'0',meter_price:'38',reorder_level:'0',supplier_id:'',notes:'TEST',active:true,selling_prices:{ROLL:{Retail:'3800',Contractor:'3500'},METER:{Retail:'38',Contractor:'35'}}};const pid=await saveMaster(owner,'products',product);for(const mode of ['VAT Inclusive','VAT Exclusive']){const id=await postMovement(owner,{request_id:randomUUID(),product_id:pid,kind:'IN',occurred_at:'2026-09-01T00:00:00Z',quantity:'1',uom:'ROLL',unit_cost:'3000',cost_entry_mode:mode,reference:'TEST '+mode});assert.equal((await query<Row>('SELECT total_cost FROM inventory_movements WHERE id=$1',[id])).rows[0].total_cost,'3000.000000');}
const input={request_id:randomUUID(),kind:'Q',channel:'Retail',customer_id:'',price_list:'Contractor',document_flow:'DR Only',occurred_at:'2026-09-17T00:00:00Z',terms:'Cash',tax_config_version:1,lines:[{id:randomUUID(),product_id:pid,quantity:'1',uom:'ROLL',price:'3500',discount:'+25.5%',adjustment_version:2,vat_mode:'VAT Exclusive',tax_treatment:'VATable'}],fees:[{id:randomUUID(),description:'Delivery Fee',amount:'1500.50',vat_mode:'VAT Exclusive',tax_treatment:'VATable'}]};const id=await saveCommercial(owner,input);
const employeeId=await saveUser(owner,{name:'TEST Bracket Employee',email:'bracket@example.test',roles:['SALES'],password:'TEST bracket long password',active:true,permission_overrides:{'commercial.read':'allow','commercial.prices':'allow','quotations.read':'allow','quotations.create':'allow','quotations.edit':'allow','sales.override':'deny'}});
const employee:Actor={id:employeeId,name:'TEST Bracket Employee',email:'bracket@example.test',roles:['SALES']};
const staffInput={...input,request_id:randomUUID(),fees:[],lines:[{...input.lines[0],id:randomUUID(),discount:'0'}]};
assert(await saveCommercial(employee,staffInput));
await assert.rejects(saveCommercial(employee,{...staffInput,request_id:randomUUID(),lines:[{...staffInput.lines[0],price:'3499'}]}),/permission/);
await assert.rejects(saveMaster(employee,'products',product,pid,1),/permission/);
await closeDB();let q=await getCommercial(owner,id);assert.equal(q.gross_total,'5893.00');assert.equal(q.vat_total,'0.00');assert.equal(q.price_list,'Contractor');assert.equal(q.document_flow,'DR Only');await saveMaster(owner,'products',{...product,contractor_price:'3600',selling_prices:{...product.selling_prices,ROLL:{Retail:'3800',Contractor:'3600'}}},pid,1);await actCommercial(owner,{id,version:q.version,request_id:randomUUID(),action:'approve'});q=await getCommercial(owner,id);const so=await actCommercial(owner,{id,version:q.version,request_id:randomUUID(),action:'convert'});const order=await getCommercial(owner,so);assert.equal(order.lines[0].entered_price,'3500.000000');assert.equal(order.gross_total,'5893.00');assert.equal(order.price_list,'Contractor');assert.equal(order.document_flow,'DR Only');const pdf=await quotationRender(await quotationDocument(owner,id));assert(!pdf.pages.join('').includes('Contractor'));assert(!pdf.pages.join('').includes('DR Only'));assert(pdf.pages.join('').includes('₱4,392.50'));assert(pdf.pages.join('').includes('₱5,893.00'));assert((await query<Row>("SELECT id FROM audit_log WHERE record_id=$1 AND entity='commercial_documents'",[id])).rows.length>0);await assert.rejects(saveCommercial(owner,{...input,id,version:1,request_id:randomUUID()}),/changed|Draft/);
const sid=await saveSale(owner,{request_id:randomUUID(),channel:'Retail',customer_id:'',price_list:'Retail',document_flow:'SI',occurred_at:'2026-09-17T00:00:00Z',terms:'Cash',tax_config_version:1,lines:[{id:randomUUID(),product_id:pid,quantity:'1',uom:'ROLL',price:'3800',discount:'10',vat_mode:'VAT Inclusive',tax_treatment:'VATable'}]});assert.equal((await getSale(owner,sid)).gross_total,'3420.00');});

test('Partial document settlements conserve exact multi-row totals and fee cents',async()=>{
 const {allocatedDocumentTotals,allocateFees}=await import('../lib/quotation-calculations');
 const rows=[{...line('0.004','1','0'),id:'a',quantity:'1'},{...line('0.004','1','0'),id:'b',quantity:'1'}];
 const first=allocatedDocumentTotals(rows,{},[{source_line_id:'a',quantity:'1'}],[]);
 const last=allocatedDocumentTotals(rows,{a:'1'},[{source_line_id:'b',quantity:'1'}],[]);
 assert.equal(first.gross_total,'0.00');assert.equal(last.gross_total,'0.01');assert.equal(documentTotals(rows,[]).gross_total,'0.01');
 const fees=calculateFees([{id:randomUUID(),description:'Delivery',amount:'0.01',vat_mode:'VAT Exclusive',tax_treatment:'VATable'}],cfg);
 const a=allocateFees(fees,rows,{},[{source_line_id:'a',quantity:'1'}]);
 const b=allocateFees(fees,rows,{a:'1'},[{source_line_id:'b',quantity:'1'}]);
 assert.equal(Number(documentTotals([],a).gross_total)+Number(documentTotals([],b).gross_total),0.01);
});
