import {test,after} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {randomUUID} from 'node:crypto';
import {migrate} from '../lib/migrations';
import {query,transaction,closeDB} from '../lib/db';
import {hashPassword} from '../lib/password';
import {saveSale} from '../lib/sales';
import {changeSaleDocument} from '../lib/sales-documents';
import {saveMaster} from '../lib/masters';
import {saveUser} from '../lib/users';
import {stamp,type Row} from '../lib/sales-common';
import {saveCommercial,actCommercial,createCommercialChild,assignCommercialNumber,allocateLine} from '../lib/commercial';
import {getCommercial,listCommercial} from '../lib/commercial-read';
import {commercialResponse} from '../lib/commercial-api';
import {authenticate} from '../lib/sessions';
import {postMovement,stockBalances} from '../lib/inventory';
import {saveTaxSettings} from '../lib/tax-settings';
import type {Actor} from '../lib/permissions';
import {savePrintProfile,preparePrint,overlay,profileSchema} from '../lib/document-print';
import {dueDate} from '../lib/sales-calculations';
import {POST as printResponse} from '../app/api/document-print/route';
const owner:Actor={id:randomUUID(),name:'TEST Stage4 Owner',email:'stage4@example.test',roles:['PRESIDENT_ADMIN']};
let worker:Actor;const password='TEST Stage4 password long';let directory:string,pid:string,order:string;
after(async()=>{await closeDB();if(directory)await rm(directory,{recursive:true,force:true});});
const product={sku:'TEST-S4',name:'TEST Stage4 Breaker',brand:'TEST',category:'Breaker',primary_uom:'PCS',secondary_uom:'',conversion:'',base_price:'500',supplier_adjustment:'0',standard_cost:'500',vat_status:'VAT',vat_rate:'0.12',retail_price:'700',contractor_price:'700',wholesale_price:'700',meter_price:'0',reorder_level:'1',supplier_id:'',notes:'TEST ONLY',active:true};
const line=(quantity='10',extra:Row={})=>({id:randomUUID(),product_id:pid,quantity,uom:'PCS',price:'700',vat_mode:'VAT Exclusive',tax_treatment:'VATable',discount:'10',...extra});
const draft=(extra:Row={})=>({request_id:randomUUID(),kind:'Q',channel:'Retail',occurred_at:'2026-09-01T00:00:00Z',terms:'Cash',tax_config_version:1,lines:[line()],...extra});
async function action(id:string,action:string,extra:Row={},actor=owner){return actCommercial(actor,{id,version:(await getCommercial(owner,id)).version,request_id:randomUUID(),action,...extra});}
async function child(kind:string,qty:string,source=order){const o=await getCommercial(owner,source);return createCommercialChild(owner,{order_id:source,kind,request_id:randomUUID(),occurred_at:'2026-09-02T00:00:00Z',lines:[{source_line_id:o.lines[0].id,quantity:qty}]});}
async function physical(id:string,n:string){const d=await getCommercial(owner,id),series=(await query<Row>('SELECT id FROM sales_options WHERE kind=$1',[d.kind==='SI'?'si_series':'dr_series'])).rows[0].id;return assignCommercialNumber(owner,{id,version:d.version,request_id:randomUUID(),series_id:series,number:n});}
async function stock(){return (await stockBalances(owner,{product:pid}))[0].available;}
test('Stage 6 workspaces, handwritten SI, calibrated overlays and preserved release/AR rules',async t=>{
 delete process.env.DATABASE_URL;directory=await mkdtemp(join(tmpdir(),'imperial-stage6-'));process.env.LOCAL_DB_PATH=directory;await migrate();await transaction(async db=>{await stamp(db,owner);await db.query('INSERT INTO users(id,name,email,password_hash,roles) VALUES($1,$2,$3,$4,$5)',[owner.id,owner.name,owner.email,await hashPassword(password),owner.roles]);});pid=await saveMaster(owner,'products',product);await postMovement(owner,{request_id:randomUUID(),product_id:pid,kind:'IN',occurred_at:'2026-08-01T00:00:00Z',quantity:'100',uom:'PCS',unit_cost:'500',reference:'TEST Stage6'});order=await saveCommercial(owner,draft({kind:'SO',terms:'30 Days'}));await action(order,'confirm');const o=await getCommercial(owner,order);let si='',dr='';
 await t.test('Handwritten draft edits and stale edits never post inventory or AR',async()=>{const input={order_id:order,kind:'SI',preparation_mode:'Handwritten',request_id:randomUUID(),occurred_at:'2026-09-02T00:00:00Z',lines:[{source_line_id:o.lines[0].id,quantity:'3'}]};si=await createCommercialChild(owner,input);assert.equal(await createCommercialChild(owner,input),si);assert.equal((await query<Row>('SELECT mode FROM commercial_preparation WHERE document_id=$1',[si])).rows[0].mode,'Handwritten');await createCommercialChild(owner,{...input,id:si,version:1,request_id:randomUUID(),lines:[{...input.lines[0],quantity:'4'}]});assert.equal((await getCommercial(owner,si)).lines[0].quantity,'4.000000');await assert.rejects(createCommercialChild(owner,{...input,id:si,version:1,request_id:randomUUID()}),/changed/);assert.equal(await stock(),'100.000000');assert.equal((await query<Row>('SELECT count(*)::int n FROM receivables')).rows[0].n,0);});
 await t.test('Finalized SI creates one AR, unchanged inventory; terms use invoice date',async()=>{await physical(si,'TEST-S6-SI');await action(si,'finalize');const ar=(await query<Row>('SELECT * FROM receivables WHERE invoice_id=$1',[si])).rows[0];assert.equal(String(ar.original_amount),'2520.00');assert.equal(await stock(),'100.000000');assert.equal((await query<Row>('SELECT count(*)::int n FROM sales')).rows[0].n,0);assert.equal(dueDate('2026-09-02T00:00:00Z','30 Days'),'2026-10-02');for(const terms of ['COD','7 Days','15 Days','30 Days','45 Days','60 Days','90 Days'])assert(dueDate('2026-09-02T00:00:00Z',terms));});
 await t.test('Five competing drafts cannot over-release; DR never creates another receivable',async()=>{const ids=await Promise.all(Array.from({length:5},()=>child('DR','10')));for(const [i,id] of ids.entries())await physical(id,'TEST-S6-DR-'+i);const result=await Promise.allSettled(ids.map(id=>action(id,'finalize')));assert.equal(result.filter(r=>r.status==='fulfilled').length,1);dr=ids[result.findIndex(r=>r.status==='fulfilled')];assert.equal(await stock(),'90.000000');assert.equal((await query<Row>('SELECT count(*)::int n FROM receivables')).rows[0].n,1);});
 const profile={kind:'SI',name:'TEST measured SI',width_mm:210,height_mm:297,approved:true,layout:{offset_x:0,offset_y:0,font_size:9,row_height:8,max_rows:10,fields:[{key:'customer',x:10,y:20,width:180},{key:'description',x:10,y:60,width:90},{key:'quantity',x:105,y:60,width:20},{key:'amount',x:135,y:60,width:40},{key:'total',x:135,y:200,width:40}]}};let profileId='';
 await t.test('Print contains variable values, excludes stationery and preprinted numbers; retry audited once',async()=>{profileId=await savePrintProfile(owner,profile);const data={document_id:si,profile_id:profileId,request_id:randomUUID(),reason:'TEST initial print'};const html=await preparePrint(owner,data);assert(!html.includes('TEST-S6-SI'));assert(!html.includes('Sales Invoice'));assert(!html.includes('Meter per Roll'));assert(html.includes('2,520.00'));assert.equal(await preparePrint(owner,data),html);assert.equal((await query<Row>('SELECT count(*)::int n FROM commercial_print_events')).rows[0].n,1);await assert.rejects(preparePrint(owner,{...data,reason:'changed'}),/already used/);});
 await t.test('Unapproved layouts, overflow and forged origins are rejected',async()=>{const unapproved=await savePrintProfile(owner,{...profile,approved:false});await assert.rejects(preparePrint(owner,{document_id:si,profile_id:unapproved,request_id:randomUUID(),reason:'TEST'}),/approve calibration/);const doc=await getCommercial(owner,si);assert.throws(()=>overlay({...doc,lines:Array.from({length:11},()=>doc.lines[0])},profileSchema.parse(profile)),/Too many/);assert.throws(()=>overlay({...doc,lines:[{...doc.lines[0],product_name:'long '.repeat(300)}]},profileSchema.parse(profile)),/too long/);const token=await authenticate(owner.email,password);const response=await printResponse(new Request('http://127.0.0.1:3002/api/document-print',{method:'POST',headers:{cookie:'imperial_session='+token,origin:'https://forged.example','Content-Type':'application/json'},body:JSON.stringify({operation:'print',data:{document_id:si,profile_id:profileId,request_id:randomUUID(),reason:'TEST'}})}));assert.equal(response.status,403);});
 await t.test('Restricted employees cannot calibrate or print protected amounts; restart preserves SI/AR',async()=>{const id=await saveUser(owner,{name:'TEST restricted',email:'s6-restricted@example.test',roles:['WAREHOUSE'],password,active:true,permission_overrides:{'commercial.read':'allow','invoices.read':'allow','sales.si.print':'deny'}});const restricted={...owner,id};await assert.rejects(savePrintProfile(restricted,profile),/permission/);await assert.rejects(preparePrint(restricted,{document_id:si,profile_id:profileId,request_id:randomUUID(),reason:'TEST'}),/permission/);const before=JSON.stringify(await getCommercial(owner,si));await closeDB();assert.equal(JSON.stringify(await getCommercial(owner,si)),before);assert.equal((await query<Row>('SELECT count(*)::int n FROM receivables')).rows[0].n,1);});
 await t.test('Five independent employee sessions cannot over-invoice the remaining quantity',async()=>{const employees=[];for(let i=0;i<5;i++){const id=await saveUser(owner,{name:'TEST Stage6 employee '+i,email:'stage6-'+i+'@example.test',roles:['SALES'],password,active:true,permission_overrides:{'commercial.read':'allow','commercial.prices':'allow','sales.prices':'allow','orders.read':'allow','invoices.read':'allow','invoices.create':'allow','invoices.finalize':'allow'}});employees.push({id,token:await authenticate('stage6-'+i+'@example.test',password)});}const results=await Promise.all(employees.map(async e=>{const data={order_id:order,kind:'SI',request_id:randomUUID(),occurred_at:'2026-09-02T00:00:00Z',lines:[{source_line_id:o.lines[0].id,quantity:'6'}]};const r=await commercialResponse(new Request('http://127.0.0.1:3002/api/commercial',{method:'POST',headers:{cookie:'imperial_session='+e.token,origin:'http://127.0.0.1:3002','Content-Type':'application/json'},body:JSON.stringify({operation:'child',data})}));assert.equal(r.status,200);return {...e,id:(await r.json()).id};}));for(const [i,r] of results.entries())await physical(r.id,'TEST-S6-CONCURRENT-'+i);const final=await Promise.all(results.map(async r=>{const d=await getCommercial(owner,r.id);return commercialResponse(new Request('http://127.0.0.1:3002/api/commercial',{method:'POST',headers:{cookie:'imperial_session='+r.token,origin:'http://127.0.0.1:3002','Content-Type':'application/json'},body:JSON.stringify({operation:'action',data:{id:r.id,version:d.version,action:'finalize',request_id:randomUUID()}})}));}));assert.equal(final.filter(r=>r.status===200).length,1);assert.equal(await stock(),'90.000000');assert.equal((await query<Row>('SELECT count(*)::int n FROM receivables')).rows[0].n,2);});

});
