import {test} from 'node:test';
import assert from 'node:assert/strict';
import React from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import {AppRouterContext} from 'next/dist/shared/lib/app-router-context.shared-runtime';
import QuotationWorkspace from '../components/quotation-workspace';
import {permissionKeys} from '../lib/permissions';
const router={back(){},forward(){},refresh(){},push(){},replace(){},prefetch(){}} as any;
const config={standard_rate:'0.12',version:1,effective_at:'2026-01-01T00:00:00Z'};
const initial={id:'test',kind:'Q',number:'Q-TEST',status:'Draft',version:1,occurred_at:'2026-09-17T00:00:00Z',validity:'2027-01-01',customer_id:'client',customer_snapshot:{id:'client',name:'TEST Client',billing_address:'TEST Address',contact_person:'TEST Contact'},salesperson_snapshot:{id:'employee',name:'TEST Agent'},notes:'TEST notes',fees:[{id:'fee',description:'Delivery Fee',amount:'1500.50',vat_mode:'VAT Inclusive',tax_treatment:'VATable'}],lines:[{id:'line',product_id:'product',product_name:'TEST Cable',quantity:'1',uom:'ROLL',entered_price:'700',vat_mode:'VAT Exclusive',tax_treatment:'VATable',vat_snapshot:{discount_expression:'-25-5-3'}}]};
function render(doc?:any,permissions=permissionKeys as unknown as any[]){return renderToStaticMarkup(React.createElement(AppRouterContext.Provider,{value:router},React.createElement(QuotationWorkspace,{initial:doc,config,permissions,employee:{id:'employee',name:'TEST Agent'}})));}
test('Quotation is the editable document with all workspace actions and no validity/VAT breakdown',()=>{const html=render(initial);for(const label of ['QUOTATION FORM','Q-TEST','Item Description 1','Unit Price 1','Discount 1','Client','Address','Contact','Agent','Date','Terms','Save','Clear Form','Print Quotation','Download PDF','Open / History','+ Add Row','Other Fees','TOTAL AMOUNT DUE'])assert(html.includes(label),label);assert(!html.includes('Valid until'));assert(!html.includes('2027-01-01'));assert(!html.includes('VAT-exclusive total'));assert(!html.includes('Amounts payable include applicable VAT'));assert(html.includes('value="₱1,500.50"'));assert(html.includes('-25%-5%-3%'));assert(html.includes('/quotations/history'));});
test('New quotation has no official number or inherited fee, and finalized document is read-only',()=>{const html=render();assert(html.includes('Assigned on save'));assert(!html.includes('value="₱1,500.50"'));assert(html.includes('New quotation'));const frozen=render({...initial,status:'Approved'});assert.match(frozen,/<fieldset disabled="" class="q-paper"/);assert.match(frozen,/<button type="submit" disabled="">Save/);});
test('Quotation workspace renders fee editing independently from product price override',()=>{const html=render(initial,permissionKeys.filter(p=>p!=='sales.override'));assert.match(html,/aria-label="Unit Price 1"[^>]*readOnly=""/);assert(!/aria-label="Fee amount 1"[^>]*readOnly=""/.test(html));const denied=render(initial,permissionKeys.filter(p=>p!=='quotations.fees'));assert.match(denied,/aria-label="Fee amount 1"[^>]*readOnly=""/);});

test('One literal Contact field preserves legacy information and long description wraps in an editable textarea',()=>{const name='TEST Electrical industrial heavy duty copper conductor with flame retardant insulation for commercial distribution panels and protected underground installations';const html=render({...initial,customer_snapshot:{...initial.customer_snapshot,quotation_contact:'  Engr. Reyes / 0917 — call after 3pm  ',phone:'historical phone',email:'history@example.test'},lines:[{...initial.lines[0],product_name:name}]});assert(html.includes('  Engr. Reyes / 0917 — call after 3pm  '));assert(!html.includes('aria-label="Phone"'));assert(!html.includes('aria-label="Email"'));assert(!html.includes('aria-label="Contact person"'));assert.match(html,/<textarea[^>]*aria-label="Item Description 1"/);assert(html.includes(name));assert(html.includes('q-description-size'));assert(html.includes('width:82px'));});

test('Price List and Document Flow are internal controls outside the customer document',()=>{const html=render({...initial,price_list:'Contractor',document_flow:'DR Only'});const paper=html.slice(html.indexOf('class="q-paper"'));assert(html.includes('aria-label="Price List"'));assert(html.includes('Document Flow'));for(const label of ['Price List','Contractor','Document Flow','DR Only'])assert(!paper.includes(label),label);});
