import {test,after} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {randomUUID} from 'node:crypto';
import {migrate} from '../lib/migrations';
import {query,transaction,closeDB} from '../lib/db';
import {hashPassword} from '../lib/password';
import {saveMaster} from '../lib/masters';
import {saveUser} from '../lib/users';
import {saveSale,postSale} from '../lib/sales';
import {postMovement} from '../lib/inventory';
import {saveCommercial,actCommercial,createCommercialChild,assignCommercialNumber} from '../lib/commercial';
import {getCommercial} from '../lib/commercial-read';
import {recordCollection,changeCheck,reverseCollection,reconcileAR,legacyReport,addFollowup,adjustAR,position,businessDate,changeCredit} from '../lib/finance';
import {getAR,listAR,listCollections,financeSummary,customerStatement} from '../lib/finance-read';
import {financeResponse} from '../lib/finance-api';
import {dueDate,paymentTerms} from '../lib/sales-calculations';
import {createReturn,changeReturn,getReturn} from '../lib/returns';
import {authenticate} from '../lib/sessions';
import {stamp,type Row} from '../lib/sales-common';
import {permissionKeys,type Actor} from '../lib/permissions';
const owner:Actor={id:randomUUID(),name:'TEST Finance Owner',email:'finance@example.test',roles:['PRESIDENT_ADMIN']};
const password='TEST Finance password long';let customer:string,pid:string,worker:Actor,restricted:Actor;const today=businessDate();
after(closeDB);
const product={sku:'TEST-FIN',name:'TEST Finance Breaker',brand:'TEST',category:'Breaker',primary_uom:'PCS',secondary_uom:'',conversion:'',base_price:'500',supplier_adjustment:'0',standard_cost:'500',vat_status:'VAT',vat_rate:'0.12',retail_price:'700',contractor_price:'700',wholesale_price:'700',meter_price:'0',reorder_level:'1',supplier_id:'',notes:'TEST ONLY',active:true};
const line=(price='1000')=>({id:randomUUID(),product_id:pid,quantity:'1',uom:'PCS',price,vat_mode:'VAT Inclusive',tax_treatment:'VATable',discount:'0'});
async function act(id:string,action:string){return actCommercial(owner,{id,version:(await getCommercial(owner,id)).version,request_id:randomUUID(),action});}
async function invoice(price='1000',terms='30 Days',occurred='2026-06-01T00:00:00Z'){
 const order=await saveCommercial(owner,{request_id:randomUUID(),kind:'SO',channel:'Wholesale',customer_id:customer,salesperson_id:owner.id,occurred_at:occurred,terms,tax_config_version:1,lines:[line(price)]});await act(order,'confirm');const o=await getCommercial(owner,order);const si=await createCommercialChild(owner,{order_id:order,kind:'SI',request_id:randomUUID(),occurred_at:occurred,lines:[{source_line_id:o.lines[0].id,quantity:'1'}]});await assignCommercialNumber(owner,{id:si,version:1,request_id:randomUUID(),series_id:(await query<Row>("SELECT id FROM sales_options WHERE kind='si_series' LIMIT 1")).rows[0].id,number:'TEST-FIN-'+randomUUID()});await act(si,'finalize');const ar=(await query<Row>('SELECT id FROM receivables WHERE invoice_id=$1',[si])).rows[0].id;return {order,si,ar};}
async function mop(code:string){return (await query<Row>("SELECT id FROM sales_options WHERE kind='payment_method' AND code=$1",[code])).rows[0].id;}
async function collect(ar:string,amount='100',method='bank',extra:Row={},actor=owner){return recordCollection(actor,{request_id:randomUUID(),ar_id:ar,amount,received_date:today,method_id:await mop(method),...extra});}
async function check(id:string,expected:string,status:string,extra:Row={}){return changeCheck(owner,{request_id:randomUUID(),id,expected,status,effective_date:today,reason:'TEST verified bank status',...extra});}
async function snapshot(){return JSON.stringify((await query("SELECT (SELECT jsonb_agg(t) FROM inventory_movements t) stock,(SELECT jsonb_agg(t) FROM sales t) sales,(SELECT jsonb_agg(t) FROM commercial_lines t) lines")).rows);}
test('Stage 5 receivables, financial history, isolation and security',async t=>{
 delete process.env.DATABASE_URL;process.env.LOCAL_DB_PATH=await mkdtemp(join(tmpdir(),'imperial-stage5-tests-'));await migrate();await migrate();await transaction(async db=>{await stamp(db,owner);await db.query('INSERT INTO users(id,name,email,password_hash,roles) VALUES($1,$2,$3,$4,$5)',[owner.id,owner.name,owner.email,await hashPassword(password),owner.roles]);await db.query("INSERT INTO customers(code,name) VALUES('TEST-FIN','TEST Finance Customer')");});customer=(await query<Row>("SELECT id FROM customers WHERE code='TEST-FIN'")).rows[0].id;pid=await saveMaster(owner,'products',product);await postMovement(owner,{request_id:randomUUID(),product_id:pid,kind:'IN',occurred_at:'2026-01-01T00:00:00Z',quantity:'1000',uom:'PCS',unit_cost:'500',reference:'TEST'});
 worker={id:await saveUser(owner,{name:'TEST Finance Accounting',email:'finance-accounting@example.test',roles:['ACCOUNTING'],password,active:true,permission_overrides:Object.fromEntries(permissionKeys.filter(k=>k.startsWith('ar.')||k.startsWith('collections.')).map(k=>[k,'allow']))}),name:'TEST Finance Accounting',email:'finance-accounting@example.test',roles:['ACCOUNTING']};
 restricted={id:await saveUser(owner,{name:'TEST Finance Restricted',email:'finance-restricted@example.test',roles:['WAREHOUSE'],password,active:true}),name:'TEST Finance Restricted',email:'finance-restricted@example.test',roles:['PRESIDENT_ADMIN']};
 await t.test('Every supported term including 90/custom uses Manila date',()=>{for(const terms of paymentTerms){const d=dueDate('2026-01-01T17:00:00Z',terms,'2026-05-15');assert.equal(d,terms==='Custom'?'2026-05-15':new Date(Date.parse('2026-01-02')+(parseInt(terms)||0)*86400000).toISOString().slice(0,10));}assert.throws(()=>dueDate('2026-01-01','Custom','2026-02-30'));});
 await t.test('No AR from quotation/order draft; finalized invoice unique and no inventory change',async()=>{const before=(await query<Row>('SELECT count(*) n FROM receivables')).rows[0].n;await saveCommercial(owner,{request_id:randomUUID(),kind:'Q',channel:'Retail',occurred_at:'2026-06-01T00:00:00Z',terms:'Cash',tax_config_version:1,lines:[line()]});assert.equal((await query<Row>('SELECT count(*) n FROM receivables')).rows[0].n,before);const s=(await query<Row>('SELECT count(*) n FROM inventory_movements')).rows[0].n;const r=await invoice();await Promise.all([reconcileAR(owner,{request_id:randomUUID()}),reconcileAR(worker,{request_id:randomUUID()})]);assert.equal((await query<Row>('SELECT count(*)::int n FROM receivables WHERE invoice_id=$1',[r.si])).rows[0].n,1);assert.equal((await query<Row>('SELECT count(*) n FROM inventory_movements')).rows[0].n,s);assert.equal((await getAR(owner,r.ar)).original_amount,'1000.00');});
 await t.test('Owner scenario A partial bank/check/bank; uncleared check stays outstanding',async()=>{const {ar}=await invoice('500000');await collect(ar,'200000');let r=await getAR(owner,ar);assert.equal(r.balance,'300000.00');assert.equal(r.payment_status,'Partially Paid');const c=await collect(ar,'150000','check',{check_bank:'TEST Bank',check_number:'CHECK-A',check_date:today});r=await getAR(owner,ar);assert.equal(r.balance,'300000.00');assert.equal(r.pending_checks,'150000.00');await check(c,'Received','Deposited');assert.equal((await getAR(owner,ar)).balance,'300000.00');await check(c,'Deposited','Cleared');await collect(ar,'150000');r=await getAR(owner,ar);assert.equal(r.balance,'0.00');assert.equal(r.payment_status,'Paid');assert.equal(r.collections.length,3);});
 for(const method of ['cash','gcash','maya','bank','card','platform','other'])await t.test('Actual MOP '+method+' settles AR without stock/VAT/Sale changes',async()=>{const {ar}=await invoice();const before=await snapshot();const id=await collect(ar,'1000',method,{reference:'TEST-REF-'+method});assert.equal((await getAR(owner,ar)).balance,'0.00');assert.equal(await snapshot(),before);assert((await listCollections(owner,{q:'TEST-REF-'+method})).rows.some(r=>r.id===id));});
 await t.test('Split payment, receipt duplicate/retry, overpayment and unpaid method rejection',async()=>{const {ar}=await invoice();const input={request_id:randomUUID(),ar_id:ar,amount:'500',received_date:today,method_id:await mop('bank')};const ids=await Promise.all([recordCollection(owner,input),recordCollection(owner,input)]);assert.equal(ids[0],ids[1]);assert.equal((await getAR(owner,ar)).balance,'500.00');await assert.rejects(collect(ar,'501'),/balance/);await assert.rejects(collect(ar,'1','unpaid'),/actual/);const c=await collect(ar,'500','check',{check_bank:'TEST',check_number:'SPLIT',check_date:today});await check(c,'Received','Deposited');await check(c,'Deposited','Cleared');assert.equal((await getAR(owner,ar)).payment_status,'Paid');});
 await t.test('Two individual employees cannot over-collect the same balance',async()=>{const {ar}=await invoice('100000');const result=await Promise.allSettled([collect(ar,'80000'),collect(ar,'80000','bank',{},worker)]);assert.equal(result.filter(r=>r.status==='fulfilled').length,1);assert.equal((await getAR(owner,ar)).balance,'20000.00');});
 await t.test('Collection reversal restores balance, is idempotent and leaves history',async()=>{const {ar}=await invoice();const id=await collect(ar,'1000');const d={request_id:randomUUID(),id,effective_date:today,reason:'TEST correcting collection'};await Promise.all([reverseCollection(owner,d),reverseCollection(owner,d)]);const r=await getAR(owner,ar);assert.equal(r.balance,'1000.00');assert.equal(r.payment_status,'Unpaid');assert.equal(r.collections[0].status,'Reversed');await assert.rejects(reverseCollection(owner,{...d,request_id:randomUUID()}),/already reversed/);});
 await t.test('Returned/cancelled/postdated checks never settle; cleared bounce restores AR',async()=>{for(const status of ['Cancelled','Returned / Bounced']){const {ar}=await invoice();const c=await collect(ar,'1000','check',{check_bank:'TEST',check_number:status,check_date:today});await check(c,'Received',status);assert.equal((await getAR(owner,ar)).balance,'1000.00');}const {ar}=await invoice();const c=await collect(ar,'1000','check',{check_bank:'TEST',check_number:'BOUNCE',check_date:today});await check(c,'Received','Deposited');await check(c,'Deposited','Cleared');await check(c,'Cleared','Returned / Bounced');assert.equal((await getAR(owner,ar)).balance,'1000.00');const future=await collect(ar,'1000','check',{check_bank:'TEST',check_number:'PDC',check_date:'2099-01-01'});await assert.rejects(check(future,'Received','Deposited'),/post-dated/);});
 await t.test('Conflicting check status transitions permit only one, with audit',async()=>{const {ar}=await invoice();const c=await collect(ar,'1000','check',{check_bank:'TEST',check_number:'RACE',check_date:today});const r=await Promise.allSettled([check(c,'Received','Deposited'),check(c,'Received','Cancelled')]);assert.equal(r.filter(x=>x.status==='fulfilled').length,1);assert((await query<Row>("SELECT count(*)::int n FROM audit_log WHERE entity='check_events'")).rows[0].n>0);});
 await t.test('Aging boundaries, remaining balances, paid exclusion and Manila timezone',async()=>{const {ar}=await invoice('500000','Cash');await collect(ar,'300000','cash',{received_date:'2026-06-02'});const base=(await query<Row>('SELECT * FROM receivables WHERE id=$1',[ar])).rows[0];for(const [d,b] of [['2026-06-01','Current'],['2026-06-02','1–30'],['2026-07-01','1–30'],['2026-07-02','31–60'],['2026-08-01','61–90'],['2026-09-01','Over 90']]){const p=await transaction(db=>position(db,base,d));assert.equal(p.aging_bucket,b);}assert.equal((await transaction(db=>position(db,base,'2026-07-11'))).balance,'200000.00');await collect(ar,'200000');assert.equal((await getAR(owner,ar)).aging_bucket,null);assert.equal(businessDate('2026-06-01T17:00:00Z'),'2026-06-02');});
 await t.test('Followup/promise never alters contractual dates or financial balances',async()=>{const {ar}=await invoice();const before=await getAR(owner,ar);await addFollowup(owner,{request_id:randomUUID(),ar_id:ar,followup_date:today,note:'TEST promised',promise_date:'2026-12-31'});const after=await getAR(owner,ar);assert.equal(after.due_date,before.due_date);assert.equal(after.balance,before.balance);assert.equal(after.followups[0].promise_date,'2026-12-31');});
 await t.test('Historical statement reconstructs Collections/reversals and excludes internal costs',async()=>{const {ar}=await invoice('1234');const id=await collect(ar,'234','cash',{received_date:'2026-06-02'});await reverseCollection(owner,{request_id:randomUUID(),id,effective_date:'2026-06-04',reason:'TEST historical reversal'});for(const [asOf,expected] of [['2026-06-01','1234.00'],['2026-06-03','1000.00'],['2026-06-04','1234.00']]){const s=await customerStatement(owner,customer,asOf);assert.equal(s.rows.find(r=>r.number===undefined),undefined);const number=(await getAR(owner,ar)).number;assert.equal(s.rows.find(r=>r.number===number)?.balance,expected);const json=JSON.stringify(s);for(const secret of ['cogs','profit','cost_snapshot','check_bank'])assert(!json.includes(secret));}});
 await t.test('Customer summary, salesperson/channel filters, credit and collection history',async()=>{const summary=await financeSummary(owner,customer);assert(Number(summary.outstanding)>0);assert(summary.aging);assert.equal(summary.credit_limit,'0.00');assert((await listAR(owner,{customer,agent:owner.id,channel:'Wholesale'})).rows.length>0);assert((await listCollections(owner,{customer})).rows.length>0);assert((await listCollections(owner,{q:'CHECK-A'})).rows.length===1);});
 await t.test('Legacy independent Sale actual payments recognized once, original unchanged',async()=>{const id=await saveSale(owner,{request_id:randomUUID(),channel:'Retail',customer_id:customer,occurred_at:'2026-06-01T00:00:00Z',terms:'Cash',tax_config_version:1,lines:[line()],payment:{method_id:await mop('cash'),amount_received:'400',status:'Partially Paid'}});await postSale(owner,{id,version:1,request_id:randomUUID()});const before=JSON.stringify((await query('SELECT to_jsonb(s) s FROM sales s WHERE id=$1',[id])).rows);await reconcileAR(owner,{request_id:randomUUID()});const ar=(await query<Row>('SELECT id FROM receivables WHERE sale_id=$1',[id])).rows[0].id;assert.equal((await getAR(owner,ar)).balance,'600.00');assert.equal((await getAR(owner,ar)).collections.length,1);assert.equal(JSON.stringify((await query('SELECT to_jsonb(s) s FROM sales s WHERE id=$1',[id])).rows),before);assert.equal((await legacyReport(owner)).duplicate_sources,0);});
 await t.test('Stage 4 release Sale is never a second AR; controlled return adjustment/refund pending',async()=>{const {order,ar}=await invoice();const o=await getCommercial(owner,order);const release=await createCommercialChild(owner,{order_id:order,kind:'RELEASE',request_id:randomUUID(),occurred_at:'2026-06-02T00:00:00Z',lines:[{source_line_id:o.lines[0].id,quantity:'1'}]});await act(release,'finalize');const sale=(await getCommercial(owner,release)).sale_id;assert.equal((await query('SELECT id FROM receivables WHERE sale_id=$1',[sale])).rows.length,0);await collect(ar,'1000');const sl=(await query<Row>('SELECT id FROM sale_lines WHERE sale_id=$1',[sale])).rows[0].id;const ret=await createReturn(owner,{request_id:randomUUID(),sale_id:sale,reason:'TEST financial return',requested_at:'2026-06-03T00:00:00Z',lines:[{sale_line_id:sl,quantity:'1'}]});const action=async(action:string,extra:Row={})=>changeReturn(owner,{id:ret,version:(await getReturn(owner,ret)).version,request_id:randomUUID(),action,...extra});await action('approve');await action('receive',{received_at:'2026-06-04T00:00:00Z'});await action('inspect',{conditions:(await getReturn(owner,ret)).lines.map((l:Row)=>({line_id:l.id,condition:'Damaged',notes:'TEST'}))});await action('complete');assert.equal((await getAR(owner,ar)).refund_due,'0.00');await adjustAR(owner,{request_id:randomUUID(),ar_id:ar,return_id:ret,amount:'1000',effective_date:today,reason:'TEST Owner approves reduction'});assert.equal((await getAR(owner,ar)).refund_due,'1000.00');assert.equal((await getReturn(owner,ret)).refund_status,'Not recorded');assert((await legacyReport(owner)).excluded_stage4>0);});
 await t.test('Restricted direct API, forged roles/origins, disabled accounts rejected',async()=>{const token=await authenticate(restricted.email,password);const request=(view:string,body?:Row)=>new Request('http://localhost:3000/api/finance?'+view,{method:body?'POST':'GET',headers:{host:'127.0.0.1:3000',origin:'http://127.0.0.1:3000',cookie:'imperial_session='+token},...(body?{body:JSON.stringify(body)}:{})});for(const view of ['','view=summary','view=collections','view=legacy','view=options','view=statement&customer='+customer+'&as_of='+today])assert.equal((await financeResponse(request(view))).status,403);const r=await invoice();for(const operation of ['collect','reverse','check','followup','adjust']){const data=operation==='collect'?{request_id:randomUUID(),ar_id:r.ar,amount:'1',received_date:today,method_id:await mop('cash')}:operation==='reverse'?{request_id:randomUUID(),id:randomUUID(),effective_date:today,reason:'TEST denied'}:operation==='check'?{request_id:randomUUID(),id:randomUUID(),expected:'Received',status:'Deposited',effective_date:today,reason:'TEST denied'}:operation==='followup'?{request_id:randomUUID(),ar_id:r.ar,followup_date:today,note:'TEST'}:{request_id:randomUUID(),ar_id:r.ar,return_id:randomUUID(),amount:'1',effective_date:today,reason:'TEST denied'};assert.equal((await financeResponse(request('',{operation,data}))).status,403);}const ownerToken=await authenticate(owner.email,password);for(const origin of ['http://evil.test','http://localhost:3000'])assert.equal((await financeResponse(new Request('http://localhost:3000/api/finance',{method:'POST',headers:{host:'127.0.0.1:3000',origin,cookie:'imperial_session='+ownerToken},body:JSON.stringify({operation:'reconcile',data:{request_id:randomUUID()}})}))).status,403);assert.equal((await financeResponse(request('',{operation:'reconcile',roles:['PRESIDENT_ADMIN'],data:{request_id:randomUUID()}}))).status,400);await saveUser(owner,{name:restricted.name,email:restricted.email,roles:['WAREHOUSE'],password:'',active:false},restricted.id,1);assert.equal((await financeResponse(request(''))).status,401);});

 await t.test('Each partial invoice gets its own terms-based due date without rewriting order dates',async()=>{const first=await invoice('100','30 Days','2026-05-01T00:00:00Z');const doc=(await query<Row>('SELECT * FROM commercial_documents WHERE id=$1',[first.si])).rows[0];assert.equal((await getAR(owner,first.ar)).due_date,'2026-05-31');const o=await saveCommercial(owner,{request_id:randomUUID(),kind:'SO',channel:'Retail',customer_id:customer,occurred_at:'2026-05-01T00:00:00Z',terms:'30 Days',tax_config_version:1,lines:[{...line('100'),quantity:'2'}]});await act(o,'confirm');const source=await getCommercial(owner,o);for(const dt of ['2026-06-01','2026-07-01']){const si=await createCommercialChild(owner,{order_id:o,kind:'SI',request_id:randomUUID(),occurred_at:dt+'T00:00:00Z',lines:[{source_line_id:source.lines[0].id,quantity:'1'}]});await assignCommercialNumber(owner,{id:si,version:1,request_id:randomUUID(),series_id:doc.series_id,number:'TEST-PARTIAL-'+dt});await act(si,'finalize');const ar=(await query<Row>('SELECT id FROM receivables WHERE invoice_id=$1',[si])).rows[0].id;assert.equal((await getAR(owner,ar)).due_date,dueDate(dt+'T00:00:00Z','30 Days'));}assert.equal(new Date((await getCommercial(owner,o)).due_date).toISOString().slice(0,10),'2026-05-31');});
 await t.test('Fine-grained projections hide MOP, bank, checks, credit and aging',async()=>{const id=await saveUser(owner,{name:'TEST Limited Sales',email:'limited-fin@example.test',roles:['SALES'],password,active:true,permission_overrides:{'ar.read':'allow','ar.customer':'allow','collections.read':'allow','ar.paid':'allow'}});const a:Actor={id,name:'TEST',email:'limited-fin@example.test',roles:['PRESIDENT_ADMIN']};const summary=await financeSummary(a,customer);for(const k of ['credit_limit','aging','pending_checks','overdue','collections_today'])assert(!(k in summary));const rows=(await listCollections(a)).rows;assert(rows.length);for(const row of rows)for(const k of ['method','reference','account','check_bank','check_number','events'])assert(!(k in row));assert.equal((await listCollections(a,{q:'CHECK-A'})).count,0);await assert.rejects(listCollections(a,{checks:'1'}),/permission/);await assert.rejects(listAR(a,{bucket:'Current'}),/permission/);await assert.rejects(listAR(a,{status:'Overdue'}),/permission/);await assert.rejects(changeCredit(a,{request_id:randomUUID(),customer_id:customer,credit_limit:'100',version:1,reason:'TEST forbidden'}),/permission/);});
 await t.test('Credit limit change audited, no automatic hold, stale change rejected',async()=>{const version=(await query<Row>('SELECT version FROM customers WHERE id=$1',[customer])).rows[0].version;const d={request_id:randomUUID(),customer_id:customer,credit_limit:'500000',version,reason:'TEST approved credit'};await changeCredit(owner,d);assert.equal((await financeSummary(owner,customer)).credit_limit,'500000.00');assert.equal((await query<Row>('SELECT account_status FROM customers WHERE id=$1',[customer])).rows[0].account_status,'Active');await assert.rejects(changeCredit(owner,{...d,request_id:randomUUID()}),/changed/);});
 await t.test('Due soon, overdue and paid filters use remaining balance',async()=>{const {ar}=await invoice('100','7 Days',today+'T00:00:00Z');assert((await listAR(owner,{status:'Due Soon'})).rows.some(r=>r.id===ar));assert(!(await listAR(owner,{status:'Overdue'})).rows.some(r=>r.id===ar));await collect(ar,'100');assert(!(await listAR(owner,{status:'Due Soon'})).rows.some(r=>r.id===ar));});
 await t.test('Receiving account selection saved; wrong MOP/account rejected',async()=>{await transaction(async db=>{await stamp(db,owner);await db.query("INSERT INTO sales_options(kind,code,name,behavior) VALUES('bank','test-bank','TEST Receiving Account','Bank')");});const bank=(await query<Row>("SELECT id FROM sales_options WHERE kind='bank' LIMIT 1")).rows[0];const {ar}=await invoice();const id=await collect(ar,'100','bank',{account_id:bank.id,reference:'TEST-ACCOUNT'});const c=(await listCollections(owner,{id})).rows[0];assert.equal(c.account_id,bank.id);await assert.rejects(collect(ar,'100','cash',{account_id:bank.id}),/does not apply/);assert((await listCollections(owner,{account:bank.id})).rows.some(r=>r.id===id));});
 await t.test('Legacy check remains pending despite original Sale payment label',async()=>{const id=await saveSale(owner,{request_id:randomUUID(),channel:'Retail',customer_id:customer,occurred_at:'2026-06-01T00:00:00Z',terms:'Cash',tax_config_version:1,lines:[line()],payment:{method_id:await mop('check'),amount_received:'1000',status:'Paid',check_bank:'TEST',check_number:'LEGACY-CHECK',check_date:today}});await postSale(owner,{id,version:1,request_id:randomUUID()});const ar=(await query<Row>('SELECT id FROM receivables WHERE sale_id=$1',[id])).rows[0].id;const r=await getAR(owner,ar);assert.equal(r.balance,'1000.00');assert.equal(r.pending_checks,'1000.00');assert.equal(r.payment_status,'Unpaid');assert.equal((await query<Row>('SELECT payment_status FROM sales WHERE id=$1',[id])).rows[0].payment_status,'Paid');});
 await t.test('Historical check statement changes only on clearing date; pending instruments reserve capacity',async()=>{const {ar}=await invoice();const c=await collect(ar,'1000','check',{received_date:'2026-06-02',check_bank:'TEST',check_number:'HISTORICAL-CHECK',check_date:'2026-06-02'});await assert.rejects(collect(ar,'1','cash'),/pending checks/);await check(c,'Received','Deposited',{effective_date:'2026-06-03'});await check(c,'Deposited','Cleared',{effective_date:'2026-06-04'});const raw=(await query<Row>('SELECT * FROM receivables WHERE id=$1',[ar])).rows[0];assert.equal((await transaction(db=>position(db,raw,'2026-06-03'))).balance,'1000.00');assert.equal((await transaction(db=>position(db,raw,'2026-06-04'))).balance,'0.00');});
 await t.test('Backdating cannot create hidden intermediate over-collection',async()=>{const {ar}=await invoice();const id=await collect(ar,'1000','cash',{received_date:'2026-06-10'});await reverseCollection(owner,{request_id:randomUUID(),id,effective_date:'2026-06-20',reason:'TEST reversal'});await assert.rejects(collect(ar,'1000','cash',{received_date:'2026-06-05'}),/precedes a recorded/);assert.equal((await getAR(owner,ar)).balance,'1000.00');});
 await t.test('Immutable financial events and restart persistence',async()=>{await assert.rejects(query('DELETE FROM collections'),/deletion/);await assert.rejects(query('UPDATE receivables SET original_amount=1'),/deletion/);const before=JSON.stringify(await financeSummary(owner,customer));await closeDB();assert.equal(JSON.stringify(await financeSummary(owner,customer)),before);});
});
