import {test,after} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {randomUUID} from 'node:crypto';
import {migrate} from '../lib/migrations';
import {query,transaction,closeDB} from '../lib/db';
import {hashPassword} from '../lib/password';
import {saveSale} from '../lib/sales';
import {changeSaleDocument} from '../lib/sales-documents';
import {saveMaster} from '../lib/masters';
import {saveUser} from '../lib/users';
import {stamp,type Row} from '../lib/sales-common';
import {saveCommercial,actCommercial,createCommercialChild,assignCommercialNumber,allocateLine} from '../lib/commercial';
import {getCommercial,listCommercial} from '../lib/commercial-read';
import {commercialResponse} from '../lib/commercial-api';
import {authenticate} from '../lib/sessions';
import {postMovement,stockBalances} from '../lib/inventory';
import {saveTaxSettings} from '../lib/tax-settings';
import type {Actor} from '../lib/permissions';
const owner:Actor={id:randomUUID(),name:'TEST Stage4 Owner',email:'stage4@example.test',roles:['PRESIDENT_ADMIN']};
let worker:Actor;const password='TEST Stage4 password long';let directory:string,pid:string,order:string;
after(async()=>{await closeDB();if(directory)await rm(directory,{recursive:true,force:true});});
const product={sku:'TEST-S4',name:'TEST Stage4 Breaker',brand:'TEST',category:'Breaker',primary_uom:'PCS',secondary_uom:'',conversion:'',base_price:'500',supplier_adjustment:'0',standard_cost:'500',vat_status:'VAT',vat_rate:'0.12',retail_price:'700',contractor_price:'700',wholesale_price:'700',meter_price:'0',reorder_level:'1',supplier_id:'',notes:'TEST ONLY',active:true};
const line=(quantity='10',extra:Row={})=>({id:randomUUID(),product_id:pid,quantity,uom:'PCS',price:'700',vat_mode:'VAT Exclusive',tax_treatment:'VATable',discount:'10',...extra});
const draft=(extra:Row={})=>({request_id:randomUUID(),kind:'Q',channel:'Retail',occurred_at:'2026-09-01T00:00:00Z',terms:'Cash',tax_config_version:1,lines:[line()],...extra});
async function action(id:string,action:string,extra:Row={},actor=owner){return actCommercial(actor,{id,version:(await getCommercial(owner,id)).version,request_id:randomUUID(),action,...extra});}
async function child(kind:string,qty:string,source=order){const o=await getCommercial(owner,source);return createCommercialChild(owner,{order_id:source,kind,request_id:randomUUID(),occurred_at:'2026-09-02T00:00:00Z',lines:[{source_line_id:o.lines[0].id,quantity:qty}]});}
async function physical(id:string,n:string){const d=await getCommercial(owner,id),series=(await query<Row>('SELECT id FROM sales_options WHERE kind=$1',[d.kind==='SI'?'si_series':'dr_series'])).rows[0].id;return assignCommercialNumber(owner,{id,version:d.version,request_id:randomUUID(),series_id:series,number:n});}
async function stock(){return (await stockBalances(owner,{product:pid}))[0].available;}
test('Stage 4 commercial workflow and security',async t=>{
 delete process.env.DATABASE_URL;directory=await mkdtemp(join(tmpdir(),'imperial-stage4-'));process.env.LOCAL_DB_PATH=directory;await migrate();await transaction(async db=>{await stamp(db,owner);await db.query('INSERT INTO users(id,name,email,password_hash,roles) VALUES($1,$2,$3,$4,$5)',[owner.id,owner.name,owner.email,await hashPassword(password),owner.roles]);});
 worker={id:await saveUser(owner,{name:'TEST Stage4 Warehouse Sales',email:'worker-s4@example.test',roles:['SALES','WAREHOUSE'],password,active:true,permission_overrides:{'commercial.read':'allow','orders.read':'allow','deliveries.read':'allow','deliveries.finalize':'allow','invoices.read':'allow','invoices.finalize':'allow','sales.post':'allow','inventory.issue':'allow'}}),name:'TEST Stage4 Warehouse Sales',email:'worker-s4@example.test',roles:['SALES','WAREHOUSE']};
 pid=await saveMaster(owner,'products',product);await postMovement(owner,{request_id:randomUUID(),product_id:pid,kind:'IN',occurred_at:'2026-08-01T00:00:00Z',quantity:'1000',uom:'PCS',unit_cost:'500',reference:'TEST Stage4'});
 await t.test('Quotation EX/INC/discounts and 50 lines never deduct stock',async()=>{const before=await stock();const id=await saveCommercial(owner,draft());const q=await getCommercial(owner,id);assert.equal(q.gross_total,'6300.00');assert.equal(q.lines[0].entered_price,'700.000000');const inc=await saveCommercial(owner,draft({lines:[line('10',{price:'784',vat_mode:'VAT Inclusive'})]}));assert.equal((await getCommercial(owner,inc)).gross_total,'7056.00');const big=await saveCommercial(owner,draft({lines:Array.from({length:50},()=>line('1'))}));assert.equal((await getCommercial(owner,big)).lines.length,50);assert.equal(await stock(),before);});
 await t.test('Draft edit, status transitions, conversion double click and snapshots',async()=>{const q=await saveCommercial(owner,draft());await action(q,'submit');await action(q,'approve');const input={id:q,version:(await getCommercial(owner,q)).version,request_id:randomUUID(),action:'convert'};const ids=await Promise.all([actCommercial(owner,input),actCommercial(owner,input)]);assert.equal(ids[0],ids[1]);order=ids[0];assert.equal((await getCommercial(owner,q)).status,'Converted');assert.equal((await getCommercial(owner,order)).source_id,q);await action(order,'confirm');assert.equal(await stock(),'1000.000000');await assert.rejects(action(q,'convert'),/Approve or accept/);});
 await t.test('SI before release has no Sale, inventory or COGS effect; partial invoices',async()=>{const id=await child('SI','6');await physical(id,'000401');await action(id,'finalize');assert.equal(await stock(),'1000.000000');assert.equal((await query('SELECT count(*)::int n FROM sales')).rows[0].n,0);const o=await getCommercial(owner,order);assert.equal(o.lines[0].invoiced,'6.000000');assert.equal(o.invoice_status,'Partially Invoiced');});
 await t.test('Partial DR posts one linked Sale with historical VAT after tax/master changes',async()=>{await saveTaxSettings(owner,{percent:'15',version:1,reason:'TEST historical snapshot protection'});await transaction(async db=>{await stamp(db,owner);await db.query("UPDATE products SET retail_price=999 WHERE id=$1",[pid]);});const id=await child('DR','6');await physical(id,'000401');const input={id,version:(await getCommercial(owner,id)).version,action:'finalize',request_id:randomUUID()};await Promise.all([actCommercial(owner,input),actCommercial(owner,input)]);assert.equal(await stock(),'994.000000');const doc=await getCommercial(owner,id);const sale=(await query<Row>('SELECT * FROM sales WHERE id=$1',[doc.sale_id])).rows[0];assert.equal(sale.gross_total,'3780.00');assert.equal(sale.cogs,'3000.000000');assert.equal((await query('SELECT count(*)::int n FROM sales')).rows[0].n,1);assert.equal((await getCommercial(owner,order)).delivery_status,'Partially Delivered');});
 await t.test('Concurrent deliveries cannot over-deliver; failed finalization rolls back',async()=>{const a=await child('DR','4'),b=await child('DR','4');await physical(a,'000402');await physical(b,'000403');const outcomes=await Promise.allSettled([action(a,'finalize'),action(b,'finalize',{},worker)]);assert.equal(outcomes.filter(x=>x.status==='fulfilled').length,1);assert.equal(await stock(),'990.000000');assert.equal((await getCommercial(owner,order)).delivery_status,'Delivered');await assert.rejects(child('DR','1'),/remaining/);});
 await t.test('Concurrent invoices cannot over-invoice and never repost delivered stock',async()=>{const a=await child('SI','4'),b=await child('SI','4');await physical(a,'000402');await physical(b,'000403');const before=await stock(),n=(await query('SELECT count(*)::int n FROM sales')).rows[0].n;const outcomes=await Promise.allSettled([action(a,'finalize'),action(b,'finalize',{},worker)]);assert.equal(outcomes.filter(x=>x.status==='fulfilled').length,1);assert.equal(await stock(),before);assert.equal((await query('SELECT count(*)::int n FROM sales')).rows[0].n,n);assert.equal((await getCommercial(owner,order)).invoice_status,'Invoiced');await assert.rejects(child('SI','1'),/remaining/);});
 await t.test('Physical numbers remain unique, including cancelled drafts',async()=>{const o=await saveCommercial(owner,draft({kind:'SO',tax_config_version:2,lines:[line('1')]}));await action(o,'confirm');const a=await child('SI','1',o);await assert.rejects(physical(a,'000401'),/duplicate key/);await physical(a,'000499');await action(a,'cancel',{reason:'TEST spoiled form'});const b=await child('SI','1',o);await assert.rejects(physical(b,'000499'),/duplicate key/);});
 await t.test('SI-only explicit Release Goods, no physical DR needed, linked order',async()=>{const o=await saveCommercial(owner,draft({kind:'SO',tax_config_version:2,lines:[line('2')]}));await action(o,'confirm');const r=await child('RELEASE','2',o);const before=await stock();await action(r,'finalize');assert.equal(await stock(),String(Number(before)-2)+'.000000');assert((await getCommercial(owner,r)).sale_id);await assert.rejects(action(r,'cancel',{reason:'TEST no silent reversal'}),/Finalized/);});
 await t.test('Authenticated API origin, forged-role, restricted financial projection and audit',async()=>{const id=await saveUser(owner,{name:'TEST restricted',email:'restricted-s4@example.test',roles:['WAREHOUSE'],password,active:true,permission_overrides:{'commercial.read':'allow','quotations.read':'allow','orders.read':'allow','deliveries.read':'allow','invoices.read':'allow'}});const employee:Actor={id,name:'TEST restricted',email:'restricted-s4@example.test',roles:['PRESIDENT_ADMIN']};const doc=await getCommercial(employee,order);assert(!('gross_total' in doc));assert(!('entered_price' in doc.lines[0]));await assert.rejects(saveCommercial(employee,draft()),/permission/);const token=await authenticate(owner.email,password);for(const origin of ['http://evil.test','http://localhost:3000']){const res=await commercialResponse(new Request('http://localhost:3000/api/commercial',{method:'POST',headers:{host:'127.0.0.1:3000',origin,cookie:'imperial_session='+token},body:JSON.stringify({operation:'save',data:draft()})}));assert.equal(res.status,403);}assert((await query<Row>("SELECT count(*)::int n FROM audit_log WHERE entity='commercial_documents' AND actor_id=$1",[owner.id])).rows[0].n>0);});
 await t.test('Draft editing rejects stale versions; cancelled orders cannot release',async()=>{const input=draft({kind:'SO',tax_config_version:2,lines:[line('2')]});const id=await saveCommercial(owner,input);await saveCommercial(owner,{...input,id,version:1,request_id:randomUUID(),notes:'TEST edited'});await assert.rejects(saveCommercial(owner,{...input,id,version:1,request_id:randomUUID()}),/changed/);await action(id,'cancel',{reason:'TEST cancel unfulfilled order'});await assert.rejects(child('DR','1',id),/Confirm/);});
 await t.test('50-line converted Sales Order preserves every structured product line',async()=>{const id=await saveCommercial(owner,draft({tax_config_version:2,lines:Array.from({length:55},()=>line('1'))}));await action(id,'approve');const so=await action(id,'convert');assert.equal((await getCommercial(owner,so)).lines.length,55);assert.equal((await getCommercial(owner,id)).gross_total,(await getCommercial(owner,so)).gross_total);});
 await t.test('Invoice from a finalized DR links the existing posting and blocks repeat quantities',async()=>{const so=await saveCommercial(owner,draft({kind:'SO',tax_config_version:2,lines:[line('3')]}));await action(so,'confirm');const dr=await child('DR','3',so);await physical(dr,'TEST-S4-DR-LINK');await action(dr,'finalize');const release=await getCommercial(owner,dr),count=(await query('SELECT count(*)::int n FROM sales')).rows[0].n;const data={order_id:so,delivery_id:dr,kind:'SI',request_id:randomUUID(),occurred_at:'2026-09-03T00:00:00Z',lines:[{source_line_id:release.lines[0].source_line_id,quantity:'3'}]};const si=await createCommercialChild(owner,data);await physical(si,'TEST-S4-SI-LINK');await action(si,'finalize');assert.equal((await getCommercial(owner,si)).source_delivery_id,dr);assert.equal((await query('SELECT count(*)::int n FROM sales')).rows[0].n,count);await assert.rejects(createCommercialChild(owner,{...data,request_id:randomUUID()}),/remaining|uninvoiced/);});
 await t.test('Fractional partial allocation conserves cents and net plus VAT always equals payable',async()=>{const o={id:randomUUID(),quantity:'3',stock_quantity:'3',subtotal:'1.00',discount_amount:'0.10',entered_amount:'0.90',net_amount:'0.90',vat_amount:'0.11',gross_amount:'1.01',vat_snapshot:{}};const parts=['0','1','2'].map(prior=>allocateLine(o,'1',prior));for(const k of ['subtotal','discount_amount','entered_amount','net_amount','vat_amount','gross_amount'])assert.equal(parts.reduce((n,p)=>n+Math.round(Number(p[k])*100),0),Math.round(Number(o[k as keyof typeof o])*100));for(const p of parts)assert.equal(Math.round(Number(p.net_amount)*100)+Math.round(Number(p.vat_amount)*100),Math.round(Number(p.gross_amount)*100));});
 await t.test('Required DR prevents no-DR release; UOM validation and failed stock release are atomic',async()=>{const so=await saveCommercial(owner,draft({kind:'SO',tax_config_version:2,dr_required:true,lines:[line('9999')]}));await action(so,'confirm');await assert.rejects(child('RELEASE','1',so),/requires/);await assert.rejects(child('DR','0.5',so),/quantity/);const dr=await child('DR','9999',so);await physical(dr,'TEST-S4-SHORT');const n=(await query('SELECT count(*)::int n FROM sales')).rows[0].n;await assert.rejects(action(dr,'finalize'),/insufficient/i);assert.equal((await query('SELECT count(*)::int n FROM sales')).rows[0].n,n);assert.equal((await getCommercial(owner,dr)).status,'Draft');});
 await t.test('Snapshot table updates and deletion are protected after confirmation',async()=>{await assert.rejects(transaction(async db=>{await stamp(db,owner);await db.query('UPDATE commercial_lines SET quantity=100 WHERE document_id=$1',[order]);}),/immutable/);await assert.rejects(query('DELETE FROM commercial_documents WHERE id=$1',[order]),/deletion|immutable/i);});
 await t.test('Advance invoice is matched to its later release and cannot bill that DR twice',async()=>{const docs=(await query<Row>("SELECT id FROM commercial_documents WHERE source_id=$1 AND kind='DR' AND status='Finalized' ORDER BY created_at",[order])).rows;const dr=await getCommercial(owner,docs[0].id);await assert.rejects(createCommercialChild(owner,{order_id:order,delivery_id:dr.id,kind:'SI',request_id:randomUUID(),occurred_at:'2026-09-03T00:00:00Z',lines:[{source_line_id:dr.lines[0].source_line_id,quantity:'1'}]}),/remaining|invoiced/);assert((await getCommercial(owner,order)).fulfilment_links.length>=2);});
 await t.test('Legacy physical number allocation cannot bypass the shared registry',async()=>{const {kind,...saleData}=draft({tax_config_version:2,lines:[line('1')]});const sale=await saveSale(owner,{...saleData,documents:{si:true,dr:false}});const series=(await query<Row>("SELECT id FROM sales_options WHERE kind='si_series' LIMIT 1")).rows[0].id;await assert.rejects(changeSaleDocument(owner,{sale_id:sale,kind:'SI',action:'assign',series_id:series,number:'000401'}),/duplicate|used/i);});
 await t.test('Fractional METER release keeps configured ROLL conversion and independent VAT basis',async()=>{const p=await saveMaster(owner,'products',{...product,sku:'TEST-S4-CABLE',name:'TEST Stage4 Cable',primary_uom:'ROLL',secondary_uom:'METER',conversion:'100',meter_price:'7'});await postMovement(owner,{request_id:randomUUID(),product_id:p,kind:'IN',occurred_at:'2026-08-01T00:00:00Z',quantity:'1',uom:'ROLL',unit_cost:'500',reference:'TEST cable'});const so=await saveCommercial(owner,draft({kind:'SO',tax_config_version:2,lines:[line('12.5',{product_id:p,uom:'METER',price:'7',discount:'0'})]}));await action(so,'confirm');const release=await child('RELEASE','12.5',so);await action(release,'finalize');assert.equal((await stockBalances(owner,{product:p}))[0].available,'87.500000');});
 await t.test('Linked release Sale cannot bypass invoice caps through legacy SI/DR actions',async()=>{const doc=(await query<Row>("SELECT sale_id FROM commercial_documents WHERE sale_id IS NOT NULL LIMIT 1")).rows[0];await assert.rejects(changeSaleDocument(owner,{sale_id:doc.sale_id,kind:'SI',action:'require'}),/linked Sales Order/);});
 await t.test('Direct API allows the real public origin, redacts restricted reads and rejects disabled sessions',async()=>{const token=await authenticate(owner.email,password);const req=(token:string,path:string,body?:unknown)=>new Request('http://localhost:3000/api/commercial'+path,{method:body?'POST':'GET',headers:{host:'127.0.0.1:3000',origin:'http://127.0.0.1:3000',cookie:'imperial_session='+token},...(body?{body:JSON.stringify(body)}:{})});assert.equal((await commercialResponse(req(token!,'',{operation:'save',data:draft({tax_config_version:2,lines:[line('1')]})}))).status,200);const restricted=await authenticate(worker.email,password);const read=await commercialResponse(req(restricted!,'?id='+order));assert.equal(read.status,200);const body=await read.text();for(const name of ['gross_total','entered_price','cogs','profit','cost_snapshot'])assert(!body.includes('"'+name+'"'));assert.equal((await commercialResponse(req(token!,'',{operation:'save',roles:['PRESIDENT_ADMIN'],data:draft()}))).status,400);await saveUser(owner,{name:worker.name,email:worker.email,roles:worker.roles,active:false,password:''},worker.id,1);assert.equal((await commercialResponse(req(restricted!,'?id='+order))).status,401);});
 await t.test('Restart preserves document relationships, allocations and snapshots',async()=>{const before=JSON.stringify(await getCommercial(owner,order)),stockBefore=await stock();await closeDB();assert.equal(JSON.stringify(await getCommercial(owner,order)),before);assert.equal(await stock(),stockBefore);assert((await listCommercial(owner,{kind:'SO'})).length>=1);});
});
