import Link from 'next/link';
import {requireUser} from '@/lib/auth';
import {allows} from '@/lib/permissions';
import {listCollections} from '@/lib/finance-read';
import {businessDate,dateText} from '@/lib/finance';
import {money} from '@/components/dashboard-ui';
import FinanceForm from '@/components/finance-form';
export default async function Page({params}:{params:Promise<{id:string}>}){const actor=await requireUser();if(!allows(actor,'collections.read'))return <h1>Access restricted</h1>;const {id}=await params,c=(await listCollections(actor,{id})).rows[0];if(!c)return <h1>Collection not found</h1>;const today=businessDate();return <><Link href="/collections">← Collections</Link><h1>{c.number}</h1><section className="panel"><h2>{money(c.amount)} · {c.status}</h2><p>{c.customer_name} · Physical SI {c.physical_number||'—'} · {c.received_date}</p><p>{c.method} {c.reference} {c.account}</p>{c.check_number&&<p>Check {c.check_number} · {c.check_bank} · Dated {c.check_date} · {c.check_status}</p>}{c.notes&&<p>{c.notes}</p>}<Link href={'/accounts-receivable/'+c.ar_id}>View {c.ar_number} and current balance</Link>{c.events&&<><h3>Check history</h3>{c.events.map((e:Record<string,string>,i:number)=><p key={i}>{dateText(e.effective_date)} · {e.status} · {e.reason} · {e.actor_name}</p>)}</>}{c.reversal&&<p>Reversed {dateText(c.reversal.effective_date)} · {c.reversal.reason} · {c.reversal.actor_name}</p>}</section>
 {c.check_status&&['Received','Deposited','Cleared'].includes(c.check_status)&&c.status!=='Reversed'&&allows(actor,'collections.check.update')&&<section className="panel"><h2>Update check status</h2><FinanceForm operation="check" label="Update check" fixed={{id,expected:c.check_status}} fields={[{name:'status',label:'New status',required:true,options:(c.check_status==='Received'?['Deposited','Cancelled','Returned / Bounced']:c.check_status==='Deposited'?['Cleared','Cancelled','Returned / Bounced']:['Returned / Bounced']).map(s=>({id:s,name:s}))},{name:'effective_date',label:'Effective date',type:'date',value:today,required:true},{name:'reason',label:'Reason / confirmation',required:true}]}/></section>}
 {c.status!=='Reversed'&&allows(actor,'collections.reverse')&&<details className="panel"><summary>Reverse Collection</summary><FinanceForm operation="reverse" label="Reverse Collection" fixed={{id}} fields={[{name:'effective_date',label:'Reversal date',type:'date',value:today,required:true},{name:'reason',label:'Reason',required:true}]}/></details>}</>;}
