import {formatQuantity} from '@/lib/quantity-display';
import Link from 'next/link';
import {requireUser} from '@/lib/auth';
import {allows,type Permission} from '@/lib/permissions';
import {listCommercial,canViewDocument} from '@/lib/commercial-read';
import {documentModule,type DocumentKind} from '@/lib/commercial';
import {money} from './dashboard-ui';
export const documentNames:Record<string,string>={Q:'Quotation',SO:'Sales Order',DR:'Delivery Receipt',SI:'Sales Invoice',RELEASE:'Goods Release'};
export default async function CommercialList({kind,searchParams}:{kind:DocumentKind;searchParams:Promise<Record<string,string|undefined>>}){const actor=await requireUser();if(!canViewDocument(actor,kind))return <h1>Access restricted</h1>;const f=Object.fromEntries(Object.entries(await searchParams).filter(([,v])=>v!==undefined)) as Record<string,string>;const rows=await listCommercial(actor,{...f,kind}),page=Math.max(1,Number(f.page)||1);return <><div className="page-head"><div><h1>{kind==='Q'?'Quotation History':documentNames[kind]+'s'}</h1><p>Search saved documents and review their source transactions</p></div>{['DR','SI'].includes(kind)&&allows(actor,kind==='SI'?'invoices.create':'deliveries.create')&&<Link className="button" href={kind==='SI'?'/sales-invoices/new':'/delivery-receipts/new'}>Create {documentNames[kind]}</Link>}{['Q','SO'].includes(kind)&&allows(actor,`${documentModule(kind)}.create` as Permission)&&<Link className="button" href={'/commercial/new?kind='+kind}>+ New {documentNames[kind]}</Link>}</div>{kind==='Q'&&actor.roles.includes('PRESIDENT_ADMIN')&&<p><Link href="/administration/quotation">Quotation defaults</Link></p>}<form className="panel toolbar"><label>Search<input name="q" defaultValue={f.q} placeholder="Document #, physical #, customer or salesperson"/></label><label>Status<input name="status" defaultValue={f.status}/></label><label>From<input type="date" name="from" defaultValue={f.from}/></label><label>To<input type="date" name="to" defaultValue={f.to}/></label><button>Search</button></form><div className="table-wrap"><table><thead><tr><th>Document / physical #</th><th>Date</th><th>Customer</th><th>Price List</th><th>Products</th><th>Status</th>{allows(actor,'commercial.prices')&&<th>Total</th>}</tr></thead><tbody>{rows.slice(0,50).map(r=><tr key={r.id}><td><Link href={'/commercial/'+r.id}>{r.number}</Link>{r.physical_number&&<p>Physical #{r.physical_number}</p>}</td><td>{new Date(r.occurred_at).toLocaleDateString('en-PH',{timeZone:'Asia/Manila'})}</td><td>{r.customer_snapshot.name}</td><td>{(r.kind==='Q'?r.quotation_snapshot?.price_list:undefined)||r.price_list||'Historical'}</td><td>{(r.products||[]).map((p:{product_name:string;quantity:string;uom:string},i:number)=><div key={i}>{p.product_name} × {formatQuantity(p.quantity)} {p.uom}</div>)}{r.line_count>3&&<small>+{r.line_count-3} more</small>}</td><td><span className="badge">{r.display_status||r.status}</span></td>{allows(actor,'commercial.prices')&&<td>{money(r.gross_total)}</td>}</tr>)}</tbody></table>{!rows.length&&<p className="empty">No matching documents.</p>}</div><div className="pagination">{page>1&&<Link href={'?'+new URLSearchParams({...f,page:String(page-1)})}>Previous</Link>}<span>Page {page}</span>{rows.length>50&&<Link href={'?'+new URLSearchParams({...f,page:String(page+1)})}>Next</Link>}</div></>;}
