'use client';
import {formatQuantity} from '@/lib/quantity-display';

import {useState,useRef,useEffect} from 'react';
import {useRouter} from 'next/navigation';
import {useSubmission} from './use-submission';
import type {Row} from '@/lib/sales-common';
import type {Permission} from '@/lib/permissions';
export default function CommercialControls({doc,permissions,options}:{doc:Row;permissions:Permission[];options:Row[]}){
 const locked=useRef(false);const [eventTime]=useState(()=>new Date().toISOString());useEffect(()=>{locked.current=false;setBusy(false);},[doc.id,doc.version]);
 const router=useRouter(),submission=useSubmission(),can=(p:string)=>permissions.includes(p as Permission);const [busy,setBusy]=useState(false),[error,setError]=useState(''),[reason,setReason]=useState(''),[physical,setPhysical]=useState(''),[series,setSeries]=useState(options.find(o=>o.kind===(doc.kind==='SI'?'si_series':'dr_series'))?.id||''),[kind,setKind]=useState(can('deliveries.create')?'DR':'SI'),[qty,setQty]=useState<Record<string,string>>({});
 async function send(operation:string,data:Row){if(locked.current)return;locked.current=true;setBusy(true);setError('');try{const payload={...data,request_id:submission({operation,...data})};const response=await fetch('/api/commercial',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({operation,data:payload})}),body=await response.json();if(!response.ok)throw new Error(body.error);router.push('/commercial/'+body.id);router.refresh();}catch(e){setError(e instanceof Error?e.message:'Unable to save.');locked.current=false;setBusy(false);}}
 const action=(a:string)=>send('action',{id:doc.id,version:doc.version,action:a,reason});
 const actions:Record<string,string>={submit:'Send for approval',approve:'Approve quotation',send:'Mark sent',accept:'Mark accepted',reject:'Reject quotation',expire:'Mark expired',convert:'Convert to Sales Order',confirm:'Confirm Sales Order',finalize:doc.kind==='SI'?'Finalize Invoice — no stock deduction':doc.kind==='DR'?'Finalize DR & Release Goods':'Finalize Release Goods'};
 const available:string[]=[];
 if(doc.kind==='Q'){if(doc.status==='Draft'&&can('quotations.edit'))available.push('submit');if(['Draft','For Approval'].includes(doc.status)&&can('quotations.approve'))available.push('approve');if(doc.status==='Approved'&&can('quotations.edit'))available.push('send');if(['Approved','Sent'].includes(doc.status)&&can('quotations.edit'))available.push('accept','reject','expire');if(['Approved','Accepted'].includes(doc.status)&&can('quotations.convert')&&can('orders.create'))available.push('convert');}
 if(doc.kind==='SO'&&doc.status==='Draft'&&can('orders.confirm'))available.push('confirm');
 if(['DR','SI','RELEASE'].includes(doc.kind)&&doc.status==='Draft'&&can(doc.kind==='SI'?'invoices.finalize':'deliveries.finalize'))available.push('finalize');
 return <fieldset disabled={busy} className="panel no-print" style={{minWidth:0}}>{error&&<p role="alert" className="error">{error}</p>}<div className="actions">{doc.kind==='Q'&&can('quotations.create')&&can('commercial.prices')&&can('sales.discounts')&&<button className="secondary" onClick={()=>send('duplicate',{id:doc.id,version:doc.version})}>Duplicate / Revise as new Draft</button>}{available.map(a=><button key={a} onClick={()=>action(a)}>{actions[a]}</button>)}</div>
 {['DR','SI'].includes(doc.kind)&&doc.status==='Draft'&&!doc.physical_number&&can(doc.kind==='SI'?'invoices.assign':'deliveries.assign')&&<form className="form-grid" onSubmit={e=>{e.preventDefault();send('number',{id:doc.id,version:doc.version,series_id:series,number:physical});}}><label>Physical pre-printed {doc.kind} #<input required value={physical} onChange={e=>setPhysical(e.target.value)} maxLength={80}/></label><label>Number series<select required value={series} onChange={e=>setSeries(e.target.value)}>{options.filter(o=>o.kind===(doc.kind==='SI'?'si_series':'dr_series')).map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label><button>Assign physical number</button></form>}
 {doc.kind==='SO'&&doc.status==='Confirmed'&&(can('deliveries.create')||can('invoices.create'))&&<form onSubmit={e=>{e.preventDefault();send('child',{order_id:doc.id,kind,occurred_at:eventTime,lines:doc.lines.filter((l:Row)=>Number(qty[l.id]||0)>0).map((l:Row)=>({source_line_id:l.id,quantity:qty[l.id]}))});}}><h2>Create from this order</h2><label>Document<select value={kind} onChange={e=>{setKind(e.target.value);setQty({});}}>{can('deliveries.create')&&<option value="DR">Delivery Receipt</option>}{can('invoices.create')&&<option value="SI">Sales Invoice</option>}{can('deliveries.create')&&!doc.dr_required&&<option value="RELEASE">Release Goods — no DR</option>}</select></label><p>Leave quantities at zero to omit a product. Creating a Draft does not release stock.</p><div className="table-wrap"><table><thead><tr><th>Product</th><th>Ordered</th><th>Delivered</th><th>Invoiced</th><th>Remaining</th><th>This document</th></tr></thead><tbody>{doc.lines.map((l:Row)=><tr key={l.id}><td>{l.product_name} · {l.uom}</td><td>{formatQuantity(l.quantity)}</td><td>{formatQuantity(l.delivered)}</td><td>{formatQuantity(l.invoiced)}</td><td>{formatQuantity(kind==='SI'?l.remaining_invoice:l.remaining_delivery)}</td><td><input aria-label={'This quantity '+l.product_name} type="number" min="0" max={kind==='SI'?l.remaining_invoice:l.remaining_delivery} step={l.uom==='METER'?'0.000001':'1'} value={qty[l.id]||'0'} onChange={e=>setQty({...qty,[l.id]:e.target.value})}/></td></tr>)}</tbody></table></div><button>Create Draft {kind==='RELEASE'?'Release':kind}</button></form>}
 {!['Finalized','Converted','Cancelled'].includes(doc.status)&&can(doc.kind==='SO'?'orders.cancel':'commercial.cancel')&&<details><summary>Cancel document</summary><label>Reason<input value={reason} onChange={e=>setReason(e.target.value)} minLength={3}/></label><button className="secondary" onClick={()=>action('cancel')}>Cancel with audit record</button></details>}
 {doc.status==='Finalized'&&['DR','RELEASE'].includes(doc.kind)&&can('invoices.create')&&<button onClick={()=>send('child',{order_id:doc.source_id,delivery_id:doc.id,kind:'SI',occurred_at:eventTime,lines:doc.lines.map((l:Row)=>({source_line_id:l.source_line_id,quantity:l.quantity}))})}>Create Invoice for this delivery</button>}
 {doc.status==='Finalized'&&<p>Finalized snapshots cannot be edited or silently voided. For goods returned, open the linked Sale and use the controlled Return workflow. Invoice corrections require accounting review.</p>}
 </fieldset>;
}
