'use client';
import {useRef,useState} from 'react';
import {useRouter} from 'next/navigation';
type Field={name:string;label:string;type?:string;required?:boolean;value?:string;options?:{id:string;name:string;behavior?:string}[]};
export default function FinanceForm({operation,label,fields=[],fixed={},destination}:{operation:string;label:string;fields?:Field[];fixed?:Record<string,string>;destination?:string}){
 const router=useRouter(),busy=useRef(false),request=useRef('');const [pending,setPending]=useState(false),[message,setMessage]=useState(''),[method,setMethod]=useState('');
 const behavior=fields.find(f=>f.name==='method_id')?.options?.find(o=>o.id===method)?.behavior;
 return <form onSubmit={async e=>{e.preventDefault();if(busy.current)return;busy.current=true;setPending(true);setMessage('');if(!request.current)request.current=crypto.randomUUID();const data:Record<string,string>={...fixed,request_id:request.current};for(const [k,v] of new FormData(e.currentTarget)){if(String(v))data[k]=String(v);}try{const res=await fetch('/api/finance',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({operation,data})});const body=await res.json();if(!res.ok){request.current='';throw new Error(body.error);}setMessage(label+' completed.');request.current='';if(destination)router.push(destination.replace(':id',body.id));router.refresh();}catch(error){setMessage(error instanceof Error?error.message:'Unable to save. Retry the same request.');}finally{busy.current=false;setPending(false);}}}>
 <div className="form-grid">{fields.filter(f=>!f.name.startsWith('check_')||behavior==='Check').filter(f=>f.name!=='account_id'||['Bank','Wallet','Card','Platform'].includes(behavior||'')).map(f=><label key={f.name}>{f.label}{f.options?<select name={f.name} required={f.required} defaultValue={f.value||''} onChange={e=>{if(f.name==='method_id')setMethod(e.target.value);}}><option value="">Select…</option>{f.options.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select>:<input name={f.name} type={f.type||'text'} step={f.type==='number'?'0.01':undefined} min={f.type==='number'?'0.01':undefined} required={f.required} defaultValue={f.value} onInput={e=>{e.currentTarget.defaultValue=e.currentTarget.value;}}/>}</label>)}</div><button className="button" disabled={pending}>{pending?'Saving…':label}</button>{message&&<p role="status" className="notice">{message}</p>}</form>;
}
