'use client';
import {Money} from '@/lib/vat';
import {useState} from 'react';
import CurrencyInput from './currency-input';
import {productPricing,type PricingRule} from '@/lib/product-pricing';
import {normalizeDiscount} from '@/lib/quotation-calculations';
export default function ProductPricingEditor({units,primary,record}:{units:string[];primary:string;record?:Record<string,any>}){
 const initial=(u:string):PricingRule=>record?.pricing_rules?.[u]?{...record.pricing_rules[u],selling_basis:'Base'}:{selling_basis:'Base',base:u===String(record?.primary_uom||primary)?String(record?.base_price??'0'):'',supplier:'0%',retail:'0%',contractor:'0%',net_override:record&&u===record.primary_uom?String(record.standard_cost):null,retail_override:record?String(record.selling_prices?.[u]?.Retail??(u===record.primary_uom?record.retail_price:u==='METER'?record.meter_price??'0':'0')):null,contractor_override:record?String(record.selling_prices?.[u]?.Contractor??(u===record.primary_uom?record.contractor_price:'0')):null};
 const [rules,setRules]=useState<Record<string,PricingRule>>(()=>Object.fromEntries(units.filter(Boolean).map(u=>[u,initial(u)]))),[error,setError]=useState('');
 const current=Object.fromEntries([...new Set(units.filter(Boolean))].map(u=>[u,rules[u]||initial(u)]));
 const meterPerRoll=current.ROLL?.meter_per_roll;let calculatedMeter='';try{if(primary==='ROLL'&&new Money(meterPerRoll||0).gt(0))calculatedMeter=new Money(current.ROLL?.base||0).div(meterPerRoll!).toFixed(6);}catch{}
 const change=(u:string,value:Partial<PricingRule>)=>setRules(old=>({...old,[u]:{...current[u],...value}}));
 const adjustment=(u:string,key:'supplier'|'retail'|'contractor',label:string)=><label>{label}<input aria-label={u+' '+label} value={current[u][key]} onChange={e=>change(u,{[key]:e.target.value})} onBlur={()=>{try{change(u,{[key]:normalizeDiscount(current[u][key])});setError('');}catch(e){setError((e as Error).message);}}} placeholder="+30 or -25-5-3"/></label>;
 return <fieldset className="panel"><legend>Base price & selling price calculations</legend><p>Retail and Contractor markups calculate independently from Base Price for each unit. Supplier adjustments and Net Cost stay separate from selling prices and FIFO. Existing prices stay manual until you choose Use calculated. VAT classification never changes these amounts.</p>{error&&<p role="alert">{error}</p>}<input type="hidden" name="pricing_rules" value={JSON.stringify(current)}/>{['base_price','standard_cost','retail_price','contractor_price'].map(k=><input key={k} type="hidden" name={k} value="0"/>)}<input name="supplier_adjustment" type="hidden" value={String(record?.supplier_adjustment??'0')}/>
 {primary==='ROLL'&&<label>Meter per Roll<input aria-label="Meter per Roll" type="number" min="0.000001" step="any" value={meterPerRoll||''} onChange={e=>change('ROLL',{meter_per_roll:e.target.value||undefined})}/><small>Pricing reference only; does not change inventory units or quantities.</small></label>}{calculatedMeter&&<p>Calculated Base Meter Price: ₱{new Money(calculatedMeter).toFixed(2)}/m {current.METER&&<button type="button" className="secondary" onClick={()=>change('METER',{base:calculatedMeter})}>Use calculated Base Meter Price</button>}<small>Base Roll Price ÷ Meter per Roll. Existing meter prices change only when you apply this value.</small></p>}
 {Object.entries(current).map(([u,rule])=>{let result:ReturnType<typeof productPricing>|undefined;try{result=productPricing(rule);}catch{}const value=(key:'net'|'retail'|'contractor',label:string)=>{const override=(key+'_override') as 'net_override'|'retail_override'|'contractor_override';return <label>{label}<CurrencyInput aria-label={u+' '+label} value={result?.[key]??rule[override]??''} required onValueChange={v=>change(u,{[override]:v})}/><small>{rule[override]===null?'Calculated':'Manual override — retained when inputs change'}</small>{rule[override]!==null&&<button type="button" className="secondary" onClick={()=>change(u,{[override]:null})}>Use calculated {label}</button>}</label>;};return <section key={u}><h3>{u}</h3><div className="form-grid"><label>{u==='METER'?'Base Price per Meter':'Base Price'}<CurrencyInput aria-label={u+' '+(u==='METER'?'Base Price per Meter':'Base Price')} value={rule.base} required onValueChange={v=>change(u,{base:v})}/></label>{adjustment(u,'supplier','Supplier Adjustment')}{value('net','Net Cost')}{adjustment(u,'retail','Retail Markup %')}{value('retail',u==='METER'?'Retail Price per Meter':'Retail Price')}{adjustment(u,'contractor','Contractor Markup %')}{value('contractor',u==='METER'?'Contractor Price per Meter':'Contractor Price')}</div>{!result&&<p role="alert">Complete valid prices and adjustments for {u} before saving.</p>}</section>;})}
 <small>Full calculation inputs are retained. Transaction unit prices use Imperial’s existing six-decimal precision; monetary display uses two decimals.</small></fieldset>;
}
