import {productPricing,type PricingRule} from '@/lib/product-pricing';
import Link from 'next/link';
import {allows,type Actor} from '@/lib/permissions';
import {quantityText} from '@/lib/format';
import {formatPesos} from '@/lib/currency-display';
const moneyText=(value:unknown)=>formatPesos(String(value??0)).replace(/^₱/,'');
import type {VatSnapshot} from '@/lib/vat';
import VatSummary from './vat-summary';
export default function ProductDetails({product:p,actor,saved=false,suppliers=[]}:{product:Record<string,unknown>;actor:Actor;saved?:boolean;suppliers?:Record<string,unknown>[]}){
 return <><Link href="/masters/products">← Back to products</Link><div className="page-head"><div><h1>{String(p.name)}</h1><p>{String(p.sku)} · <span className={`badge ${p.active?'':'off'}`}>{p.active?'Active':'Inactive'}</span></p></div>{allows(actor,'products.write')&&<Link className="button" href="?edit=1">Edit product</Link>}</div>{saved&&<p className="success" role="status">Product saved successfully.</p>}<section className="panel"><dl>{[['Brand',p.brand],['Category',p.category],['Unit',p.primary_uom],['Low Stock Level',`${quantityText(p.reorder_level)} ${p.primary_uom}`],['Notes',p.notes]].map(([label,value])=><div key={String(label)}><dt>{String(label)}</dt><dd>{String(value||'—')}</dd></div>)}</dl>
 {allows(actor,'products.cost')&&<p>Cost: ₱{moneyText(p.standard_cost)} · Supplier tag: {p.cost_entry_mode==='VAT Inclusive'?'VAT INC':'VAT EX'} (information only)</p>}
 {allows(actor,'products.prices')&&<table><thead><tr><th>UOM</th><th>Retail</th><th>Contractor</th></tr></thead><tbody>{[p.primary_uom,p.secondary_uom].filter(Boolean).map(u=>{const prices=(p.selling_prices as Record<string,Record<string,string>>|null)?.[String(u)];return <tr key={String(u)}><td>{String(u)}</td><td>{prices?.Retail!==undefined?'₱'+moneyText(prices.Retail):u===p.primary_uom?'₱'+moneyText(p.retail_price):u==='METER'&&p.meter_price!==null?'₱'+moneyText(p.meter_price):'Not configured'}</td><td>{prices?.Contractor!==undefined?'₱'+moneyText(prices.Contractor):u===p.primary_uom?'₱'+moneyText(p.contractor_price):'Not configured'}</td></tr>;})}</tbody></table>}
 {!!p.pricing_rules&&allows(actor,'products.cost')&&allows(actor,'products.prices')&&<div className="table-wrap"><table><thead><tr><th>UOM</th><th>Base Price</th><th>Supplier Adjustment</th><th>Net Cost</th><th>Retail Adjustment</th><th>Retail Price</th><th>Contractor Adjustment</th><th>Contractor Price</th></tr></thead><tbody>{Object.entries(p.pricing_rules as Record<string,PricingRule>).map(([u,r])=>{const v=productPricing(r);return <tr key={u}><td>{u}</td><td>₱{moneyText(r.base)}</td><td>{r.supplier}</td><td>₱{moneyText(v.net)}<small>{r.net_override===null?'Calculated':'Manual override'}</small></td><td>{r.retail}</td><td>₱{moneyText(v.retail)}<small>{r.retail_override===null?'Calculated':'Manual override'}</small></td><td>{r.contractor}</td><td>₱{moneyText(v.contractor)}<small>{r.contractor_override===null?'Calculated':'Manual override'}</small></td></tr>;})}</tbody></table></div>}<details className="advanced"><summary>View Details</summary>{!!p.secondary_uom&&<p>1 {String(p.primary_uom)} = {quantityText(p.conversion)} {String(p.secondary_uom)}</p>}
 {allows(actor,'products.cost')&&<p>Default supplier: {String(suppliers.find(s=>s.id===p.supplier_id)?.name||(p.supplier_id?'Saved supplier':'Not specified'))}</p>}
 {!p.pricing_rules&&allows(actor,'products.cost')&&<p>Base price: ₱{moneyText(p.base_price)} · Supplier adjustment: {String(p.supplier_adjustment)}</p>}
 {allows(actor,'products.cost')&&allows(actor,'products.prices')&&<><h3>Calculated estimates</h3><p>Estimated profit: {p.estimated_profit===null?'—':`₱${moneyText(p.estimated_profit)}`} · Markup: {String(p.markup_percent??'—')}% · Margin: {String(p.profit_margin_percent??'—')}%</p><p className="muted">{String(p.profit_basis||'')} These are estimates, not accounting profit.</p></>}
 <p className="muted">Created: {new Date(String(p.created_at)).toLocaleString('en-PH',{timeZone:'Asia/Manila'})}<br/>Updated: {new Date(String(p.updated_at)).toLocaleString('en-PH',{timeZone:'Asia/Manila'})}</p></details></section>{allows(actor,'inventory.read')&&<Link className="button secondary" href={`/inventory?product=${p.id}`}>View stock & activity</Link>}</>;
}
