'use client';
import VatReferenceSelector from './vat-reference-selector';

import {repriceQuotationRows,quotationProductForList,type QuotationPriceList,quotationPriceLists,quotationUoms} from '@/lib/quotation-pricing';

import {useState,useRef,type ReactNode} from 'react';
import {useRouter} from 'next/navigation';
import Link from 'next/link';
import {useSubmission} from './use-submission';
import CurrencyInput from './currency-input';
import {formatPesos} from '@/lib/currency-display';
import QuantityInput from './quantity-input';
import {formatQuantity} from '@/lib/quantity-display';
import QuotationLookup from './quotation-lookup';
import {quotationDiscountDisplay,blankQuotationRow,selectQuotationProduct,removeQuotationRow,clearQuotationForm} from '@/lib/quotation-form';
import {quotationLine,normalizeDiscount,savedDiscount,calculateFees,documentTotals} from '@/lib/quotation-calculations';
import {paymentTerms} from '@/lib/sales-calculations';
import {Money,type TaxConfig} from '@/lib/vat';
import type {Permission} from '@/lib/permissions';
import type {Row} from '@/lib/sales-common';
const money=(v:unknown)=>formatPesos(String(v||0));
const contactValue=(c:Row|null)=>c?.quotation_contact??[c?.contact_person,c?.phone,c?.email].filter(Boolean).join(' · ');
const units=['PCS','ROLL','BOX','METER'];
export default function QuotationWorkspace({initial,config,permissions,defaults,employee,controls}:{initial?:Row;config:TaxConfig;permissions:Permission[];defaults?:Row;employee?:Row;controls?:ReactNode}){
 const [vatReference,setVatReference]=useState(initial?.vat_reference_mode||'Excluded');
 const [priceList,setPriceList]=useState<QuotationPriceList>(initial?.quotation_snapshot?.price_list||initial?.price_list||'None'),[documentFlow,setDocumentFlow]=useState(initial?.document_flow||'SI');
 const router=useRouter(),submission=useSubmission(),locked=useRef(false),can=(p:Permission)=>permissions.includes(p);
 const editable=initial?initial.status==='Draft'&&can('quotations.edit'):can('quotations.create');
 const canFees=editable&&can('quotations.fees');
 const [dirty,setDirty]=useState(Boolean(initial?.status==='Draft'&&initial?.lines?.some((l:Row)=>l.vat_snapshot?.policy!=='ENTERED_AMOUNTS_NO_VAT_V1'))),[busy,setBusy]=useState(false),[error,setError]=useState(''),[confirmClear,setConfirmClear]=useState(false),[setup,setSetup]=useState(false);
 const [customer,setCustomer]=useState<Row|null>(initial?.customer_id?initial.customer_snapshot:null),[agent,setAgent]=useState<Row|null>(initial?.salesperson_snapshot||employee||null);
 const [date,setDate]=useState(initial?new Date(new Date(initial.occurred_at).getTime()+8*3600000).toISOString().slice(0,10):new Date(Date.now()+8*3600000).toISOString().slice(0,10));
 const [terms,setTerms]=useState(initial?.terms||'Cash'),[customTerms,setCustomTerms]=useState(initial?.custom_terms||''),[customDate,setCustomDate]=useState(initial?.due_date?new Date(initial.due_date).toISOString().slice(0,10):'');
 const [notes,setNotes]=useState(initial?.notes??defaults?.notes??''),[disclaimer,setDisclaimer]=useState(initial?.quotation_snapshot?.disclaimer??defaults?.disclaimer??'');
 const [lines,setLines]=useState<Row[]>((initial?.lines||[]).map((l:Row)=>({...l,price:l.entered_price,discount:quotationDiscountDisplay(savedDiscount(l)),unit_defaults:l.unit_defaults||[{uom:l.uom,price:l.entered_price,vat_mode:l.vat_mode,tax_treatment:l.tax_treatment}]})));
 const [fees,setFees]=useState<Row[]>((initial?.fees||[]).map((f:Row)=>({id:f.id,description:f.description,amount:f.amount,vat_mode:f.vat_mode,tax_treatment:f.tax_treatment})));
 const change=(fn:()=>void)=>{setDirty(true);fn();};
 const patch=(id:string,value:Row)=>change(()=>setLines(old=>old.map(l=>l.id===id?{...l,...value}:l)));
 const patchFee=(id:string,value:Row)=>change(()=>setFees(old=>old.map(f=>f.id===id?{...f,...value}:f)));
 const clear=()=>clearQuotationForm(dirty,()=>true,url=>window.location.assign(url));
 let calculated:Row[]=[],feeAmounts:Row[]=[],totals:ReturnType<typeof documentTotals>|null=null;
 try{calculated=lines.map(l=>quotationLine(l.price,l.quantity,l.discount,l.vat_mode,l.tax_treatment,config,2));feeAmounts=calculateFees(fees as Parameters<typeof calculateFees>[0],config);totals=documentTotals(calculated,feeAmounts);}catch{}
 if(initial&&!editable){calculated=initial.lines;feeAmounts=initial.fees||[];totals=initial as ReturnType<typeof documentTotals>;}
 const totalSales=calculated.reduce((n,l)=>n.plus(l.vat_snapshot?.exact_amount??l.gross_amount??0),new Money(0)),feeTotal=feeAmounts.reduce((n,f)=>n.plus(f.gross_amount??0),new Money(0));
 function addFee(description:string){change(()=>setFees(old=>[...old,{id:crypto.randomUUID(),description,amount:'0',vat_mode:'VAT Exclusive',tax_treatment:'VATable'}]));setSetup(true);}
 async function save(e:React.FormEvent){e.preventDefault();if(locked.current||!editable)return;setError('');if(!customer&&(initial?.channel||'Wholesale')==='Wholesale'){setError('Choose a client from the search results.');return;}if(!totals||!lines.length){setError('Add items and check quantities, prices and charge setup.');setSetup(true);return;}
 locked.current=true;setBusy(true);try{
 const data={...(initial?{id:initial.id,version:initial.version}:{}),kind:'Q',vat_reference_mode:vatReference,quotation_price_list:priceList,price_list:priceList==='None'?'Retail':priceList,document_flow:documentFlow,company:initial?.company||'Imperial Electrical and Industrial Supply Corporation',channel:initial?.channel||'Wholesale',platform_id:initial?.platform_id||'',customer_id:customer?.id||'',...(customer?{customer_override:{quotation_contact:contactValue(customer),billing_address:customer.billing_address||'',contact_person:customer.contact_person||'',phone:customer.phone||'',email:customer.email||''}}:{}),salesperson_id:agent?.id||'',occurred_at:initial&&date===new Date(new Date(initial.occurred_at).getTime()+8*3600000).toISOString().slice(0,10)?initial.occurred_at:new Date(date+'T00:00:00+08:00').toISOString(),terms,custom_terms:customTerms,custom_due_date:customDate,notes,disclaimer,tax_config_version:config.version,fees,si_required:initial?.si_required||false,dr_required:initial?.dr_required||false,payment_method_id:initial?.payment_method_id||'',lines:lines.map(l=>({id:l.id,product_id:l.product_id,family_id:l.family_id,quantity:l.quantity,uom:l.uom,price:l.price,discount:normalizeDiscount(l.discount),adjustment_version:2,manual_price_override:l.manual_price_override??l.vat_snapshot?.quotation_pricing?.manual_override,vat_mode:l.vat_mode,tax_treatment:l.tax_treatment}))};
 const response=await fetch('/api/commercial',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({operation:'save',data:{...data,request_id:submission(data)}})}),body=await response.json();if(!response.ok)throw new Error(body.error);setDirty(false);router.replace('/quotations?id='+body.id);router.refresh();
 }catch(e){setError(e instanceof Error?e.message:'Unable to save quotation.');locked.current=false;setBusy(false);}}
 const field=(label:string,value:string,update:(value:string)=>void,extra:Record<string,unknown>={})=><><input aria-label={label} value={value} onChange={e=>change(()=>update(e.target.value))} {...extra}/><span className="q-print-value">{value||(label.startsWith('Discount ')?'':'—')}</span></>;
 return <div className="quotation-workspace"><form onSubmit={save} onChangeCapture={()=>setDirty(true)}>
 <div className="q-toolbar no-print"><button type="submit" disabled={busy||!editable}>{busy?'Saving…':'Save'}</button><button type="button" className="secondary" disabled={busy} onClick={()=>dirty?setConfirmClear(true):clear()}>Clear Form</button><button type="button" className="secondary" onClick={()=>window.print()}>Print Quotation</button>{initial&&!dirty?<a className="button secondary" href={'/quotation-document/'+initial.id+'?download=1'}>Download PDF</a>:<button type="button" className="secondary" onClick={()=>setError('Save this quotation before downloading its PDF.')}>Download PDF</button>}<Link className="button secondary" href="/quotations/history">Open / History</Link><span role="status">{dirty?'Unsaved changes':initial?'Saved · '+initial.status:'New quotation'}</span></div>
 {error&&<p role="alert" className="error no-print">{error}</p>}{confirmClear&&<section className="panel no-print" role="alertdialog" aria-label="Clear unsaved quotation"><h2>Clear unsaved changes?</h2><p>Saved quotations and other employees’ forms will not change.</p><button type="button" className="secondary" onClick={()=>setConfirmClear(false)}>Keep Editing</button> <button type="button" onClick={clear}>Clear Unsaved Form</button></section>}
 {initial?.lines?.some((l:Row)=>l.vat_snapshot?.policy!=='ENTERED_AMOUNTS_NO_VAT_V1')&&<p className="notice no-print">This historical quotation retains its saved amounts. {editable?'The editable preview uses the new entered-price rules; Save explicitly records a revised draft.':'Duplicate it to prepare a new quotation under the entered-price rules.'}</p>}
 <div className="q-internal-controls panel form-grid no-print"><VatReferenceSelector value={vatReference} disabled={!editable||busy} onChange={v=>change(()=>setVatReference(v))}/><label>Price List<select aria-label="Price List" value={priceList} disabled={!editable||busy} onChange={e=>change(()=>{const list=e.target.value as QuotationPriceList;setPriceList(list);setLines(old=>repriceQuotationRows(old,list));})}>{quotationPriceLists.map(list=><option key={list} value={list}>{list.toUpperCase()}</option>)}</select><small>Changing the list or UOM loads that master price. You can then override Unit Price.</small></label><label>Document Flow<select aria-label="Document Flow" disabled={!editable||busy} value={documentFlow} onChange={e=>change(()=>setDocumentFlow(e.target.value))}><option>SI</option><option>DR Only</option></select></label></div> <fieldset disabled={!editable||busy} className="q-paper">
 <header className="q-letterhead"><div className="q-logo"><img src="/quotation/reference.png" alt="Imperial"/></div><strong>{initial?.company||'IMPERIAL ELECTRICAL AND INDUSTRIAL SUPPLY CORPORATION'}</strong></header><h1>QUOTATION FORM</h1>
 <div className="q-document-meta"><div><strong>Quotation No.: {initial?.number||'Assigned on save'}</strong><p className="q-status">{initial?.status||'DRAFT'}</p></div><div className="q-meta-fields"><label>Agent<QuotationLookup kind="agents" label="Agent" value={agent?.name||''} onSelect={r=>change(()=>setAgent(r))}/></label><label>Date<span>{field('Date',date,setDate,{type:'date',required:true})}</span></label><label>Terms<span><select aria-label="Terms" value={terms} onChange={e=>change(()=>setTerms(e.target.value))}>{paymentTerms.map(t=><option key={t}>{t}</option>)}</select><span className="q-print-value">{terms==='Custom'?customTerms:terms}</span></span></label>{terms==='Custom'&&<><label>Terms details<span>{field('Custom terms',customTerms,setCustomTerms,{required:true})}</span></label><label>Due date<span>{field('Due date',customDate,setCustomDate,{type:'date',required:true})}</span></label></>}</div></div>
 <div className="q-client"><label><b>Client:</b><QuotationLookup kind="customers" label="Client" value={customer?.name||initial?.customer_snapshot?.name||''} onSelect={r=>change(()=>{setCustomer(r);if(!lines.length&&r.default_price_list)setPriceList(r.default_price_list);if(paymentTerms.includes(r.payment_terms))setTerms(r.payment_terms);})}/></label><label><b>Address:</b><span>{field('Address',customer?.billing_address||'',value=>setCustomer(customer?{...customer,billing_address:value}:null),{disabled:!customer,maxLength:1000})}</span></label><label><b>Contact:</b><span>{field('Contact',contactValue(customer),value=>setCustomer(customer?{...customer,quotation_contact:value}:null),{disabled:!customer,maxLength:1000})}</span></label></div>
 <table className="q-items"><colgroup><col/><col style={{width:80}}/><col style={{width:82}}/><col style={{width:105}}/><col style={{width:105}}/><col style={{width:108}}/><col className="no-print" style={{width:30}}/></colgroup><thead><tr>{['ITEM DESCRIPTION','QUANTITY','UOM','UNIT PRICE','DISCOUNT','AMOUNT'].map(s=><th key={s}>{s}</th>)}<th className="no-print"/></tr></thead><tbody>{lines.map((l,i)=><tr key={l.id}><td><QuotationLookup kind="products" label={'Item Description '+(i+1)} value={l.family_name||l.product_name} onSelect={r=>{change(()=>setLines(old=>selectQuotationProduct(old,l.id,quotationProductForList(r,priceList))));}}/>{l.family_id&&<small className="no-print">Inventory SKU: {l.sku||'Select UOM'}</small>}</td><td><QuantityInput aria-label={'Quantity '+(i+1)} value={l.quantity} onChange={e=>patch(l.id,{quantity:e.target.value})} type="number" min={l.uom==='METER'?'0.000001':'1'} step={l.uom==='METER'?'0.000001':'1'} required/><span className="q-print-value">{formatQuantity(l.quantity)}</span></td><td><select aria-label={'UOM '+(i+1)} value={l.uom} required onChange={e=>{const d=l.unit_defaults.find((v:Row)=>v.uom===e.target.value);patch(l.id,{...d,uom:e.target.value,price:d?.prices?.[priceList]??'',manual_price_override:false});}}><option value="">—</option>{Array.from(new Set([...l.unit_defaults.map((d:Row)=>d.uom),...(l.uom?[l.uom]:[])])).map(u=><option key={String(u)}>{String(u)}</option>)}</select><span className="q-print-value">{l.uom}</span></td><td><div className="q-currency"><CurrencyInput aria-label={'Unit Price '+(i+1)} value={l.price} onValueChange={value=>patch(l.id,{price:value,manual_price_override:true})} readOnly={!can('sales.override')} required/><span className="q-print-money">{money(l.price)}</span></div></td><td>{field('Discount '+(i+1),l.discount,value=>patch(l.id,{discount:value}),{readOnly:!can('sales.discount.apply'),maxLength:150,placeholder:'',onBlur:()=>{try{const value=quotationDiscountDisplay(l.discount);if(value!==l.discount)patch(l.id,{discount:value});setError('');}catch(e){setError(e instanceof Error?e.message:'Check discount.');}}})}</td><td className="q-amount">{calculated[i]?money(calculated[i].gross_amount):'—'}</td><td className="no-print"><button type="button" className="q-remove" aria-label={'Remove row '+(i+1)} onClick={()=>change(()=>setLines(old=>removeQuotationRow(old,l.id)))}>×</button></td></tr>)}</tbody></table>
 <div className="q-row-tools no-print"><button type="button" className="secondary" onClick={()=>change(()=>setLines(old=>[...old,blankQuotationRow(crypto.randomUUID())]))}>+ Add Row</button>{!lines.length&&<span>Add an item to start your quotation.</span>}</div>
 <section className="q-bottom"><div className="q-fees">{fees.map((f,i)=><div className="q-fee" key={f.id}><span>{field('Fee description '+(i+1),f.description,value=>patchFee(f.id,{description:value}),{readOnly:!canFees,required:true,maxLength:200})}</span><div className="q-currency"><CurrencyInput aria-label={'Fee amount '+(i+1)} value={f.amount} onValueChange={value=>patchFee(f.id,{amount:value})} readOnly={!canFees} required/><span className="q-print-money">{feeAmounts[i]?money(feeAmounts[i].gross_amount):'—'}</span></div>{canFees&&<button type="button" className="q-remove no-print" aria-label={'Remove fee '+(i+1)} onClick={()=>change(()=>setFees(old=>old.filter(v=>v.id!==f.id)))}>×</button>}</div>)}{canFees&&<div className="q-row-tools no-print"><button type="button" className="secondary" onClick={()=>addFee('Delivery Fee')}>+ Delivery Fee</button><button type="button" className="secondary" onClick={()=>addFee('')}>+ Other Fee</button></div>}</div><table className="q-totals"><tbody><tr><th>Total Sales</th><td>{totals?money(totalSales):'—'}</td></tr><tr><th>Other Fees</th><td>{totals?money(feeTotal):'—'}</td></tr><tr><th>TOTAL AMOUNT DUE</th><td>{totals?money(totals.gross_total):'—'}</td></tr></tbody></table></section>
 <label className="q-notes">Notes:<textarea aria-label="Notes" value={notes} onChange={e=>change(()=>setNotes(e.target.value))} maxLength={1000}/><span className="q-print-value">{notes}</span></label><div className="q-disclaimer">{disclaimer}</div>
 </fieldset>
 <details className="no-print"><summary>Quotation note settings</summary><textarea aria-label="Quotation disclaimer" value={disclaimer} onChange={e=>change(()=>setDisclaimer(e.target.value))} maxLength={1500}/></details>
 </form>{initial&&<fieldset className="q-document-actions no-print" disabled={dirty||busy}>{dirty&&<p>Save changes before using document actions.</p>}{controls}</fieldset>}</div>;
}
