'use client';
import {useState} from 'react';
import {useRouter} from 'next/navigation';
import {useSubmission} from './use-submission';
import {Money} from '@/lib/vat';
import type {Row} from '@/lib/sales-common';
export default function ReturnEntry({sale,kind}:{sale:Row;kind:'Return'|'Cancellation'}){
 const submission=useSubmission();const [requestedAt]=useState(()=>new Date().toISOString());
 const router=useRouter();const remaining=sale.lines.filter((l:Row)=>new Money(l.quantity).gt(l.returned_quantity));const [quantities,setQuantities]=useState<Record<string,string>>(Object.fromEntries(remaining.map((l:Row)=>[l.id,kind==='Cancellation'?new Money(l.quantity).minus(l.returned_quantity).toFixed():'0']))),[reason,setReason]=useState(''),[reference,setReference]=useState(''),[notes,setNotes]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const data={request_id:crypto.randomUUID(),sale_id:sale.id,kind,reason,requested_at:requestedAt,platform_case_reference:reference,notes,lines:remaining.filter((l:Row)=>new Money(quantities[l.id]||0).gt(0)).map((l:Row)=>({sale_line_id:l.id,quantity:quantities[l.id]}))};data.request_id=submission({...data,request_id:undefined});const res=await fetch('/api/returns',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({operation:'create',data})}),body=await res.json();if(!res.ok)throw new Error(body.error);router.push('/returns/'+body.id);router.refresh();}catch(e){setError(e instanceof Error?e.message:'Unable to save Return.');}finally{setBusy(false);}}
 return <form onSubmit={submit}><p className="notice">This request does not change stock or record a refund. Receive and inspect the goods before restocking. The original Sale and documents remain unchanged.</p><section className="panel form-grid"><label>Reason<input required minLength={3} maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)}/></label>{sale.channel==='Online'&&<label>Platform Return / Case Reference<input value={reference} onChange={e=>setReference(e.target.value)} maxLength={160}/></label>}<label>Notes<textarea value={notes} onChange={e=>setNotes(e.target.value)}/></label></section><div className="table-wrap"><table><thead><tr><th>Original product</th><th>Sold</th><th>Previously returned</th><th>Return quantity</th></tr></thead><tbody>{remaining.map((l:Row)=><tr key={l.id}><td>{l.product_name}</td><td>{l.quantity} {l.uom}</td><td>{l.returned_quantity} {l.uom}</td><td><input aria-label={'Return quantity '+l.product_name} type="number" min="0" max={new Money(l.quantity).minus(l.returned_quantity).toFixed()} step={l.uom==='METER'?'0.000001':'1'} value={quantities[l.id]} readOnly={kind==='Cancellation'} onChange={e=>setQuantities({...quantities,[l.id]:e.target.value})}/></td></tr>)}</tbody></table></div>{error&&<p role="alert" className="error">{error}</p>}<div className="actions"><button disabled={busy||!remaining.length}>{busy?'Saving…':'Create '+kind+' Request'}</button></div></form>;
}
