'use client';
import {useState} from 'react';
import {useRouter} from 'next/navigation';
import {useSubmission} from './use-submission';
import {returnConditions} from '@/lib/return-calculations';
import type {Permission} from '@/lib/permissions';
import type {Row} from '@/lib/sales-common';
export default function ReturnActions({record,permissions}:{record:Row;permissions:Permission[]}){
 const submission=useSubmission();
 const router=useRouter();const [error,setError]=useState(''),[busy,setBusy]=useState(false),[reason,setReason]=useState(''),[received,setReceived]=useState(new Date(Date.now()+8*3600000+1000).toISOString().slice(0,19)),[conditions,setConditions]=useState<Record<string,string>>(Object.fromEntries(record.lines.map((l:Row)=>[l.id,l.condition])));
 const can=(p:Permission)=>permissions.includes(p)&&(record.kind!=='Cancellation'||permissions.includes('sales.cancel'));
 async function act(action:string){setBusy(true);setError('');try{const data={id:record.id,version:record.version,request_id:crypto.randomUUID(),action,reason,...(action==='receive'?{received_at:new Date(received+'+08:00').toISOString()}:{}),...(action==='inspect'?{conditions:record.lines.map((l:Row)=>({line_id:l.id,condition:conditions[l.id],notes:reason}))}:{})};data.request_id=submission({...data,request_id:undefined});const res=await fetch('/api/returns',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({operation:'change',data})}),body=await res.json();if(!res.ok)throw new Error(body.error);router.refresh();}catch(e){setError(e instanceof Error?e.message:'Unable to update Return.');}finally{setBusy(false);}}
 return <section className="panel"><h2>Return workflow</h2>{error&&<p role="alert" className="error">{error}</p>}{!['Completed','Cancelled','Rejected'].includes(record.status)&&<label>Action notes / reason<input value={reason} onChange={e=>setReason(e.target.value)} maxLength={1000}/></label>}<div className="actions">{record.status==='Return Requested'&&can('returns.approve')&&<button disabled={busy} onClick={()=>act('approve')}>Approve Return</button>}{record.status==='Approved'&&can('returns.receive')&&<button disabled={busy} onClick={()=>act('transit')}>Mark In Transit</button>}{['Approved','In Transit'].includes(record.status)&&can('returns.receive')&&<div><label>Goods received at (Philippines)<input type="datetime-local" step="1" required value={received} onChange={e=>setReceived(e.target.value)}/></label><button disabled={busy||!received} onClick={()=>act('receive')}>Confirm Goods Received</button></div>}{['Return Requested','Approved','In Transit','Received','Inspected'].includes(record.status)&&can('returns.reject')&&<><button className="button secondary" disabled={busy||reason.trim().length<3} onClick={()=>act('reject')}>Reject Request</button>{['Return Requested','Approved','In Transit'].includes(record.status)&&<button className="button secondary" disabled={busy||reason.trim().length<3} onClick={()=>act('cancel')}>Cancel Request</button>}</>}</div>
 {['Received','Inspected'].includes(record.status)&&can('returns.condition')&&<><h3>Inspection</h3><div className="form-grid">{record.lines.map((l:Row)=><label key={l.id}>{l.product_name} · {l.quantity} {l.uom}<select value={conditions[l.id]} onChange={e=>setConditions({...conditions,[l.id]:e.target.value})}>{returnConditions.map(c=><option key={c}>{c}</option>)}</select></label>)}</div><div className="actions"><button disabled={busy} onClick={()=>act('inspect')}>Save Inspection</button></div></>}
 <div className="actions">{record.status==='Inspected'&&record.lines.some((l:Row)=>l.condition==='Sellable'&&!l.movement_id)&&can('returns.restock')&&<button disabled={busy} onClick={()=>act('restock')}>Restock Sellable Goods</button>}{['Inspected','Restocked'].includes(record.status)&&can('returns.complete')&&<button disabled={busy} onClick={()=>act('complete')}>Complete Return</button>}</div><p className="muted">Receipt and inspection keep the Return pending acceptance. Restocking or completing accepts it. Damaged, defective and uninspected goods do not enter available stock. Refunds are separate; this workflow does not record a refund.</p></section>;
}
