'use client';
import {useState} from 'react';
import {useRouter} from 'next/navigation';
import Link from 'next/link';
import type {Permission} from '@/lib/permissions';
import type {Row} from '@/lib/sales-common';
export default function SaleActions({sale,options,permissions}:{sale:Row;options:Row[];permissions:Permission[]}){
 const router=useRouter(),can=(p:Permission)=>permissions.includes(p);const [error,setError]=useState(''),[busy,setBusy]=useState(false),[reason,setReason]=useState(''),[series,setSeries]=useState<Record<string,string>>({}),[numbers,setNumbers]=useState<Record<string,string>>({});
 async function submit(endpoint:string,operation:string,data:Row){setBusy(true);setError('');try{const res=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({operation,data})}),body=await res.json();if(!res.ok)throw new Error(body.error);router.refresh();}catch(e){setError(e instanceof Error?e.message:'Action failed.');}finally{setBusy(false);}}
 return <><div className="quick-actions">{sale.status==='Draft'&&<>{can('sales.edit')&&<Link className="button secondary" href={'/sales/'+sale.id+'/edit'}>Edit Draft</Link>}{can('sales.post')&&can('inventory.issue')&&<button disabled={busy} onClick={()=>submit('/api/sales','post',{id:sale.id,version:sale.version,request_id:crypto.randomUUID()})}>Post Sale & Deduct Stock</button>}</>}{sale.status==='Posted'&&!['Cancelled / Reversed','Fully Returned'].includes(sale.activity)&&can('returns.create')&&<Link className="button secondary" href={'/returns/new?sale='+sale.id}>Create Return</Link>}{sale.status==='Posted'&&!['Cancelled / Reversed','Fully Returned'].includes(sale.activity)&&can('sales.cancel')&&can('returns.create')&&<Link className="button secondary" href={'/returns/new?sale='+sale.id+'&kind=Cancellation'}>Controlled Cancellation</Link>}</div>{error&&<div className="error" role="alert">{error}</div>}
 {sale.documents&&<section className="panel"><h2>Sales Invoice / Delivery Receipt</h2>{sale.documents.map((d:Row)=><div key={d.id} className="panel"><strong>{d.kind} {d.number||'—'}</strong> <span className="badge">{d.status}</span>{d.series_snapshot&&<small> · {d.series_snapshot.name}</small>}{(d.status==='Required / Pending'||(d.status==='Cancelled / Void'&&sale.documents.filter((other:Row)=>other.kind===d.kind).every((other:Row)=>other.status==='Cancelled / Void')))&&can(d.kind==='SI'?'sales.si.assign':'sales.dr.assign')&&<form className="toolbar" onSubmit={e=>{e.preventDefault();submit('/api/sales','document',{sale_id:sale.id,...(d.status==='Cancelled / Void'?{}:{document_id:d.id}),kind:d.kind,action:'assign',series_id:series[d.id]||options.find(o=>o.kind===(d.kind==='SI'?'si_series':'dr_series'))?.id,number:numbers[d.id]||''});}}><label>Series<select value={series[d.id]||options.find(o=>o.kind===(d.kind==='SI'?'si_series':'dr_series'))?.id||''} onChange={e=>setSeries({...series,[d.id]:e.target.value})}>{options.filter(o=>o.kind===(d.kind==='SI'?'si_series':'dr_series')).map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label><label>Physical {d.kind} #<input required value={numbers[d.id]||''} onChange={e=>setNumbers({...numbers,[d.id]:e.target.value})} maxLength={80}/></label><button disabled={busy}>Assign number</button></form>}{d.number&&d.status!=='Cancelled / Void'&&<div className="actions">{sale.status==='Posted'&&can(d.kind==='SI'?'sales.si.print':'sales.dr.print')&&<><Link className="button secondary" href={'/sales/documents/'+d.id}>View document preview</Link><button disabled={busy||d.status==='Printed'} onClick={()=>submit('/api/sales','document',{sale_id:sale.id,document_id:d.id,kind:d.kind,action:'printed'})}>Mark printed</button></>}{can('sales.documents.void')&&<details><summary>Void document</summary><label>Reason<input value={reason} onChange={e=>setReason(e.target.value)}/></label><button disabled={busy||reason.trim().length<3} onClick={()=>submit('/api/sales','document',{sale_id:sale.id,document_id:d.id,kind:d.kind,action:'void',reason})}>Void this number</button></details>}</div>}{d.status==='Not Required'&&can('sales.documents.require')&&<button disabled={busy} onClick={()=>submit('/api/sales','document',{sale_id:sale.id,kind:d.kind,action:'require'})}>Require {d.kind}</button>}{d.status==='Cancelled / Void'&&<p>{d.reason} · Number remains reserved.</p>}</div>)}</section>}
 {sale.status==='Draft'&&can('sales.cancel')&&<details className="panel"><summary>Cancel Draft</summary><label>Cancellation reason<input value={reason} onChange={e=>setReason(e.target.value)}/></label><p>History is retained. No inventory will be deducted.</p><button disabled={busy||reason.trim().length<3} onClick={()=>submit('/api/returns','cancel-draft',{id:sale.id,version:sale.version,request_id:crypto.randomUUID(),reason})}>Cancel Draft</button></details>}</>;
}
