'use client';
import VatReferenceSelector from './vat-reference-selector';
import PriceListControl from './price-list-control';
import {priceListRows,productForPriceList} from '@/lib/quotation-form';
import type {PriceList} from '@/lib/operational-pricing';
import {useState} from 'react';
import {useRouter} from 'next/navigation';
import Link from 'next/link';
import {useSubmission} from './use-submission';
import SalesSearch from './sales-search';
import {calculateSaleLine,saleTotals,paymentTerms} from '@/lib/sales-calculations';
import {Money,type TaxConfig,type EntryMode,type TaxTreatment} from '@/lib/vat';
import type {Permission} from '@/lib/permissions';
import type {Row} from '@/lib/sales-common';
const money=(v:unknown)=>'₱'+Number(v||0).toLocaleString('en-PH',{minimumFractionDigits:2,maximumFractionDigits:2});
export default function SaleEntry({initial,options,config,permissions}:{initial?:Row;options:Row[];config:TaxConfig;permissions:Permission[]}){
 const [vatReference,setVatReference]=useState(initial?.vat_reference_mode||'Excluded');
 const [priceList,setPriceList]=useState<PriceList>(initial?.price_list||'Retail'),[documentFlow,setDocumentFlow]=useState(initial?.document_flow||'SI');
 const submission=useSubmission();
 const router=useRouter(),can=(p:Permission)=>permissions.includes(p);
 const [channel,setChannel]=useState(initial?.channel||'Wholesale'),[customer,setCustomer]=useState<Row|null>(initial?.customer_id?initial.customer_snapshot:null),[platform,setPlatform]=useState(initial?.platform_snapshot?.id||''),[onlineReference,setOnlineReference]=useState(initial?.online_reference||''),[reference,setReference]=useState(initial?.reference||''),[terms,setTerms]=useState(initial?.terms||'Cash'),[customTerms,setCustomTerms]=useState(initial?.custom_terms||''),[customDate,setCustomDate]=useState(initial?.due_date?new Date(initial.due_date).toISOString().slice(0,10):''),[agent,setAgent]=useState<Row|null>(initial?.salesperson_snapshot||null),[notes,setNotes]=useState(initial?.notes||'');
 const [date,setDate]=useState(initial?new Date(new Date(initial.occurred_at).getTime()+8*3600000).toISOString().slice(0,16):new Date(Date.now()+8*3600000).toISOString().slice(0,16));
 const [lines,setLines]=useState<Row[]>((initial?.lines||[]).map((l:Row)=>({...l,price:l.entered_price,discount:l.discount_percent||'0',unit_defaults:l.unit_defaults||[{uom:l.uom,price:l.entered_price,vat_mode:l.vat_mode,tax_treatment:l.tax_treatment}]})));
 const [payment,setPayment]=useState<Row>(initial?.payment_intent||{method_id:options.find(o=>o.code==='unpaid'&&o.kind==='payment_method')?.id||'',amount_received:'0',account_id:'',reference:'',check_bank:'',check_number:'',check_date:''});
 const [si,setSI]=useState(Boolean(initial?.documents?.some((d:Row)=>d.kind==='SI'&&!['Not Required','Cancelled / Void'].includes(d.status)))),[dr,setDR]=useState(Boolean(initial?.documents?.some((d:Row)=>d.kind==='DR'&&!['Not Required','Cancelled / Void'].includes(d.status))));
 const [error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 let totals:ReturnType<typeof saleTotals>|null=null;try{totals=saleTotals(lines.map(l=>calculateSaleLine(l.price,l.quantity,l.discount,l.vat_mode,l.tax_treatment,config)));}catch{}
 const patch=(id:string,value:Row)=>setLines(old=>old.map(l=>l.id===id?{...l,...value}:l));
 function add(product:Row){product=productForPriceList(product,priceList);if(lines.some(l=>l.product_id===product.id))setNotice('This product is already in the Sale. Separate lines are retained; check quantities and prices before posting.');const defaults=product.unit_defaults[0];setLines(old=>[...old,{id:crypto.randomUUID(),product_id:product.id,product_name:product.name,sku:product.sku,available:product.available,stock_uom:product.secondary_uom||product.primary_uom,unit_defaults:product.unit_defaults,quantity:'1',discount:'0',...defaults,vat_mode:defaults.vat_mode||''}]);}
 const method=options.find(o=>o.id===payment.method_id);
 async function submit(e:React.FormEvent){e.preventDefault();setError('');if(!totals||!lines.length){setError('Add products and check quantities, prices.');return;}setBusy(true);try{
  const amount=new Money(payment.amount_received||'0'),status=amount.isZero()?'Unpaid':amount.eq(totals.gross_total)?'Paid':'Partially Paid';
  const data={request_id:crypto.randomUUID(),...(initial?{id:initial.id,version:initial.version}:{}),vat_reference_mode:vatReference,price_list:priceList,document_flow:documentFlow,channel,customer_id:customer?.id||'',platform_id:channel==='Online'?platform:'',online_reference:channel==='Online'?onlineReference:'',occurred_at:new Date(date+':00+08:00').toISOString(),reference,terms,custom_terms:customTerms,custom_due_date:customDate,salesperson_id:agent?.id||'',notes,tax_config_version:config.version,lines:lines.map(l=>({id:l.id,product_id:l.product_id,quantity:l.quantity,uom:l.uom,price:l.price,vat_mode:l.vat_mode,tax_treatment:l.tax_treatment,discount:l.discount})),...(can('sales.payment.edit')?{payment:{method_id:payment.method_id,amount_received:payment.amount_received||'0',account_id:payment.account_id||'',reference:payment.reference||'',check_bank:payment.check_bank||'',check_number:payment.check_number||'',check_date:payment.check_date?String(payment.check_date).slice(0,10):'',status}}:{}),...(can('sales.documents.require')?{documents:{si,dr}}:{})};
  data.request_id=submission({...data,request_id:undefined});
  const res=await fetch('/api/sales',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({operation:'save',data})}),body=await res.json();if(!res.ok)throw new Error(body.error);router.push('/sales/'+body.id);router.refresh();
 }catch(e){setError(e instanceof Error?e.message:'Unable to save.');}finally{setBusy(false);}}
 return <form className="sale-entry" onSubmit={submit}><fieldset disabled={busy} style={{border:0,padding:0,minWidth:0}}><section className="panel form-grid no-print"><VatReferenceSelector value={vatReference} onChange={setVatReference}/><PriceListControl value={priceList} hasItems={lines.length>0} onChange={(list,update)=>{setPriceList(list);if(update)setLines(old=>priceListRows(old,list));}}/></section><section className="panel form-grid"><label>Sales Channel<select value={channel} onChange={e=>setChannel(e.target.value)}>{['Wholesale','Retail','Online'].map(c=><option key={c}>{c}</option>)}</select></label><label>Sale date / time (Philippines)<input type="datetime-local" required value={date} onChange={e=>setDate(e.target.value)}/></label><div><SalesSearch kind="customers" label="Customer" onSelect={r=>{setCustomer(r);if(!lines.length&&r.default_price_list)setPriceList(r.default_price_list);if(r.payment_terms&&paymentTerms.includes(r.payment_terms))setTerms(r.payment_terms);}}/><p>{customer?<><strong>{customer.name}</strong> · {customer.code} <button type="button" className="button secondary" onClick={()=>setCustomer(null)}>Clear</button></>:channel==='Wholesale'?'Select an existing customer.':'Walk-in'}</p>{can('customers.create')&&<Link href="/masters/customers/new" target="_blank">+ Create customer</Link>}</div><label>Reference<input value={reference} onChange={e=>setReference(e.target.value)} maxLength={1000}/></label>{channel==='Online'&&<><label>Platform<select required value={platform} onChange={e=>setPlatform(e.target.value)}><option value="">Select platform</option>{options.filter(o=>o.kind==='platform').map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label><label>Platform Order #<input value={onlineReference} onChange={e=>setOnlineReference(e.target.value)}/></label></>}</section>
 <section className="panel"><h2>Products</h2><SalesSearch kind="products" label="Add product" onSelect={add}/>{notice&&<p className="notice" role="status">{notice}</p>}<div className="table-wrap sales-grid"><table><thead><tr><th>Product</th><th>Quantity</th><th>UOM</th><th>Entered price</th>{can('sales.discounts')&&<th>Discount %</th>}<th>Customer payable</th><th/></tr></thead><tbody>{lines.map(l=>{let calc;try{calc=calculateSaleLine(l.price,l.quantity,l.discount,l.vat_mode as EntryMode,l.tax_treatment as TaxTreatment,config);}catch{}return <tr key={l.id}><td><strong>{l.product_name}</strong><br/><small>{l.sku}{l.available!==undefined?' · Available '+l.available+' '+l.stock_uom:''}</small></td><td><input aria-label={'Quantity '+l.product_name} type="number" min={l.uom==='METER'?'0.000001':'1'} step={l.uom==='METER'?'0.000001':'1'} value={l.quantity} onChange={e=>patch(l.id,{quantity:e.target.value})} required/></td><td><select aria-label={'Unit '+l.product_name} value={l.uom} onChange={e=>{const base=l.unit_defaults.find((d:Row)=>d.uom===e.target.value);const def={...base,price:base?.prices?.[priceList]??base?.price};patch(l.id,{...def,vat_mode:def.vat_mode||''});}}>{l.unit_defaults.map((d:Row)=><option key={d.uom}>{d.uom}</option>)}</select></td><td><input aria-label={'Price '+l.product_name} type="number" min="0" step="0.000001" value={l.price} readOnly={!can('sales.override')} onChange={e=>patch(l.id,{price:e.target.value})} required/></td>{can('sales.discounts')&&<td><input aria-label={'Discount '+l.product_name} type="number" min="0" max="100" step="0.000001" value={l.discount} readOnly={!can('sales.discount.apply')} onChange={e=>patch(l.id,{discount:e.target.value})}/></td>}<td>{calc?money(calc.gross_amount):'—'}</td><td><button type="button" className="button secondary" aria-label={'Remove '+l.product_name} onClick={()=>setLines(old=>old.filter(row=>row.id!==l.id))}>Remove</button></td></tr>;})}</tbody></table>{!lines.length&&<p className="empty">Search above to add the first product.</p>}</div><p><strong>{lines.length} product lines · Customer payable {totals?money(totals.gross_total):'—'}</strong></p></section>
 <section className="panel form-grid"><label>Payment terms<select value={terms} onChange={e=>setTerms(e.target.value)}>{paymentTerms.map(t=><option key={t}>{t}</option>)}</select></label>{terms==='Custom'&&<><label>Custom terms<input required value={customTerms} onChange={e=>setCustomTerms(e.target.value)}/></label><label>Due date<input required type="date" value={customDate} onChange={e=>setCustomDate(e.target.value)}/></label></>}{can('sales.payment.edit')&&<><label>Mode of payment<select required value={payment.method_id} onChange={e=>setPayment({method_id:e.target.value,amount_received:'0',account_id:'',reference:'',check_bank:'',check_number:'',check_date:''})}>{options.filter(o=>o.kind==='payment_method').map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label><label>Amount actually received<input type="number" min="0" step="0.01" value={payment.amount_received} onChange={e=>setPayment({...payment,amount_received:e.target.value})}/></label>{method?.behavior==='Bank'&&<label>Receiving account label<select value={payment.account_id} onChange={e=>setPayment({...payment,account_id:e.target.value})}><option value="">Not specified</option>{options.filter(o=>o.kind==='bank').map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label>}{['Wallet','Bank','Platform','Other','Card'].includes(method?.behavior)&&<label>Payment reference (optional)<input value={payment.reference} onChange={e=>setPayment({...payment,reference:e.target.value})}/></label>}{method?.behavior==='Check'&&['check_bank','check_number','check_date'].map(field=><label key={field}>{field.replace('check_','Check ')}<input required type={field==='check_date'?'date':'text'} value={payment[field]} onChange={e=>setPayment({...payment,[field]:e.target.value})}/></label>)}</>}{can('sales.documents.require')&&<div><label className="check"><input type="checkbox" checked={si} onChange={e=>setSI(e.target.checked)}/>Sales Invoice required</label><br/><label className="check"><input type="checkbox" checked={dr} onChange={e=>setDR(e.target.checked)}/>Delivery Receipt required</label><small>Physical numbers can be assigned on the review screen.</small></div>}<div><SalesSearch kind="agents" label="Salesperson / Agent (optional)" onSelect={setAgent}/>{agent&&<p>{agent.name} <button type="button" className="button secondary" onClick={()=>setAgent(null)}>Clear</button></p>}</div><label>Notes<textarea value={notes} onChange={e=>setNotes(e.target.value)} maxLength={1000}/></label></section>
 {error&&<div role="alert" className="error">{error}</div>}<div className="actions"><button type="submit">{busy?'Saving…':'Save Draft & Review'}</button><Link className="button secondary" href="/sales">Back to Sales</Link></div></fieldset></form>;
}
