import {transaction} from './db';
import {freshActor} from './masters';
import {allows,type Actor,type Permission} from './permissions';
import {need,type Row} from './sales-common';
import {documentModule,documentKinds} from './commercial';
import {Money} from './vat';
export function canViewDocument(actor:Actor,kind:string){return allows(actor,`${documentModule(kind)}.read` as Permission);}
function redact(actor:Actor,r:Row):Row{if(allows(actor,'commercial.prices')){if(!allows(actor,'sales.discounts')){r={...r};delete r.discount_total;if(r.lines)r.lines=r.lines.map((l:Row)=>{const clean={...l};for(const k of ['discount_percent','discount_rules','discount_amount','vat_snapshot'])delete clean[k];return clean;});}return r;}const hidden=['fees','subtotal','discount_total','entered_total','net_total','vat_total','gross_total','tax_config','payment_method_id','terms','custom_terms','due_date'];const result=Object.fromEntries(Object.entries(r).filter(([k])=>!hidden.includes(k)));if(r.lines)result.lines=r.lines.map((l:Row)=>Object.fromEntries(Object.entries(l).filter(([k])=>!['entered_price','discount_percent','discount_rules','vat_snapshot','subtotal','discount_amount','entered_amount','net_amount','vat_amount','gross_amount'].includes(k))));return result;}
export async function listCommercial(actor:Actor,filter:Record<string,string>={}){return transaction(async db=>{actor=await freshActor(db,actor.id);need(actor,'commercial.read');if(!(await db.query("SELECT to_regclass('imperial.commercial_documents') AS t")).rows[0].t)return [];const kinds=documentKinds.filter(k=>(!filter.kind||filter.kind===k)&&canViewDocument(actor,k));const rows=(await db.query<Row>(`SELECT d.*, (SELECT jsonb_agg(p) FROM (SELECT product_name,quantity,uom FROM commercial_lines WHERE document_id=d.id AND active ORDER BY position LIMIT 3) p) AS products,(SELECT count(*)::int FROM commercial_lines WHERE document_id=d.id AND active) AS line_count FROM commercial_documents d WHERE kind=ANY($1::text[]) AND ($2 OR customer_id IS NULL) AND (number ILIKE $3 OR physical_number ILIKE $3 OR customer_snapshot->>'name' ILIKE $3 OR salesperson_snapshot->>'name' ILIKE $3) AND ($4='' OR status=$4) AND ($5='' OR (occurred_at AT TIME ZONE 'Asia/Manila')::date>=NULLIF($5,'')::date) AND ($6='' OR (occurred_at AT TIME ZONE 'Asia/Manila')::date<=NULLIF($6,'')::date) ORDER BY occurred_at DESC,created_at DESC LIMIT 51 OFFSET $7`,[kinds,allows(actor,'customers.read'),'%'+(filter.q||'').slice(0,100)+'%',filter.status||'',filter.from||'',filter.to||'',(Math.max(1,Math.min(Number(filter.page)||1,10000))-1)*50])).rows;const orders=rows.filter(r=>r.kind==='SO'&&r.status==='Confirmed');if(orders.length){const progress=(await db.query<Row>("SELECT l.document_id,bool_and(l.quantity=COALESCE(p.delivered,0)) delivered,bool_or(COALESCE(p.delivered,0)>0) some_delivered,bool_and(l.quantity=COALESCE(p.invoiced,0)) invoiced,bool_or(COALESCE(p.invoiced,0)>0) some_invoiced FROM commercial_lines l LEFT JOIN (SELECT c.source_line_id,sum(c.quantity) FILTER(WHERE d.kind IN ('DR','RELEASE')) delivered,sum(c.quantity) FILTER(WHERE d.kind='SI') invoiced FROM commercial_lines c JOIN commercial_documents d ON d.id=c.document_id WHERE d.status='Finalized' AND c.active GROUP BY c.source_line_id) p ON p.source_line_id=l.id WHERE l.document_id=ANY($1::uuid[]) AND l.active GROUP BY l.document_id",[orders.map(r=>r.id)])).rows;for(const r of orders){const p=progress.find(p=>p.document_id===r.id);if(p)r.display_status=[p.delivered?'Delivered':p.some_delivered?'Partially Delivered':'Confirmed',p.invoiced?'Invoiced':p.some_invoiced?'Partially Invoiced':'Not Invoiced'].join(' · ');}}return rows.map(r=>redact(actor,r));});}
export async function getCommercial(actor:Actor,id:string){return transaction(async db=>{actor=await freshActor(db,actor.id);const doc=(await db.query<Row>('SELECT * FROM commercial_documents WHERE id=$1',[id])).rows[0];if(!doc)throw new Error('Document not found.');if(!canViewDocument(actor,doc.kind))throw new Error('You do not have permission for this document.');if(doc.customer_id)need(actor,'customers.read');
 doc.lines=(await db.query<Row>('SELECT * FROM commercial_lines WHERE document_id=$1 AND active ORDER BY position,id',[id])).rows;
 const order=doc.kind==='SO'?doc.id:['DR','SI','RELEASE'].includes(doc.kind)?doc.source_id:null;
 if(order){const orderLines=(await db.query<Row>(`SELECT l.id,l.quantity,COALESCE(sum(c.quantity) FILTER(WHERE d.kind IN ('DR','RELEASE') AND d.status='Finalized'),0)::text AS delivered,COALESCE(sum(c.quantity) FILTER(WHERE d.kind='SI' AND d.status='Finalized'),0)::text AS invoiced FROM commercial_lines l LEFT JOIN commercial_lines c ON c.source_line_id=l.id AND c.active LEFT JOIN commercial_documents d ON d.id=c.document_id WHERE l.document_id=$1 AND l.active GROUP BY l.id`,[order])).rows;for(const l of doc.lines){const progress=orderLines.find(o=>o.id===(doc.kind==='SO'?l.id:l.source_line_id));if(progress){l.ordered=progress.quantity;l.delivered=progress.delivered;l.invoiced=progress.invoiced;l.remaining_delivery=new Money(progress.quantity).minus(progress.delivered).toFixed(6);l.remaining_invoice=new Money(progress.quantity).minus(progress.invoiced).toFixed(6);}}
 if(doc.kind==='SO'&&doc.status==='Confirmed'){const full=(key:string)=>orderLines.every(l=>new Money(l[key]).eq(l.quantity)),any=(key:string)=>orderLines.some(l=>new Money(l[key]).gt(0));doc.delivery_status=full('delivered')?'Delivered':any('delivered')?'Partially Delivered':'Not Delivered';doc.invoice_status=full('invoiced')?'Invoiced':any('invoiced')?'Partially Invoiced':'Not Invoiced';}}
 if(order){
 const allocations=(await db.query<Row>("SELECT d.id,d.kind,d.number,d.sale_id,l.source_line_id,l.product_name,l.quantity,l.uom,l.vat_snapshot FROM commercial_documents d JOIN commercial_lines l ON l.document_id=d.id WHERE d.source_id=$1 AND d.status='Finalized' AND l.active",[order])).rows;
 doc.fulfilment_links=[];for(const invoice of allocations.filter(a=>a.kind==='SI'))for(const release of allocations.filter(a=>['DR','RELEASE'].includes(a.kind)&&a.source_line_id===invoice.source_line_id)){
 if(!canViewDocument(actor,'SI')||!canViewDocument(actor,release.kind))continue;
 const a=new Money(invoice.vat_snapshot.allocation.prior_quantity),b=new Money(release.vat_snapshot.allocation.prior_quantity),end=Money.min(a.plus(invoice.quantity),b.plus(release.quantity)),start=Money.max(a,b);if(end.gt(start))doc.fulfilment_links.push({invoice_id:invoice.id,invoice_number:invoice.number,release_id:release.id,release_number:release.number,sale_id:allows(actor,'sales.read')?release.sale_id:null,product_name:release.product_name,quantity:end.minus(start).toFixed(6),uom:release.uom});
 }}
 const related=(await db.query<Row>(`WITH RECURSIVE ancestors AS (SELECT id,source_id FROM commercial_documents WHERE id=$1 UNION ALL SELECT d.id,d.source_id FROM commercial_documents d JOIN ancestors a ON d.id=a.source_id), family AS (SELECT d.* FROM commercial_documents d WHERE d.id=(SELECT id FROM ancestors WHERE source_id IS NULL LIMIT 1) UNION ALL SELECT d.* FROM commercial_documents d JOIN family f ON d.source_id=f.id) SELECT id,kind,number,physical_number,status,sale_id FROM family ORDER BY created_at`,[id])).rows;
 doc.related=related.filter(r=>canViewDocument(actor,r.kind)).map(r=>({...r,sale_id:allows(actor,'sales.read')?r.sale_id:null}));if(!allows(actor,'sales.read'))delete doc.sale_id;
 return redact(actor,doc);
 });}

export async function commercialSaleLinks(actor:Actor,sale:string){return transaction(async db=>{actor=await freshActor(db,actor.id);if(!allows(actor,'commercial.read'))return [];const ready=(await db.query("SELECT to_regclass('imperial.commercial_documents') AS t")).rows[0].t;if(!ready)return [];return (await db.query<Row>('SELECT id,kind,number FROM commercial_documents WHERE sale_id=$1',[sale])).rows.filter(r=>canViewDocument(actor,r.kind));});}
export async function commercialOptions(actor:Actor){return transaction(async db=>{actor=await freshActor(db,actor.id);need(actor,'commercial.read');return (await db.query<Row>('SELECT id,kind,code,name,behavior,version FROM sales_options WHERE active ORDER BY kind,name')).rows.filter(r=>r.kind==='platform'||(r.kind==='dr_series'?allows(actor,'deliveries.assign'):r.kind==='si_series'?allows(actor,'invoices.assign'):allows(actor,'commercial.prices')));});}

export async function commercialReady(){return transaction(async db=>Boolean((await db.query("SELECT to_regclass('imperial.commercial_documents') AS t")).rows[0].t));}
