import {familyOptions} from './quotation-families';
import {quotationPrice,canonicalQuotationUom,type QuotationPriceList} from './quotation-pricing';
import {recordVatReference,referenceDate} from './vat-reference';
import {operationalConfig} from './operational-pricing';
import {savedDiscount,normalizeDiscount,feeSchema,quotationLine,calculateFees,documentTotals,allocateFees,allocatedDocumentTotals} from './quotation-calculations';
import {defaultQuotationText} from './quotation-defaults';
import {saleLineSchema} from './sales-schema';
import {createARForSource} from './finance';
import {randomUUID} from 'node:crypto';
import {z} from 'zod';
import {transaction,type DB} from './db';
import {freshActor} from './masters';
import {allows,type Actor,type Permission} from './permissions';
import {need,stamp,digest,decimal,option,type Row} from './sales-common';
import {saleDraftSchema} from './sales-schema';
import {saleProductDefaults,postSaleInTransaction} from './sales';
import {calculateSaleLine,saleTotals,dueDate} from './sales-calculations';
import {Money} from './vat';
export const documentKinds=['Q','SO','DR','SI','RELEASE'] as const;
export type DocumentKind=typeof documentKinds[number];
export const documentModule=(kind:string)=>({Q:'quotations',SO:'orders',DR:'deliveries',RELEASE:'deliveries',SI:'invoices'}[kind]!);
const permit=(actor:Actor,kind:string,action:string)=>need(actor,`${documentModule(kind)}.${action}` as Permission);
const totalsKeys=['subtotal','discount_total','entered_total','net_total','vat_total','gross_total'];
const amountKeys=['subtotal','discount_amount','entered_amount','net_amount','vat_amount','gross_amount'];
const lineKeys=['position','product_id','product_name','sku','brand','category','quantity','uom','stock_quantity','stock_uom','conversion','entered_price','vat_mode','tax_treatment','discount_percent','discount_rules','vat_snapshot',...amountKeys];
const headerKeys=['vat_reference_mode','price_list','document_flow','occurred_at','customer_id','customer_snapshot','salesperson_id','salesperson_snapshot','channel','platform_id','platform_snapshot','terms','custom_terms','due_date','company','validity','notes','tax_config','payment_method_id','si_required','dr_required','fees','quotation_snapshot',...totalsKeys];
const pick=(r:Row,keys:string[])=>Object.fromEntries(keys.map(k=>[k,r[k]??null]));
async function insert(db:DB,table:string,row:Row){const keys=Object.keys(row);return (await db.query<Row>(`INSERT INTO ${table}(${keys.join(',')}) VALUES(${keys.map((_,i)=>'$'+(i+1)).join(',')}) RETURNING *`,keys.map(k=>typeof row[k]==='object'&&row[k]!==null?JSON.stringify(row[k]):row[k]))).rows[0];}
async function update(db:DB,table:string,id:string,row:Row){const keys=Object.keys(row);await db.query(`UPDATE ${table} SET ${keys.map((k,i)=>k+'=$'+(i+1)).join(',')} WHERE id=$${keys.length+1}`,[...keys.map(k=>typeof row[k]==='object'&&row[k]!==null?JSON.stringify(row[k]):row[k]),id]);}
async function number(db:DB,kind:string){return String((await db.query("SELECT business_document_number($1,nextval('commercial_number_seq')) AS n",[kind==='RELEASE'?'REL-':kind+'-'])).rows[0].n);}
async function lines(db:DB,id:string){return (await db.query<Row>('SELECT * FROM commercial_lines WHERE document_id=$1 AND active ORDER BY position,id',[id])).rows;}
async function locked(db:DB,id:string){const r=(await db.query<Row>('SELECT * FROM commercial_documents WHERE id=$1 FOR UPDATE',[id])).rows[0];if(!r)throw new Error('Document not found.');return r;}
async function request(db:DB,actor:Actor,id:string,op:string,data:unknown){await db.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[id]);const r=(await db.query<Row>('SELECT * FROM commercial_requests WHERE request_id=$1',[id])).rows[0];if(r){if(r.actor_id!==actor.id||r.operation!==op||r.payload_hash!==digest(data))throw new Error('Submission already used for different details.');return String(r.document_id);}}
async function remember(db:DB,actor:Actor,id:string,op:string,data:unknown,document:string){await insert(db,'commercial_requests',{request_id:id,actor_id:actor.id,operation:op,payload_hash:digest(data),document_id:document});return document;}
function version(r:Row,v:number){if(r.version!==v)throw new Error('Document changed. Reload and review before continuing.');}
function visible(actor:Actor,r:Row){permit(actor,r.kind,'read');if(r.customer_id)need(actor,'customers.read');}
export const commercialDraftSchema=saleDraftSchema.omit({payment:true,documents:true,reference:true}).extend({quotation_price_list:z.enum(['None','Retail','Contractor']).optional(),kind:z.enum(['Q','SO']),lines:z.array(saleLineSchema.extend({family_id:z.uuid().optional(),manual_price_override:z.boolean().optional(),discount:z.string().max(150).default('0'),adjustment_version:z.literal(2).optional()})).min(1),fees:z.array(feeSchema).max(30).optional(),customer_override:z.object({quotation_contact:z.string().max(1000).optional(),billing_address:z.string().max(1000),contact_person:z.string().max(200),phone:z.string().max(80),email:z.string().max(200)}).strict().optional(),disclaimer:z.string().trim().max(1500).optional(),company:z.string().trim().min(1).max(250).default('Imperial Electrical and Industrial Supply Corporation'),validity:z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional(),payment_method_id:z.union([z.uuid(),z.literal('')]).default(''),si_required:z.boolean().default(false),dr_required:z.boolean().default(false)}).strict();
export async function saveCommercial(actor:Actor,input:unknown){if(input&&typeof input==='object'&&(input as Row).kind==='Q'&&Array.isArray((input as Row).lines))input={...(input as Row),lines:(input as Row).lines.map((l:Row)=>({...l,uom:typeof l.uom==='string'?canonicalQuotationUom(l.uom):l.uom}))};const d=commercialDraftSchema.parse(input);if(d.kind!=='Q'&&(d.quotation_price_list!==undefined||d.lines.some(l=>l.manual_price_override!==undefined||l.family_id!==undefined)))throw new Error('Quotation pricing controls apply only to quotations.');if(d.validity&&(Number.isNaN(Date.parse(d.validity))||new Date(d.validity).toISOString().slice(0,10)!==d.validity))throw new Error('Select a valid expiry date.');return transaction(async db=>{
 actor=await freshActor(db,actor.id);permit(actor,d.kind,d.id?'edit':'create');need(actor,'commercial.prices');need(actor,'products.read');
 const replay=await request(db,actor,d.request_id,'save',d);if(replay)return replay;
 const old=d.id?await locked(db,d.id):null;if(old){visible(actor,old);version(old,d.version!);if(old.kind!==d.kind||old.status!=='Draft'||old.source_id)throw new Error('Only independent Draft quotations/orders can be edited.');}
 const quotationList:QuotationPriceList=d.quotation_price_list||old?.quotation_snapshot?.price_list||d.price_list;
 if(new Set(d.lines.map(l=>l.id)).size!==d.lines.length)throw new Error('Duplicate line identifier.');
 let customer:Row={name:'Walk-in',billing_address:''};if(d.customer_id){need(actor,'customers.read');customer=(await db.query<Row>('SELECT id,name,code,billing_address,contact_person,phone,email,tin FROM customers WHERE id=$1 AND active FOR SHARE',[d.customer_id])).rows[0];if(!customer)throw new Error('Choose an active customer.');}else if(d.channel==='Wholesale')throw new Error('Wholesale requires a customer.');
 let agent:Row|null=null;if(d.salesperson_id){agent=(await db.query<Row>('SELECT id,name FROM users WHERE id=$1 AND active FOR SHARE',[d.salesperson_id])).rows[0];if(!agent)throw new Error('Choose an active salesperson.');}
 if(old?.customer_id===d.customer_id)customer=old.customer_snapshot;
 if(d.customer_override){if(d.kind!=='Q')throw new Error('Contact overrides apply to quotations.');customer={...customer,...d.customer_override};}
 if(old&&old.salesperson_id===agent?.id)agent=old.salesperson_snapshot;
 if(!old&&!agent&&d.kind==='Q')agent={id:actor.id,name:actor.name};
 const platform=d.channel==='Online'?await option(db,d.platform_id,'platform'):null;if(d.payment_method_id)await option(db,d.payment_method_id,'payment_method');
 const config=operationalConfig;
 const products=(await db.query<Row>('SELECT * FROM products WHERE id=ANY($1::uuid[]) ORDER BY id FOR SHARE',[[...new Set(d.lines.map(l=>l.product_id))]])).rows;
 const previous=old?await lines(db,old.id):[];const content:Row[]=[];
 for(const l of d.lines){const p=products.find(p=>p.id===l.product_id);if(!p||!p.active)throw new Error('Choose active products.');const q=new Money(l.quantity);if(q.lte(0)||(l.uom!=='METER'&&!q.isInteger()))throw new Error('Count units require positive whole quantities.');if(d.kind!=='Q'&&l.uom!==p.primary_uom&&l.uom!==p.secondary_uom)throw new Error('UOM not configured.');
 const prior=previous.find(p=>p.id===l.id&&p.product_id===l.product_id&&p.uom===l.uom);let familySnapshot=prior?.vat_snapshot?.quotation_family;if(l.family_id){if(!prior||familySnapshot?.id!==l.family_id){const family=await familyOptions(db,l.family_id);const route=family?.unit_defaults.find(u=>u.uom===l.uom);if(!family||!route||route.product_id!==l.product_id)throw new Error('Family UOM route changed or is unavailable. Select the product again.');familySnapshot={id:l.family_id,name:family.name,version:route.family_version,product_id:p.id,sku:p.sku,uom:l.uom};}}const defaults=d.kind==='Q'?{price:quotationPrice(p,l.uom,quotationList)}:saleProductDefaults(p,l.uom,d.price_list);
 if(!(prior&&new Money(prior.entered_price).eq(l.price))&&(!defaults.price||!new Money(defaults.price).eq(l.price)))need(actor,'sales.override');
 const expression=prior?savedDiscount(prior):'0%';
 const entered=normalizeDiscount(l.adjustment_version===2?l.discount:l.discount.startsWith('-')?l.discount:'-'+l.discount);
 if(entered!==expression)need(actor,'sales.discount.apply');
 if(prior&&!allows(actor,'sales.discounts')&&!new Money(prior.discount_amount).isZero())throw new Error('You do not have permission to edit protected discounts.');
 const factor=new Money(p.conversion||1),stock=q.mul(l.uom===p.primary_uom?factor:1);if(stock.decimalPlaces()>6||stock.gte('1e24')||((p.secondary_uom||p.primary_uom)!=='METER'&&!stock.isInteger()))throw new Error('Converted quantity is invalid.');
 content.push({id:l.id,position:content.length+1,product_id:p.id,product_name:prior?.product_name||p.name,sku:prior?.sku||p.sku,brand:p.brand,category:p.category,quantity:q.toFixed(6),uom:l.uom,stock_quantity:stock.toFixed(6),stock_uom:p.secondary_uom||p.primary_uom,conversion:factor.toFixed(6),...quotationLine(l.price,l.quantity,l.discount,l.vat_mode,l.tax_treatment,config,l.adjustment_version),vat_mode:l.vat_mode,tax_treatment:l.tax_treatment});if(d.kind==='Q'){const latest=content[content.length-1];if(familySnapshot)latest.vat_snapshot.quotation_family=familySnapshot;latest.vat_snapshot.quotation_pricing={price_list:quotationList,manual_override:l.manual_price_override===true||(l.manual_price_override===undefined&&prior?.vat_snapshot?.quotation_pricing?.manual_override===true)||!defaults.price||!new Money(defaults.price).eq(l.price)};}}
 const fees=d.fees===undefined?(old?.fees||[]):calculateFees(d.fees,config);
 if(fees.length!==(old?.fees||[]).length||fees.some((f:Row,i:number)=>{const prior=old?.fees?.[i];return !prior||f.id!==prior.id||f.description!==prior.description||!new Money(f.amount).eq(prior.amount)||f.vat_mode!==prior.vat_mode||f.tax_treatment!==prior.tax_treatment;}))need(actor,d.kind==='Q'?'quotations.fees':'sales.override');
 const defaults=(await db.query<Row>('SELECT notes,disclaimer FROM quotation_defaults WHERE singleton=true')).rows[0]||defaultQuotationText;
 const quotation_snapshot=old?.quotation_snapshot||{template_version:1,disclaimer:d.disclaimer??defaults.disclaimer};
 if(d.disclaimer!==undefined)quotation_snapshot.disclaimer=d.disclaimer;
 if(d.kind==='Q')quotation_snapshot.price_list=quotationList;
 const header={vat_reference_mode:d.vat_reference_mode,price_list:d.kind==='Q'?(quotationList==='None'?null:quotationList):d.price_list,document_flow:d.document_flow,fees,quotation_snapshot,kind:d.kind,occurred_at:d.occurred_at,customer_id:d.customer_id||null,customer_snapshot:customer,salesperson_id:agent?.id||null,salesperson_snapshot:agent,channel:d.channel,platform_id:platform?.id||null,platform_snapshot:platform,terms:d.terms,custom_terms:d.custom_terms,due_date:dueDate(d.occurred_at,d.terms,d.custom_due_date),company:d.company,validity:d.validity||old?.validity||null,notes:d.notes,tax_config:{standard_rate:config.standard_rate,version:config.version,effective_at:config.effective_at},payment_method_id:d.payment_method_id||null,si_required:d.si_required,dr_required:d.dr_required,...documentTotals(content,fees)};
 await stamp(db,actor);const id=old?.id||(await insert(db,'commercial_documents',{...header,number:await number(db,d.kind),created_by:actor.id})).id;
 if(old){await update(db,'commercial_documents',id,{...header,version:old.version+1,updated_at:new Date().toISOString()});await db.query('UPDATE commercial_lines SET active=false WHERE document_id=$1 AND active',[id]);}
 for(const l of content){const prior=(await db.query<Row>('SELECT document_id FROM commercial_lines WHERE id=$1',[l.id])).rows[0];if(prior&&prior.document_id!==id)throw new Error('Line belongs to another document.');if(prior)await update(db,'commercial_lines',l.id,{...l,active:true});else await insert(db,'commercial_lines',{...l,document_id:id});}
 return remember(db,actor,d.request_id,'save',d,id);
 });}
const actionSchema=z.object({id:z.uuid(),version:z.number().int().positive(),request_id:z.uuid(),action:z.enum(['submit','approve','send','accept','reject','expire','confirm','cancel','convert','finalize']),reason:z.string().trim().max(1000).default('')}).strict();
// Frozen monetary amounts are allocated cumulatively: the last partial conserves every centavo.
export function allocateLine(l:Row,q:string,prior='0'){const ratio=(value:string,quantity:string)=>new Money(value).mul(quantity).div(l.quantity).toDecimalPlaces(2);const end=new Money(prior).plus(q).toFixed(6);const r=pick(l,lineKeys);r.quantity=q;r.stock_quantity=new Money(l.stock_quantity).mul(q).div(l.quantity).toFixed(6);for(const k of amountKeys)r[k]=ratio(l[k],end).minus(ratio(l[k],prior)).toFixed(2);r.discount_amount=new Money(r.subtotal).minus(r.entered_amount).toFixed(2);r.vat_amount=new Money(r.gross_amount).minus(r.net_amount).toFixed(2);r.vat_snapshot={...l.vat_snapshot,...(l.vat_snapshot?.exact_amount?{exact_amount:r.gross_amount,exact_subtotal:r.subtotal}:{}),quantity:q,allocation:{source_line_id:l.id,source_quantity:l.quantity,prior_quantity:prior,method:'CUMULATIVE_SNAPSHOT_HALF_UP_2'},entered:r.entered_amount,net:r.net_amount,vat:r.vat_amount,gross:r.gross_amount};return r;}
async function used(db:DB,order:string,line:string,kind:'delivery'|'invoice'){return String((await db.query("SELECT COALESCE(sum(l.quantity),0)::text n FROM commercial_lines l JOIN commercial_documents d ON d.id=l.document_id WHERE d.source_id=$1 AND l.source_line_id=$2 AND d.status='Finalized' AND d.kind=ANY($3::text[]) AND l.active",[order,line,kind==='delivery'?['DR','RELEASE']:['SI']])).rows[0].n);}
const childSchema=z.object({id:z.uuid().optional(),version:z.number().int().positive().optional(),preparation_mode:z.enum(['Computer','Handwritten']).default('Computer'),order_id:z.uuid(),delivery_id:z.uuid().optional(),kind:z.enum(['DR','SI','RELEASE']),request_id:z.uuid(),occurred_at:z.iso.datetime({offset:true}),notes:z.string().trim().max(1000).default(''),lines:z.array(z.object({source_line_id:z.uuid(),quantity:decimal}).strict()).min(1)}).strict();
export async function createCommercialChild(actor:Actor,input:unknown){const d=childSchema.parse(input);return transaction(async db=>{
 actor=await freshActor(db,actor.id);permit(actor,d.kind,'create');const replay=await request(db,actor,d.request_id,'child',d);if(replay)return replay;const editing=d.id?await locked(db,d.id):null;if(editing){visible(actor,editing);version(editing,d.version!);if(editing.status!=='Draft'||editing.kind!==d.kind||editing.source_id!==d.order_id)throw new Error('Only the matching Draft can be edited.');}if(d.preparation_mode==='Handwritten'&&d.kind!=='SI')throw new Error('Handwritten mode applies to SI only.');const order=await locked(db,d.order_id);visible(actor,order);if(order.kind!=='SO'||order.status!=='Confirmed')throw new Error('Confirm the Sales Order first.');if(d.kind==='RELEASE'&&order.dr_required)throw new Error('This order requires a Delivery Receipt.');if(new Set(d.lines.map(l=>l.source_line_id)).size!==d.lines.length)throw new Error('Choose each order line once.');
 let delivery:Row|null=null;let delivered:Row[]=[];if(d.delivery_id){delivery=(await db.query<Row>('SELECT * FROM commercial_documents WHERE id=$1',[d.delivery_id])).rows[0];if(!delivery||d.kind!=='SI'||delivery.source_id!==order.id||!['DR','RELEASE'].includes(delivery.kind)||delivery.status!=='Finalized')throw new Error('Choose a finalized release from this order.');visible(actor,delivery);delivered=await lines(db,delivery.id);}
 const originals=await lines(db,order.id),selected:Row[]=[];for(const l of d.lines){const o=originals.find(o=>o.id===l.source_line_id);if(!o)throw new Error('Order line not found.');const q=new Money(l.quantity),prior=await used(db,order.id,o.id,d.kind==='SI'?'invoice':'delivery');if(q.lte(0)||(o.uom!=='METER'&&!q.isInteger())||q.plus(prior).gt(o.quantity))throw new Error('Quantity exceeds remaining order quantity.');if(delivery){const releaseLine=delivered.find(r=>r.source_line_id===o.id);if(!releaseLine)throw new Error('Product is not on this delivery.');const start=new Money(releaseLine.vat_snapshot.allocation.prior_quantity),end=start.plus(releaseLine.quantity);if(new Money(prior).lt(start))throw new Error('Invoice earlier order quantities first, or create an invoice from the order.');if(new Money(prior).plus(q).gt(end))throw new Error('This delivery’s quantities are already invoiced or exceed its uninvoiced quantity.');}selected.push({...allocateLine(o,q.toFixed(6),prior),source_line_id:o.id});}
 const feePrior:Record<string,string>={};for(const l of originals)feePrior[l.id]=await used(db,order.id,l.id,'invoice');
 const fees=d.kind==='SI'?allocateFees(order.fees||[],originals,feePrior,selected):[];
 const amountPrior:Record<string,string>={};for(const l of originals)amountPrior[l.id]=await used(db,order.id,l.id,d.kind==='SI'?'invoice':'delivery');
 await stamp(db,actor);const header={...pick(order,headerKeys),fees,occurred_at:d.occurred_at,notes:d.notes||order.notes,...allocatedDocumentTotals(originals,amountPrior,selected,fees)};let child:Row;if(editing){const prep=(await db.query<Row>('SELECT mode FROM commercial_preparation WHERE document_id=$1',[editing.id])).rows[0];if(prep&&prep.mode!==d.preparation_mode)throw new Error('Preparation mode is fixed after creation.');await update(db,'commercial_documents',editing.id,{...header,source_delivery_id:delivery?.id||null,version:editing.version+1,updated_at:new Date().toISOString()});await db.query('UPDATE commercial_lines SET active=false WHERE document_id=$1 AND active',[editing.id]);child=editing;}else{child=await insert(db,'commercial_documents',{...header,kind:d.kind,number:await number(db,d.kind),source_id:order.id,source_delivery_id:delivery?.id||null,created_by:actor.id});await insert(db,'commercial_preparation',{document_id:child.id,mode:d.preparation_mode,recorded_by:actor.id});}for(const l of selected)await insert(db,'commercial_lines',{...l,document_id:child.id});return remember(db,actor,d.request_id,'child',d,child.id);
 });}
export async function assignCommercialNumber(actor:Actor,input:unknown){const d=z.object({id:z.uuid(),version:z.number().int().positive(),request_id:z.uuid(),series_id:z.uuid(),number:z.string().trim().min(1).max(80)}).strict().parse(input);return transaction(async db=>{actor=await freshActor(db,actor.id);const replay=await request(db,actor,d.request_id,'number',d);const doc=await locked(db,d.id);visible(actor,doc);permit(actor,doc.kind,'assign');if(replay)return replay;version(doc,d.version);if(!['DR','SI'].includes(doc.kind)||doc.status!=='Draft'||doc.physical_number)throw new Error('Assign a number to an unnumbered Draft only. Cancel a spoiled Draft and create a replacement.');await option(db,d.series_id,doc.kind==='SI'?'si_series':'dr_series');await stamp(db,actor);await insert(db,'physical_document_registry',{series_id:d.series_id,normalized_number:d.number.toLowerCase(),commercial_id:doc.id});await update(db,'commercial_documents',doc.id,{series_id:d.series_id,physical_number:d.number,version:doc.version+1,updated_at:new Date().toISOString()});return remember(db,actor,d.request_id,'number',d,doc.id);});}
async function finalize(db:DB,actor:Actor,doc:Row){permit(actor,doc.kind,'finalize');if(!['DR','SI','RELEASE'].includes(doc.kind)||doc.status!=='Draft')throw new Error('Only a Draft delivery/invoice can be finalized.');if(doc.kind!=='RELEASE'&&!doc.physical_number)throw new Error('Assign the actual pre-printed physical number first.');const order=await locked(db,doc.source_id);visible(actor,order);if(order.status!=='Confirmed')throw new Error('Order is not confirmed.');const originals=await lines(db,order.id),content=await lines(db,doc.id);
 for(const l of content){const o=originals.find(o=>o.id===l.source_line_id);if(!o)throw new Error('Order line missing.');const prior=await used(db,order.id,o.id,doc.kind==='SI'?'invoice':'delivery');if(new Money(prior).plus(l.quantity).gt(o.quantity))throw new Error('Another employee already finalized these quantities; remaining quantity is insufficient.');if(doc.source_delivery_id){const released=(await db.query<Row>('SELECT quantity,vat_snapshot FROM commercial_lines WHERE document_id=$1 AND source_line_id=$2 AND active',[doc.source_delivery_id,o.id])).rows[0];if(!released)throw new Error('Delivery line missing.');const start=new Money(released.vat_snapshot.allocation.prior_quantity),end=start.plus(released.quantity);if(new Money(prior).lt(start)||new Money(prior).plus(l.quantity).gt(end))throw new Error('This delivery is already invoiced, or earlier order quantities must be invoiced first.');}const allocation=allocateLine(o,l.quantity,prior);await update(db,'commercial_lines',l.id,allocation);Object.assign(l,allocation);}
 const feePrior:Record<string,string>={};for(const l of originals)feePrior[l.id]=await used(db,order.id,l.id,'invoice');
 const fees=doc.kind==='SI'?allocateFees(order.fees||[],originals,feePrior,content):[];
 const amountPrior:Record<string,string>={};for(const l of originals)amountPrior[l.id]=await used(db,order.id,l.id,doc.kind==='SI'?'invoice':'delivery');
 const totals=allocatedDocumentTotals(originals,amountPrior,content,fees);await update(db,'commercial_documents',doc.id,{...totals,fees});
 if(doc.kind!=='SI'){
  need(actor,'sales.post');need(actor,'inventory.issue');const unpaid=await db.query<Row>("SELECT id,kind,code,name,behavior,version FROM sales_options WHERE kind='payment_method' AND code='unpaid' AND active");if(!unpaid.rows[0])throw new Error('Enable the unpaid payment method.');
  const h=pick(doc,['vat_reference_mode','price_list','document_flow','channel','customer_id','customer_snapshot','platform_id','platform_snapshot','terms','custom_terms','due_date','salesperson_id','salesperson_snapshot','tax_config']);const quantities:Row={};for(const l of content)quantities[l.uom]=new Money(quantities[l.uom]||0).plus(l.quantity).toFixed(6);
  const sale=await insert(db,'sales',{...h,...totals,occurred_at:doc.occurred_at,request_id:randomUUID(),creation_hash:digest({release:doc.id}),reference:doc.number,notes:'Goods release '+doc.number+' / '+order.number,line_count:content.length,quantities,payment_intent:{method_id:unpaid.rows[0].id,method_snapshot:unpaid.rows[0],amount_received:'0.00',status:'Unpaid'},payment_status:'Unpaid',created_by:actor.id,actor_name:actor.name});
  for(const l of content)await insert(db,'sale_lines',{...pick(l,lineKeys),sale_id:sale.id});
  await update(db,'commercial_documents',doc.id,{sale_id:sale.id});await postSaleInTransaction(actor,{id:sale.id,version:1,request_id:randomUUID()},db,true);
  const posted=(await db.query<Row>('SELECT l.position,m.stock_quantity,m.stock_uom FROM sale_lines l JOIN inventory_movements m ON m.id=l.movement_id WHERE l.sale_id=$1',[sale.id])).rows;
  for(const l of content){const m=posted.find(m=>m.position===l.position);if(!m||!new Money(m.stock_quantity).eq(l.stock_quantity)||m.stock_uom!==l.stock_uom)throw new Error('Product unit conversion changed since the order. Review the order before releasing goods.');}
 }
 await update(db,'commercial_documents',doc.id,{status:'Finalized',version:doc.version+1,finalized_by:actor.id,finalized_at:new Date().toISOString(),updated_at:new Date().toISOString()});
 if(doc.kind==='SI')await recordVatReference(db,actor,{direction:'Output',kind:'invoice',id:doc.id,number:doc.physical_number||doc.number,date:referenceDate(doc.occurred_at),amount:totals.gross_total,included:doc.vat_reference_mode==='Included'});
 if(doc.kind==='SI')await createARForSource(db,actor,'invoice',doc.id);
}
export async function actCommercial(actor:Actor,input:unknown){const d=actionSchema.parse(input);return transaction(async db=>{actor=await freshActor(db,actor.id);const replay=await request(db,actor,d.request_id,d.action,d);const doc=await locked(db,d.id);visible(actor,doc);if(replay)return replay;version(doc,d.version);await stamp(db,actor);
 if(d.action==='finalize')await finalize(db,actor,doc);
 else if(d.action==='convert'){
  permit(actor,'Q','convert');permit(actor,'SO','create');if(doc.kind!=='Q'||!['Approved','Accepted'].includes(doc.status))throw new Error('Approve or accept this quotation before conversion.');if(doc.validity&&new Date(doc.validity).toISOString().slice(0,10)<new Date().toISOString().slice(0,10))throw new Error('Quotation has expired.');
  const child=await insert(db,'commercial_documents',{...pick(doc,headerKeys),kind:'SO',number:await number(db,'SO'),source_id:doc.id,created_by:actor.id});for(const l of await lines(db,doc.id))await insert(db,'commercial_lines',{...pick(l,lineKeys),source_line_id:l.id,document_id:child.id});await update(db,'commercial_documents',doc.id,{status:'Converted',version:doc.version+1,updated_at:new Date().toISOString()});return remember(db,actor,d.request_id,d.action,d,child.id);
 }else{
  let status='';if(d.action==='cancel'){if(d.reason.length<3)throw new Error('Enter a cancellation reason.');if(doc.kind==='SO')permit(actor,'SO','cancel');else need(actor,'commercial.cancel');if(doc.status==='Finalized'||doc.status==='Converted'||doc.sale_id)throw new Error('Finalized documents cannot be voided here. Use the linked Sale Return workflow for released goods; invoice corrections require accounting review.');if((await db.query("SELECT id FROM commercial_documents WHERE source_id=$1 AND status<>'Cancelled'",[doc.id])).rows.length)throw new Error('Resolve related documents before cancelling.');status='Cancelled';}
  else if(d.action==='confirm'){permit(actor,'SO','confirm');if(doc.kind!=='SO'||doc.status!=='Draft')throw new Error('Only Draft orders can be confirmed.');status='Confirmed';}
  else{permit(actor,'Q',d.action==='approve'?'approve':'edit');if(doc.kind!=='Q')throw new Error('Quotation action required.');const transitions:Record<string,[string[],string]>={submit:[['Draft'],'For Approval'],approve:[['Draft','For Approval'],'Approved'],send:[['Approved'],'Sent'],accept:[['Sent','Approved'],'Accepted'],reject:[['For Approval','Sent','Approved'],'Rejected'],expire:[['Approved','Sent'],'Expired']};const rule=transitions[d.action];if(!rule||!rule[0].includes(doc.status))throw new Error('Invalid quotation status transition.');status=rule[1];}
  await update(db,'commercial_documents',doc.id,{status,reason:d.reason,version:doc.version+1,updated_at:new Date().toISOString()});
 }return remember(db,actor,d.request_id,d.action,d,doc.id);
 });}

export async function duplicateQuotation(actor:Actor,input:unknown){const d=z.object({id:z.uuid(),version:z.number().int().positive(),request_id:z.uuid()}).strict().parse(input);return transaction(async db=>{actor=await freshActor(db,actor.id);permit(actor,'Q','create');need(actor,'commercial.prices');need(actor,'sales.discounts');const replay=await request(db,actor,d.request_id,'duplicate',d);if(replay)return replay;const original=await locked(db,d.id);visible(actor,original);version(original,d.version);if(original.kind!=='Q')throw new Error('Choose a quotation.');await stamp(db,actor);const copy=await insert(db,'commercial_documents',{...pick(original,headerKeys),kind:'Q',number:await number(db,'Q'),copied_from_id:original.id,created_by:actor.id});for(const l of await lines(db,original.id))await insert(db,'commercial_lines',{...pick(l,lineKeys),document_id:copy.id});return remember(db,actor,d.request_id,'duplicate',d,copy.id);});}
