import {z} from 'zod';
import {transaction,type DB} from './db';
import {freshActor} from './masters';
import {allows,type Actor} from './permissions';
import {need,type Row} from './sales-common';
import {Money} from './vat';
import {position,businessDate,dateText,financeReady} from './finance';
export async function projectAR(db:DB,actor:Actor,ar:Row,asOf=businessDate()){
 const p=await position(db,ar,asOf);const row:Row={...ar,invoice_date:dateText(ar.invoice_date),due_date:dateText(ar.due_date),customer_name:ar.customer_snapshot.name||'Walk-in',collected:p.collected,balance:p.balance,payment_status:p.payment_status,adjustments:p.adjustments,refund_due:p.refund_due};
 if(p.payment_status==='Paid')need(actor,'ar.paid');
 if(allows(actor,'ar.overdue'))row.days_overdue=p.days_overdue;
 if(allows(actor,'ar.due')){const days=Math.floor((Date.parse(dateText(ar.due_date))-Date.parse(asOf))/86400000);row.due_indicator=p.payment_status==='Paid'?'Paid':days===0?'Due today':days>0?'Due in '+days+' days':allows(actor,'ar.overdue')?'Overdue — '+(-days)+' days':undefined;}
 if(allows(actor,'ar.aging'))row.aging_bucket=p.aging_bucket;
 if(allows(actor,'collections.checks'))row.pending_checks=p.pending_checks;
 if(allows(actor,'collections.read')){row.last_collection_date=p.last_collection_date;row.last_collection_amount=p.last_collection_amount;}
 return row;
}
async function allAR(db:DB,actor:Actor,filter:Row={},asOf=businessDate()){
 need(actor,'ar.read');if(!await financeReady(db))return [];
 if(filter.customer)z.uuid().parse(filter.customer);if(filter.agent)z.uuid().parse(filter.agent);
 if(filter.status==='Paid')need(actor,'ar.paid');if(filter.status==='Overdue')need(actor,'ar.overdue');if(filter.status==='Due Soon')need(actor,'ar.due');if(filter.bucket)need(actor,'ar.aging');
 const raw=(await db.query<Row>(`SELECT a.*,u.name AS salesperson_name FROM receivables a LEFT JOIN users u ON u.id=a.salesperson_id WHERE invoice_date<=$1 AND ($2='' OR a.customer_id=NULLIF($2,'')::uuid) AND ($3='' OR a.salesperson_id=NULLIF($3,'')::uuid) AND ($4='' OR a.channel=$4) ORDER BY a.invoice_date DESC,a.number DESC`,[asOf,filter.customer||'',filter.agent||'',filter.channel||''])).rows;
 const result:Row[]=[];const q=String(filter.q||'').toLowerCase().slice(0,160);
 for(const ar of raw){const p=await position(db,ar,asOf);if(p.payment_status==='Paid'&&!allows(actor,'ar.paid'))continue;if(q&&![ar.number,ar.source_number,ar.physical_number,ar.customer_snapshot.name,ar.salesperson_name].some(v=>String(v||'').toLowerCase().includes(q)))continue;
 if(filter.status&&(['Unpaid','Partially Paid','Paid'].includes(filter.status)?p.payment_status!==filter.status:filter.status==='Overdue'?p.days_overdue===0:filter.status==='Due Soon'?!(new Money(p.balance).gt(0)&&dateText(ar.due_date)>=asOf&&dateText(ar.due_date)<=new Date(Date.parse(asOf)+7*86400000).toISOString().slice(0,10)):false))continue;
 if(filter.bucket&&p.aging_bucket!==filter.bucket)continue;
 result.push(await projectAR(db,actor,ar,asOf));}return result;
}
export async function listAR(actor:Actor,filter:Row={}){return transaction(async db=>{actor=await freshActor(db,actor.id);const rows=await allAR(db,actor,filter);const page=Math.max(1,Math.min(100000,Number(filter.page)||1));return {rows:rows.slice((page-1)*50,page*50),count:rows.length};});}
async function collectionView(db:DB,actor:Actor,c:Row){const row:Row={id:c.id,number:c.number,customer_id:c.customer_id,amount:c.amount,received_date:dateText(c.received_date),actor_name:c.actor_name,status:c.reversed?'Reversed':'Recorded',ar_id:c.ar_id,ar_number:c.ar_number,physical_number:c.physical_number,customer_name:c.customer_name};
 if(allows(actor,'collections.details'))Object.assign(row,{method:c.method_snapshot.name,behavior:c.method_snapshot.behavior,reference:c.reference,notes:c.notes});
 if(allows(actor,'collections.accounts'))Object.assign(row,{account_id:c.account_id,account:c.account_snapshot?.name||''});
 if(allows(actor,'collections.checks')&&c.method_snapshot.behavior==='Check'){Object.assign(row,{check_bank:c.check_bank,check_number:c.check_number,check_date:dateText(c.check_date)});row.events=(await db.query<Row>('SELECT e.status,e.effective_date,e.reason,u.name AS actor_name FROM check_events e JOIN users u ON u.id=e.actor_id WHERE collection_id=$1 ORDER BY sequence',[c.id])).rows;row.check_status=row.events.at(-1)?.status;}
 if(c.reversed)row.reversal=(await db.query('SELECT r.effective_date,r.reason,u.name AS actor_name FROM collection_reversals r JOIN users u ON u.id=r.actor_id WHERE collection_id=$1',[c.id])).rows[0];return row;
}
async function collectionRows(db:DB,actor:Actor,filter:Row={}){
 need(actor,'collections.read');if(!await financeReady(db))return [];
 for(const key of ['ar','customer','employee','method','account','id'])if(filter[key])z.uuid().parse(filter[key]);for(const key of ['from','to'])if(filter[key])z.iso.date().parse(filter[key]);
 if(filter.method)need(actor,'collections.details');if(filter.account)need(actor,'collections.accounts');if(filter.checks||filter.check_status)need(actor,'collections.checks');
 const rows=(await db.query<Row>(`SELECT c.*,u.name AS actor_name,a.ar_id,r.number AS ar_number,r.physical_number,r.source_number,r.customer_snapshot->>'name' AS customer_name,EXISTS(SELECT 1 FROM collection_reversals v WHERE v.collection_id=c.id) AS reversed FROM collections c JOIN collection_allocations a ON a.collection_id=c.id JOIN receivables r ON r.id=a.ar_id JOIN users u ON u.id=c.actor_id
 WHERE ($1='' OR a.ar_id=NULLIF($1,'')::uuid) AND ($2='' OR c.customer_id=NULLIF($2,'')::uuid) AND ($3='' OR c.id=NULLIF($3,'')::uuid) ORDER BY c.received_date DESC,c.created_at DESC`,[filter.ar||'',filter.customer||'',filter.id||''])).rows;
 const result:Row[]=[];const q=String(filter.q||'').toLowerCase().slice(0,160);for(const c of rows){if(filter.employee&&c.actor_id!==filter.employee||filter.method&&c.method_id!==filter.method||filter.account&&c.account_id!==filter.account||filter.from&&dateText(c.received_date)<filter.from||filter.to&&dateText(c.received_date)>filter.to||filter.checks&&c.method_snapshot.behavior!=='Check')continue;
 const search=[c.number,c.customer_name,c.physical_number,c.source_number];if(allows(actor,'collections.details'))search.push(c.reference);if(allows(actor,'collections.checks'))search.push(c.check_number);if(q&&!search.some(v=>String(v||'').toLowerCase().includes(q)))continue;
 const row=await collectionView(db,actor,c);if(filter.status&&row.status!==filter.status||filter.check_status&&row.check_status!==filter.check_status)continue;result.push(row);}return result;
}
export async function listCollections(actor:Actor,filter:Row={}){return transaction(async db=>{actor=await freshActor(db,actor.id);const rows=await collectionRows(db,actor,filter);const page=Math.max(1,Math.min(100000,Number(filter.page)||1));return {rows:rows.slice((page-1)*50,page*50),count:rows.length};});}
export async function getAR(actor:Actor,id:string){z.uuid().parse(id);return transaction(async db=>{actor=await freshActor(db,actor.id);need(actor,'ar.read');const ar=(await db.query<Row>('SELECT * FROM receivables WHERE id=$1',[id])).rows[0];if(!ar)throw new Error('Receivable not found.');const row=await projectAR(db,actor,ar);
 if(allows(actor,'collections.read'))row.collections=await collectionRows(db,actor,{ar:id});
 if(allows(actor,'ar.followups')||allows(actor,'ar.promise')){const f=(await db.query<Row>('SELECT f.*,u.name AS actor_name FROM ar_followups f JOIN users u ON u.id=f.actor_id WHERE ar_id=$1 ORDER BY f.created_at DESC',[id])).rows;row.followups=f.map(v=>({id:v.id,followup_date:dateText(v.followup_date),actor_name:v.actor_name,...(allows(actor,'ar.followups')?{note:v.note}:{}),...(allows(actor,'ar.promise')?{promise_date:v.promise_date?dateText(v.promise_date):null}:{})}));}
 row.adjustment_history=(await db.query<Row>('SELECT a.*,r.number AS return_number,u.name AS actor_name FROM ar_adjustments a JOIN sale_returns r ON r.id=a.return_id JOIN users u ON u.id=a.actor_id WHERE ar_id=$1 ORDER BY created_at',[id])).rows;
 if(allows(actor,'ar.adjust'))row.adjustable_returns=(await db.query<Row>(`SELECT r.id,r.number FROM sale_returns r WHERE r.status='Completed' AND (r.sale_id=$1 OR EXISTS(SELECT 1 FROM commercial_documents d WHERE d.sale_id=r.sale_id AND d.source_id=$2)) ORDER BY r.created_at DESC`,[ar.sale_id,ar.order_id])).rows;
 return row;});}
export async function financeSummary(actor:Actor,customer?:string,asOf=businessDate()){z.iso.date().parse(asOf);if(customer)z.uuid().parse(customer);return transaction(async db=>{actor=await freshActor(db,actor.id);need(actor,'ar.read');if(customer)need(actor,'ar.customer');const rows=await allAR(db,actor,{customer},asOf),sum=(key:string)=>rows.reduce((n,r)=>n.plus(r[key]||0),new Money(0)).toFixed(2);const result:Row={outstanding:sum('balance'),refund_due:sum('refund_due')};if(allows(actor,'collections.checks'))result.pending_checks=sum('pending_checks');if(allows(actor,'ar.overdue'))result.overdue=rows.filter(r=>r.days_overdue>0).reduce((n,r)=>n.plus(r.balance),new Money(0)).toFixed(2);if(allows(actor,'ar.due'))result.due_soon=rows.filter(r=>r.due_date>=asOf&&r.due_date<=new Date(Date.parse(asOf)+7*86400000).toISOString().slice(0,10)).reduce((n,r)=>n.plus(r.balance),new Money(0)).toFixed(2);
 if(allows(actor,'ar.aging'))result.aging=Object.fromEntries(['Current','1–30','31–60','61–90','Over 90'].map(b=>[b,rows.filter(r=>r.aging_bucket===b).reduce((n,r)=>n.plus(r.balance),new Money(0)).toFixed(2)]));
 if(customer&&allows(actor,'ar.credit')){const c=(await db.query<Row>('SELECT credit_limit,account_status,version FROM customers WHERE id=$1',[customer])).rows[0];if(c){result.credit_limit=c.credit_limit;result.customer_version=c.version;result.account_status=c.account_status;result.available_credit=new Money(c.credit_limit||0).minus(result.outstanding).toFixed(2);}}
 if(allows(actor,'collections.summary')&&await financeReady(db)){result.collections_today=(await db.query<Row>(`SELECT COALESCE(sum(c.amount),0)::text AS n FROM collections c WHERE ($2='' OR c.customer_id=NULLIF($2,'')::uuid) AND NOT EXISTS(SELECT 1 FROM collection_reversals r WHERE r.collection_id=c.id AND r.effective_date<=$1) AND ((c.method_snapshot->>'behavior'<>'Check' AND c.received_date=$1) OR (c.method_snapshot->>'behavior'='Check' AND (SELECT e.status FROM check_events e WHERE e.collection_id=c.id AND e.effective_date<=$1 ORDER BY e.sequence DESC LIMIT 1)='Cleared' AND EXISTS(SELECT 1 FROM check_events e WHERE e.collection_id=c.id AND e.status='Cleared' AND e.effective_date=$1)))`,[asOf,customer||''])).rows[0].n;}
 return result;});}
export async function customerStatement(actor:Actor,customer:string,asOf:string){z.uuid().parse(customer);z.iso.date().parse(asOf);if(asOf>businessDate())throw new Error('Statement date cannot be in the future.');return transaction(async db=>{actor=await freshActor(db,actor.id);need(actor,'ar.statement');need(actor,'ar.customer');need(actor,'ar.paid');const c=(await db.query<Row>('SELECT id,name,code,billing_address AS address FROM customers WHERE id=$1',[customer])).rows[0];if(!c)throw new Error('Customer not found.');const raw=(await db.query<Row>('SELECT * FROM receivables WHERE customer_id=$1 AND invoice_date<=$2 ORDER BY invoice_date,number',[customer,asOf])).rows;const rows=[];for(const ar of raw){const p=await position(db,ar,asOf);rows.push({number:ar.number,physical_number:ar.physical_number,invoice_date:dateText(ar.invoice_date),due_date:dateText(ar.due_date),original_amount:ar.original_amount,collected:p.collected,adjustments:p.adjustments,balance:p.balance,refund_due:p.refund_due});}return {customer:c,as_of:asOf,rows,total:rows.reduce((n,r)=>n.plus(r.balance),new Money(0)).toFixed(2),refund_due:rows.reduce((n,r)=>n.plus(r.refund_due),new Money(0)).toFixed(2)};});}
export async function financeOptions(actor:Actor){return transaction(async db=>{actor=await freshActor(db,actor.id);need(actor,'collections.record');return {methods:(await db.query("SELECT id,name,behavior FROM sales_options WHERE kind='payment_method' AND active AND behavior<>'Unpaid' ORDER BY name")).rows,accounts:allows(actor,'collections.accounts')?(await db.query("SELECT id,name FROM sales_options WHERE kind='bank' AND active ORDER BY name")).rows:[]};});}
export async function collectionFilters(actor:Actor){return transaction(async db=>{actor=await freshActor(db,actor.id);need(actor,'collections.read');return {methods:allows(actor,'collections.details')?(await db.query<Row>("SELECT id,name FROM sales_options WHERE kind='payment_method' AND behavior<>'Unpaid' ORDER BY name")).rows:[],accounts:allows(actor,'collections.accounts')?(await db.query<Row>("SELECT id,name FROM sales_options WHERE kind='bank' ORDER BY name")).rows:[]};});}
