import {offsetVatReference} from './vat-reference';
import {z} from 'zod';
import {transaction,type DB} from './db';
import {freshActor} from './masters';
import {allows,type Actor} from './permissions';
import {need,stamp,digest,option,type Row} from './sales-common';
import {Money} from './vat';
import {dueDate} from './sales-calculations';
export const businessDate=(value:Date|string=new Date())=>new Date(new Date(value).getTime()+8*3600000).toISOString().slice(0,10);
export const dateText=(v:unknown)=>v instanceof Date?v.toISOString().slice(0,10):String(v).slice(0,10);
export async function financeReady(db:DB){return Boolean((await db.query<Row>("SELECT to_regclass('imperial.receivables') AS t")).rows[0].t);}
async function insert(db:DB,table:string,data:Row){const keys=Object.keys(data);return (await db.query<Row>(`INSERT INTO ${table}(${keys.join(',')}) VALUES(${keys.map((_,i)=>'$'+(i+1)).join(',')}) RETURNING *`,Object.values(data).map(v=>v&&typeof v==='object'&&!(v instanceof Date)?JSON.stringify(v):v))).rows[0];}
const amount=z.string().regex(/^\d{1,16}(\.\d{1,2})?$/).refine(v=>new Money(v).gt(0),'Enter a positive amount');
const date=z.iso.date();const reason=z.string().trim().min(3).max(1000);const optional=z.string().trim().max(250).default('');
function validDate(v:string,min?:string){if(v>businessDate()||(min&&v<min))throw new Error('Use a date on or after the related event and not in the future.');}
async function lockAR(db:DB,id:string){const row=(await db.query<Row>('SELECT * FROM receivables WHERE id=$1 FOR UPDATE',[id])).rows[0];if(!row)throw new Error('Receivable not found.');return row;}
async function financialDate(db:DB,ar:string,date:string){
 const last=(await db.query<Row>(`SELECT max(d)::text AS latest FROM (SELECT c.received_date d FROM collections c JOIN collection_allocations a ON a.collection_id=c.id WHERE a.ar_id=$1 UNION ALL SELECT e.effective_date FROM check_events e JOIN collection_allocations a ON a.collection_id=e.collection_id WHERE a.ar_id=$1 UNION ALL SELECT r.effective_date FROM collection_reversals r JOIN collection_allocations a ON a.collection_id=r.collection_id WHERE a.ar_id=$1 UNION ALL SELECT effective_date FROM ar_adjustments WHERE ar_id=$1) events`,[ar])).rows[0].latest;
 if(last&&date<last)throw new Error('The date precedes a recorded financial event. Use '+last+' or later to preserve historical balances.');
}
async function withAction(actor:Actor,operation:string,data:Row,fn:(db:DB,actor:Actor)=>Promise<string>){return transaction(async db=>{actor=await freshActor(db,actor.id);need(actor,operation as Parameters<typeof need>[1]);await db.query('SELECT pg_advisory_xact_lock(hashtext($1))',[data.request_id]);const hash=digest(data),prior=(await db.query<Row>('SELECT * FROM finance_requests WHERE request_id=$1',[data.request_id])).rows[0];if(prior){if(prior.actor_id!==actor.id||prior.operation!==operation||prior.payload_hash!==hash)throw new Error('Submission already used for different details.');return String(prior.result_id);}await stamp(db,actor);const id=await fn(db,actor);await insert(db,'finance_requests',{request_id:data.request_id,actor_id:actor.id,operation,payload_hash:hash,result_id:id});return id;});}

// History is append-only. Reconstruct the balance from events effective on the requested Manila business date.
export async function position(db:DB,ar:Row,asOf=businessDate()){
 const records=(await db.query<Row>(`SELECT c.*,a.amount AS allocated,
 (SELECT status FROM check_events e WHERE e.collection_id=c.id AND e.effective_date<=$2 ORDER BY e.sequence DESC LIMIT 1) AS check_status,
 EXISTS(SELECT 1 FROM collection_reversals r WHERE r.collection_id=c.id AND r.effective_date<=$2) AS reversed
 FROM collection_allocations a JOIN collections c ON c.id=a.collection_id WHERE a.ar_id=$1 AND c.received_date<=$2 ORDER BY c.received_date,c.created_at,c.id`,[ar.id,asOf])).rows;
 let cleared=new Money(0),pending=new Money(0);for(const c of records){if(c.reversed)continue;if(c.method_snapshot.behavior==='Check'){if(c.check_status==='Cleared')cleared=cleared.plus(c.allocated);else if(['Received','Deposited'].includes(c.check_status))pending=pending.plus(c.allocated);}else cleared=cleared.plus(c.allocated);}
 const adjustments=(await db.query<Row>('SELECT * FROM ar_adjustments WHERE ar_id=$1 AND effective_date<=$2 ORDER BY effective_date,created_at',[ar.id,asOf])).rows;
 const adjusted=adjustments.reduce<InstanceType<typeof Money>>((n,a)=>n.plus(a.amount),new Money(0));const raw=new Money(ar.original_amount).minus(cleared).minus(adjusted),balance=Money.max(0,raw),refund=Money.max(0,raw.negated());
 const days=Math.max(0,Math.floor((Date.parse(asOf)-Date.parse(dateText(ar.due_date)))/86400000));
 const status=balance.isZero()?'Paid':cleared.plus(adjusted).isZero()?'Unpaid':'Partially Paid';
 const bucket=days===0?'Current':days<=30?'1–30':days<=60?'31–60':days<=90?'61–90':'Over 90';
 const last=records.filter(c=>!c.reversed&&(c.method_snapshot.behavior!=='Check'||c.check_status==='Cleared')).at(-1);
 return {collected:cleared.toFixed(2),pending_checks:pending.toFixed(2),adjustments:adjusted.toFixed(2),balance:balance.toFixed(2),refund_due:refund.toFixed(2),payment_status:status,days_overdue:balance.gt(0)?days:0,aging_bucket:balance.gt(0)?bucket:null,last_collection_date:last?dateText(last.received_date):null,last_collection_amount:last?.allocated||null,records,adjustment_records:adjustments};
}

export async function classifyLegacy(db:DB,sale:Row){
 if(sale.status!=='Posted')return 'Not Posted';
 // All Stage 4 release Sales are excluded, even before their SI exists: the SI remains the sole billing source.
 if((await db.query('SELECT id FROM commercial_documents WHERE sale_id=$1',[sale.id])).rows.length)return 'Stage 4 release';
 if((await db.query('SELECT id FROM sale_reversals WHERE sale_id=$1',[sale.id])).rows.length)return 'Owner review: reversed Sale';
 if((await db.query('SELECT id FROM sale_returns WHERE sale_id=$1',[sale.id])).rows.length)return 'Owner review: historical Return';
 const payments=(await db.query<Row>('SELECT * FROM sale_payments WHERE sale_id=$1',[sale.id])).rows;
 if(payments.some(p=>p.reversal_of||new Money(p.amount).lte(0)||!p.method_snapshot?.behavior||p.method_snapshot.behavior==='Unpaid'||(p.method_snapshot.behavior==='Check'&&(!p.check_number||!p.check_bank||!p.check_date))))return 'Owner review: payment history';
 if(payments.reduce<InstanceType<typeof Money>>((n,p)=>n.plus(p.amount),new Money(0)).gt(sale.gross_total))return 'Owner review: excess historical payments';
 return 'Eligible';
}
export async function createARForSource(db:DB,actor:Actor,kind:'invoice'|'sale',id:string){
 if(!await financeReady(db))return null;
 const table=kind==='invoice'?'commercial_documents':'sales',key=kind==='invoice'?'invoice_id':'sale_id';
 const source=(await db.query<Row>(`SELECT * FROM ${table} WHERE id=$1 FOR UPDATE`,[id])).rows[0];if(!source)throw new Error('Source not found.');
 const existing=(await db.query<Row>(`SELECT id FROM receivables WHERE ${key}=$1`,[id])).rows[0];if(existing)return String(existing.id);
 if(kind==='invoice'){if(source.kind!=='SI'||source.status!=='Finalized')return null;}else if(await classifyLegacy(db,source)!=='Eligible')return null;
 const physical=kind==='invoice'?source.physical_number:(await db.query<Row>("SELECT number FROM sale_documents WHERE sale_id=$1 AND kind='SI' AND status<>'Cancelled / Void' AND number IS NOT NULL ORDER BY created_at LIMIT 1",[id])).rows[0]?.number||'';
 await stamp(db,actor);
 const ar=await insert(db,'receivables',{[key]:id,customer_id:source.customer_id,customer_snapshot:source.customer_snapshot,physical_number:physical||'',source_number:source.number,order_id:kind==='invoice'?source.source_id:null,salesperson_id:source.salesperson_id,channel:source.channel,company:source.company||'Imperial Electrical and Industrial Supply Corporation',invoice_date:businessDate(source.occurred_at),terms:source.terms,custom_terms:source.custom_terms,due_date:kind==='invoice'&&source.terms!=='Custom'?dueDate(source.occurred_at,source.terms):source.due_date?dateText(source.due_date):dueDate(source.occurred_at,source.terms),original_amount:source.gross_total,actor_id:actor.id});
 if(kind==='sale')for(const p of (await db.query<Row>('SELECT * FROM sale_payments WHERE sale_id=$1 ORDER BY created_at,id',[id])).rows){
 const c=await insert(db,'collections',{customer_id:source.customer_id,amount:p.amount,received_date:businessDate(p.received_at),method_id:p.method_id,method_snapshot:p.method_snapshot,account_id:p.account_id,account_snapshot:p.account_snapshot,reference:p.reference,check_bank:p.check_bank,check_number:p.check_number,check_date:p.check_date,notes:'Recognized existing actual payment; original unchanged.',legacy_payment_id:p.id,actor_id:p.actor_id});
 await insert(db,'collection_allocations',{collection_id:c.id,ar_id:ar.id,amount:p.amount});if(p.method_snapshot.behavior==='Check')await insert(db,'check_events',{collection_id:c.id,status:'Received',effective_date:businessDate(p.received_at),reason:'Historical instrument; no evidence of clearing.',actor_id:actor.id});}
 return String(ar.id);
}
export async function reconcileAR(actor:Actor,input:unknown){const d=z.object({request_id:z.uuid()}).strict().parse(input);return withAction(actor,'ar.generate',d,async(db,actor)=>{
 const sources=(await db.query<Row>("SELECT id FROM commercial_documents WHERE kind='SI' AND status='Finalized' ORDER BY id")).rows;let last:string|null=null;
 for(const row of sources)last=await createARForSource(db,actor,'invoice',row.id)||last;
 for(const row of (await db.query<Row>("SELECT id FROM sales WHERE status='Posted' ORDER BY id")).rows)last=await createARForSource(db,actor,'sale',row.id)||last;
 return last||actor.id;
 });}
export async function legacyReport(actor:Actor){return transaction(async db=>{actor=await freshActor(db,actor.id);need(actor,'ar.generate');const result:Row={eligible:0,excluded_stage4:0,with_actual_payments:0,Unpaid:0,'Partially Paid':0,Paid:0,review:[]};for(const s of (await db.query<Row>("SELECT * FROM sales WHERE status='Posted' ORDER BY number")).rows){const classification=await classifyLegacy(db,s);if(classification==='Stage 4 release'){result.excluded_stage4++;continue;}if(classification!=='Eligible'){result.review.push({id:s.id,number:s.number,reason:classification});continue;}result.eligible++;const ps=(await db.query<Row>('SELECT * FROM sale_payments WHERE sale_id=$1',[s.id])).rows;if(ps.length)result.with_actual_payments++;const valid=ps.filter(p=>p.method_snapshot.behavior!=='Check').reduce<InstanceType<typeof Money>>((n,p)=>n.plus(p.amount),new Money(0));result[valid.isZero()?'Unpaid':valid.eq(s.gross_total)?'Paid':'Partially Paid']++;}result.duplicate_sources=(await db.query<Row>(`SELECT count(*)::int AS n FROM receivables a JOIN commercial_documents d ON d.sale_id=a.sale_id`)).rows[0].n;return result;});}

export async function recordCollection(actor:Actor,input:unknown){const d=z.object({request_id:z.uuid(),ar_id:z.uuid(),amount,received_date:date,method_id:z.uuid(),account_id:z.uuid().optional(),reference:optional,check_bank:optional,check_number:optional,check_date:date.optional(),notes:z.string().trim().max(1000).default('')}).strict().parse(input);return withAction(actor,'collections.record',d,async(db,actor)=>{
 const ar=await lockAR(db,d.ar_id);validDate(d.received_date,dateText(ar.invoice_date));await financialDate(db,ar.id,d.received_date);const p=await position(db,ar),method=await option(db,d.method_id,'payment_method');if(method.behavior==='Unpaid')throw new Error('Choose an actual received payment method.');
 // Reserve pending instruments to prevent accidental duplicate collection; they still remain fully outstanding in AR.
 const available=new Money(p.balance).minus(p.pending_checks);if(new Money(d.amount).gt(available))throw new Error('Available balance is only ₱'+Money.max(0,available).toFixed(2)+' after pending checks.');
 const atDate=await position(db,ar,d.received_date);if(new Money(d.amount).gt(new Money(atDate.balance).minus(atDate.pending_checks)))throw new Error('Collection exceeds the balance on this date.');
 let account=null;if(d.account_id){need(actor,'collections.accounts');if(!['Bank','Wallet','Card','Platform'].includes(method.behavior))throw new Error('Receiving account does not apply to this payment method.');account=await option(db,d.account_id,'bank');}
 if(method.behavior==='Check'){need(actor,'collections.checks');if(!d.check_bank||!d.check_number||!d.check_date)throw new Error('Enter check bank, number and date.');}else if(d.check_bank||d.check_number||d.check_date)throw new Error('Check fields require Check payment.');
 const {request_id,ar_id,...fields}=d;void request_id;void ar_id;
 const c=await insert(db,'collections',{...fields,account_id:d.account_id||null,check_date:d.check_date||null,customer_id:ar.customer_id,method_snapshot:method,account_snapshot:account,actor_id:actor.id});await insert(db,'collection_allocations',{collection_id:c.id,ar_id:ar.id,amount:d.amount});
 if(method.behavior==='Check')await insert(db,'check_events',{collection_id:c.id,status:'Received',effective_date:d.received_date,actor_id:actor.id});return c.id;
 });}
async function lockedCollection(db:DB,id:string){const allocation=(await db.query<Row>('SELECT ar_id FROM collection_allocations WHERE collection_id=$1 ORDER BY ar_id',[id])).rows;if(!allocation.length)throw new Error('Collection not found.');for(const a of allocation)await lockAR(db,a.ar_id);const c=(await db.query<Row>('SELECT * FROM collections WHERE id=$1 FOR UPDATE',[id])).rows[0];return {c,allocation};}
export async function reverseCollection(actor:Actor,input:unknown){const d=z.object({request_id:z.uuid(),id:z.uuid(),effective_date:date,reason}).strict().parse(input);return withAction(actor,'collections.reverse',d,async(db,actor)=>{const {c,allocation}=await lockedCollection(db,d.id);for(const a of allocation)await financialDate(db,a.ar_id,d.effective_date);validDate(d.effective_date,dateText(c.received_date));const last=(await db.query<Row>('SELECT effective_date FROM check_events WHERE collection_id=$1 ORDER BY sequence DESC LIMIT 1',[c.id])).rows[0];if(last&&d.effective_date<dateText(last.effective_date))throw new Error('Reversal must follow the latest check event.');if((await db.query('SELECT id FROM collection_reversals WHERE collection_id=$1',[c.id])).rows.length)throw new Error('Collection already reversed.');await insert(db,'collection_reversals',{collection_id:c.id,effective_date:d.effective_date,reason:d.reason,actor_id:actor.id});return c.id;});}
export async function changeCheck(actor:Actor,input:unknown){const d=z.object({request_id:z.uuid(),id:z.uuid(),expected:z.enum(['Received','Deposited','Cleared']),status:z.enum(['Deposited','Cleared','Returned / Bounced','Cancelled']),effective_date:date,reason}).strict().parse(input);return withAction(actor,'collections.check.update',d,async(db,actor)=>{need(actor,'collections.checks');const {c,allocation}=await lockedCollection(db,d.id);for(const a of allocation)await financialDate(db,a.ar_id,d.effective_date);if(c.method_snapshot.behavior!=='Check')throw new Error('Not a Check.');if((await db.query('SELECT id FROM collection_reversals WHERE collection_id=$1',[c.id])).rows.length)throw new Error('Collection is reversed.');const last=(await db.query<Row>('SELECT * FROM check_events WHERE collection_id=$1 ORDER BY sequence DESC LIMIT 1',[c.id])).rows[0];if(!last||last.status!==d.expected)throw new Error('Check status changed. Reload and review.');const allowed:Record<string,string[]>={Received:['Deposited','Cancelled','Returned / Bounced'],Deposited:['Cleared','Cancelled','Returned / Bounced'],Cleared:['Returned / Bounced']};if(!allowed[last.status]?.includes(d.status))throw new Error('Invalid check transition.');validDate(d.effective_date,dateText(last.effective_date));if(['Deposited','Cleared'].includes(d.status)&&d.effective_date<dateText(c.check_date))throw new Error('A post-dated check cannot be deposited or cleared before its check date.');
 if(d.status==='Cleared')for(const a of allocation){const ar=await lockAR(db,a.ar_id),p=await position(db,ar);const value=(await db.query<Row>('SELECT amount FROM collection_allocations WHERE collection_id=$1 AND ar_id=$2',[c.id,a.ar_id])).rows[0].amount;if(new Money(value).gt(p.balance))throw new Error('Check exceeds outstanding AR after adjustments. Resolve the instrument before clearing.');}
 await insert(db,'check_events',{collection_id:c.id,status:d.status,effective_date:d.effective_date,reason:d.reason,actor_id:actor.id});return c.id;});}
export async function addFollowup(actor:Actor,input:unknown){const d=z.object({request_id:z.uuid(),ar_id:z.uuid(),followup_date:date,note:z.string().trim().max(1000).default(''),promise_date:date.optional()}).strict().parse(input);return withAction(actor,'ar.followup.add',d,async(db,actor)=>{await lockAR(db,d.ar_id);validDate(d.followup_date);if(d.promise_date)need(actor,'ar.promise.edit');if(!d.note&&!d.promise_date)throw new Error('Enter a note or promise date.');await insert(db,'ar_followups',{ar_id:d.ar_id,followup_date:d.followup_date,note:d.note,promise_date:d.promise_date||null,actor_id:actor.id});return d.ar_id;});}
export async function adjustAR(actor:Actor,input:unknown){const d=z.object({request_id:z.uuid(),ar_id:z.uuid(),return_id:z.uuid(),amount,effective_date:date,reason}).strict().parse(input);return withAction(actor,'ar.adjust',d,async(db,actor)=>{const ar=await lockAR(db,d.ar_id);await financialDate(db,ar.id,d.effective_date);const ret=(await db.query<Row>('SELECT * FROM sale_returns WHERE id=$1 FOR UPDATE',[d.return_id])).rows[0];if(!ret||ret.status!=='Completed')throw new Error('Select a completed, accepted Return.');validDate(d.effective_date,businessDate(ret.updated_at));
 let eligible=new Money(0);
 if(ar.sale_id===ret.sale_id){eligible=(await db.query<Row>('SELECT COALESCE(sum(gross_amount),0) AS n FROM sale_return_lines WHERE return_id=$1 AND accepted',[ret.id])).rows.reduce<InstanceType<typeof Money>>((n,r)=>n.plus(r.n),new Money(0));}
 else if(ar.invoice_id){const release=(await db.query<Row>('SELECT * FROM commercial_documents WHERE sale_id=$1 AND source_id=$2',[ret.sale_id,ar.order_id])).rows[0];if(!release)throw new Error('Return does not belong to this invoice order.');
 // Allocate the accepted return against the invoice/release overlap; never apply the same returned value twice.
 const rows=(await db.query<Row>(`SELECT r.gross_amount,r.quantity AS return_quantity,sl.position,dl.source_line_id,dl.quantity AS delivery_quantity,dl.vat_snapshot AS delivery_snapshot,il.quantity AS invoice_quantity,il.vat_snapshot AS invoice_snapshot FROM sale_return_lines r JOIN sale_lines sl ON sl.id=r.sale_line_id JOIN commercial_lines dl ON dl.document_id=$2 AND dl.position=sl.position JOIN commercial_lines il ON il.document_id=$3 AND il.source_line_id=dl.source_line_id WHERE r.return_id=$1 AND r.accepted`,[ret.id,release.id,ar.invoice_id])).rows;
 for(const row of rows){const ds=new Money(row.delivery_snapshot.allocation.prior_quantity),de=ds.plus(row.delivery_quantity),is=new Money(row.invoice_snapshot.allocation.prior_quantity),ie=is.plus(row.invoice_quantity);const overlap=Money.max(0,Money.min(de,ie).minus(Money.max(ds,is)));eligible=eligible.plus(new Money(row.gross_amount).mul(overlap).div(row.delivery_quantity));}}
 else throw new Error('Return does not belong to this receivable.');
 const total=(await db.query<Row>('SELECT COALESCE(sum(gross_amount),0) n FROM sale_return_lines WHERE return_id=$1 AND accepted',[ret.id])).rows[0].n;
 const prior=(await db.query<Row>('SELECT COALESCE(sum(amount),0) n FROM ar_adjustments WHERE return_id=$1',[ret.id])).rows[0].n;
 const p=await position(db,ar);if(new Money(d.amount).gt(eligible.toDecimalPlaces(2))||new Money(d.amount).plus(prior).gt(total)||new Money(d.amount).plus(p.adjustments).gt(ar.original_amount))throw new Error('Adjustment exceeds the accepted returned value allocated to this invoice.');
 const adjustment=await insert(db,'ar_adjustments',{ar_id:ar.id,return_id:ret.id,amount:d.amount,effective_date:d.effective_date,reason:d.reason,actor_id:actor.id});await offsetVatReference(db,actor,ar.invoice_id?'invoice':'sale',ar.invoice_id||ar.sale_id,'ar-adjustment:'+adjustment.id,d.amount,d.effective_date,d.reason);return ar.id;});}
export async function changeCredit(actor:Actor,input:unknown){const d=z.object({request_id:z.uuid(),customer_id:z.uuid(),credit_limit:z.string().regex(/^\d{1,16}(\.\d{1,2})?$/),version:z.coerce.number().int().positive(),reason}).strict().parse(input);return withAction(actor,'ar.credit.edit',d,async(db,actor)=>{need(actor,'ar.credit');const c=(await db.query<Row>('SELECT * FROM customers WHERE id=$1 FOR UPDATE',[d.customer_id])).rows[0];if(!c||c.version!==d.version)throw new Error('Customer changed. Reload before updating credit limit.');await db.query('UPDATE customers SET credit_limit=$1,version=version+1,updated_at=now() WHERE id=$2',[d.credit_limit,c.id]);await db.query("INSERT INTO audit_log(actor_id,actor_name,entity,record_id,action,after_data) VALUES($1,$2,'customers',$3,'CREDIT_LIMIT_REASON',$4)",[actor.id,actor.name,c.id,JSON.stringify({reason:d.reason})]);return c.id;});}
