import {resolveSession} from './sessions';
import {hasValidRequestOrigin} from './request-origin';
import {saleError} from './sales-common';
import {reconcileAR,recordCollection,reverseCollection,changeCheck,addFollowup,adjustAR,legacyReport,changeCredit} from './finance';
import {listAR,getAR,listCollections,financeSummary,customerStatement,financeOptions} from './finance-read';
export async function financeResponse(request:Request){const headers={'Cache-Control':'private, no-store','Vary':'Cookie'};try{const token=request.headers.get('cookie')?.split(';').map(s=>s.trim()).find(s=>s.startsWith('imperial_session='))?.slice(17);const actor=token?await resolveSession(token):null;if(!actor)return Response.json({error:'Authentication required'},{status:401,headers});
 if(request.method==='GET'){const p=new URL(request.url).searchParams,f=Object.fromEntries(p);let data;switch(p.get('view')){case 'detail':data=await getAR(actor,f.id);break;case 'collections':data=await listCollections(actor,f);break;case 'summary':data=await financeSummary(actor,f.customer);break;case 'statement':data=await customerStatement(actor,f.customer,f.as_of);break;case 'options':data=await financeOptions(actor);break;case 'legacy':data=await legacyReport(actor);break;default:data=await listAR(actor,f);}return Response.json({data},{headers});}
 if(request.method!=='POST')return Response.json({error:'Method not allowed'},{status:405,headers});if(!hasValidRequestOrigin(request))return Response.json({error:'Invalid request origin'},{status:403,headers});const body=await request.json();const handlers={reconcile:reconcileAR,collect:recordCollection,reverse:reverseCollection,check:changeCheck,followup:addFollowup,adjust:adjustAR,credit:changeCredit};if(!body||typeof body!=='object'||Array.isArray(body)||Object.keys(body).some(k=>!['operation','data'].includes(k))||!Object.hasOwn(handlers,body.operation))return Response.json({error:'Invalid request'},{status:400,headers});return Response.json({id:await handlers[body.operation as keyof typeof handlers](actor,body.data)},{headers});
 }catch(e){return Response.json({error:saleError(e)},{status:e instanceof Error&&e.message.includes('permission')?403:400,headers});}}
