import {familyOptions} from './quotation-families';
import {transaction} from './db';
import {freshActor} from './masters';
import {need,type Row} from './sales-common';
import type {Actor} from './permissions';
import {quotationUnits} from './quotation-pricing';
function access(actor:Actor){need(actor,'quotations.read');need(actor,'commercial.prices');need(actor,'products.read');}
// Only public selling references are projected. Never expose full rules or acquisition fields.
export async function quotationProductSearch(actor:Actor,q:string):Promise<Row[]>{return transaction(async db=>{actor=await freshActor(db,actor.id);access(actor);const rows=(await db.query<Row>(`SELECT p.*,COALESCE((SELECT sum(CASE WHEN m.kind='IN' THEN m.stock_quantity ELSE -m.stock_quantity END) FROM inventory_movements m WHERE m.product_id=p.id),0)::text available FROM products p WHERE active AND (name ILIKE $1 OR sku ILIKE $1 OR brand ILIKE $1) ORDER BY name,id LIMIT 20`,['%'+q.slice(0,120)+'%'])).rows;const families=(await db.query<Row>(`SELECT DISTINCT f.id,f.name FROM quotation_families f LEFT JOIN quotation_family_variants v ON v.family_id=f.id LEFT JOIN products p ON p.id=v.product_id WHERE f.active AND (f.name ILIKE $1 OR f.code ILIKE $1 OR p.name ILIKE $1 OR p.sku ILIKE $1) ORDER BY f.name LIMIT 20`,['%'+q.slice(0,120)+'%'])).rows;const linked=new Set((await db.query<Row>('SELECT product_id FROM quotation_family_variants')).rows.map(r=>r.product_id));const grouped=[];for(const f of families){const option=await familyOptions(db,f.id);if(option)grouped.push(option);}return [...grouped,...rows.filter(p=>!linked.has(p.id)).map(p=>({id:p.id,name:p.name,sku:p.sku,primary_uom:p.primary_uom,secondary_uom:p.secondary_uom,available:p.available,unit_defaults:quotationUnits(p).filter(u=>[p.primary_uom,p.secondary_uom].includes(u.uom))}))];});}
export async function quotationPricingOptions(actor:Actor,lines:Row[]):Promise<Row[]>{return transaction(async db=>{actor=await freshActor(db,actor.id);access(actor);const products=(await db.query<Row>('SELECT * FROM products WHERE id=ANY($1::uuid[]) AND active',[[...new Set(lines.map(l=>l.product_id))]])).rows;const result=[];for(const l of lines){const familyId=l.vat_snapshot?.quotation_family?.id;if(familyId){const family=await familyOptions(db,familyId);result.push({...l,family_id:familyId,family_name:l.vat_snapshot.quotation_family.name,unit_defaults:family?.unit_defaults||[]});continue;}const p=products.find(p=>p.id===l.product_id);result.push({...l,unit_defaults:p?quotationUnits(p).filter(u=>[p.primary_uom,p.secondary_uom].includes(u.uom)):[{uom:l.uom,price:l.entered_price,prices:{},vat_mode:l.vat_mode,tax_treatment:l.tax_treatment}]});}return result;});}
