import {z} from 'zod';
import {transaction} from './db';
import {freshActor} from './masters';
import {has,allows,type Actor} from './permissions';
import {stamp,type Row} from './sales-common';
export async function salesOptions(actor:Actor,all=false){return transaction(async db=>{actor=await freshActor(db,actor.id);if(!has(actor)&&!allows(actor,'sales.read'))throw new Error('You do not have permission for Sales.');if(all&&!has(actor))throw new Error('Only Owner/Admin can manage Sales settings.');const rows=(await db.query<Row>(`SELECT id,kind,code,name,behavior,active,version FROM sales_options ${all?'':'WHERE active'} ORDER BY kind,name`)).rows;return rows.filter(r=>has(actor)||r.kind==='platform'||(['payment_method','bank'].includes(r.kind)?allows(actor,'sales.payments'):allows(actor,'sales.documents')));});}
export async function saveSalesOption(actor:Actor,input:unknown){const d=z.object({id:z.uuid().optional(),kind:z.enum(['platform','payment_method','bank','si_series','dr_series']),code:z.string().trim().min(1).max(60).regex(/^[a-zA-Z0-9_-]+$/),name:z.string().trim().min(1).max(160),behavior:z.enum(['Cash','Wallet','Bank','Check','Card','Platform','Unpaid','Other','SI','DR']).default('Other'),active:z.boolean(),version:z.number().int().positive().optional()}).strict().parse(input);
 return transaction(async db=>{actor=await freshActor(db,actor.id);if(!has(actor))throw new Error('Only Owner/Admin can manage Sales settings.');await stamp(db,actor);
 if(d.id){const old=(await db.query<Row>('SELECT * FROM sales_options WHERE id=$1 FOR UPDATE',[d.id])).rows[0];if(!old||old.version!==d.version)throw new Error('Settings changed. Reload before saving.');if(old.kind!==d.kind||old.code!==d.code)throw new Error('Keep the original option type and code. Create a new option for a different purpose.');await db.query('UPDATE sales_options SET name=$1,behavior=$2,active=$3,version=version+1,updated_at=now() WHERE id=$4',[d.name,d.behavior,d.active,d.id]);return d.id;}
 return String((await db.query('INSERT INTO sales_options(kind,code,name,behavior,active) VALUES($1,$2,$3,$4,$5) RETURNING id',[d.kind,d.code,d.name,d.behavior,d.active])).rows[0].id);});}
export async function returnPolicies(actor:Actor){return transaction(async db=>{actor=await freshActor(db,actor.id);if(!has(actor))throw new Error('Only Owner/Admin can manage Sales settings.');return (await db.query<Row>('SELECT p.*,o.name AS platform_name FROM platform_return_policies p JOIN sales_options o ON o.id=p.platform_id ORDER BY o.name,p.version DESC')).rows;});}
export async function saveReturnPolicy(actor:Actor,input:unknown){const d=z.object({platform_id:z.uuid(),previous_version:z.number().int().nonnegative(),window_days:z.number().int().min(0).max(3650).nullable(),starts_from:z.enum(['Delivery','Sale','Platform specified']),notes:z.string().trim().max(1000),effective_at:z.iso.datetime({offset:true})}).strict().parse(input);return transaction(async db=>{
 actor=await freshActor(db,actor.id);if(!has(actor))throw new Error('Only Owner/Admin can manage Sales settings.');
 const platform=(await db.query("SELECT id FROM sales_options WHERE id=$1 AND kind='platform' FOR UPDATE",[d.platform_id])).rows[0];if(!platform)throw new Error('Choose a platform.');
 const last=(await db.query<Row>('SELECT COALESCE(max(version),0)::int AS version FROM platform_return_policies WHERE platform_id=$1',[d.platform_id])).rows[0];if(last.version!==d.previous_version)throw new Error('Policy changed. Reload before saving.');await stamp(db,actor);
 return String((await db.query('INSERT INTO platform_return_policies(platform_id,version,window_days,starts_from,notes,effective_at) VALUES($1,$2,$3,$4,$5,$6) RETURNING id',[d.platform_id,last.version+1,d.window_days,d.starts_from,d.notes,d.effective_at])).rows[0].id);
 });}
