import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {writeFile} from 'node:fs/promises';
import {query,closeDB} from '../lib/db';
import {saveMaster} from '../lib/masters';
import {saveCommercial} from '../lib/commercial';
import {quotationDocument} from '../lib/quotation-document';
import {quotationRender} from '../lib/quotation-pdf';
import type {Actor} from '../lib/permissions';
async function main(){assert.equal(process.cwd(),'/private/tmp/imperial-stage55-app');assert(!process.env.DATABASE_URL);process.env.LOCAL_DB_PATH='/private/tmp/imperial-stage55-app/.local-db';const owner=(await query<Actor>("SELECT id,name,email,roles,permission_overrides FROM users WHERE email='stage55.owner@example.test'")).rows[0];assert(owner);const suffix=randomUUID().slice(0,8);const base={sku:'TEST-PRICING-'+suffix,name:'TEST Pricing THHN industrial copper conductor',brand:'TEST',category:'TEST Pricing',primary_uom:'ROLL',secondary_uom:'METER',conversion:'100',base_price:'3000',supplier_adjustment:'0',standard_cost:'3000',cost_entry_mode:'VAT Inclusive',vat_status:'VAT',vat_rate:'0.12',retail_price:'3800',contractor_price:'3500',wholesale_price:'0',meter_price:'15',reorder_level:'0',supplier_id:'',notes:'TEST entered-amount and price-list review only',active:true,selling_prices:{ROLL:{Retail:'3800',Contractor:'3500'},METER:{Retail:'15',Contractor:'14'}}};const pid=await saveMaster(owner,'products',base);const customer=(await query<{id:string}>("SELECT id FROM customers WHERE active ORDER BY created_at LIMIT 1")).rows[0];const line=(quantity:string,uom:string,price:string,discount:string)=>({id:randomUUID(),product_id:pid,quantity,uom,price,discount,adjustment_version:2});const id=await saveCommercial(owner,{request_id:randomUUID(),kind:'Q',channel:'Wholesale',customer_id:customer.id,price_list:'Retail',document_flow:'DR Only',occurred_at:'2026-09-17T00:00:00Z',terms:'Cash',notes:'TEST Owner pricing examples — isolated review only',lines:[line('1','ROLL','3000','+25.5'),line('1','METER','15','-25-5-3'),line('12.5','METER','15','-25-5-3')],fees:[{id:randomUUID(),description:'Delivery Fee',amount:'1500.50'},{id:randomUUID(),description:'Handling Fee',amount:'20'}]});const doc=await quotationDocument(owner,id);assert.deepEqual(doc.lines.map((l:{amount:string})=>l.amount),['3765.00','10.37','129.59']);assert.equal(doc.total,'5425.45');const render=await quotationRender(doc);await writeFile('test-results/stage55/operational-pricing-preview.pdf',render.bytes);await writeFile('test-results/stage55/operational-review.json',JSON.stringify({id,number:doc.number,product:pid,sku:base.sku,amounts:doc.lines.map((l:{amount:string})=>l.amount),total:doc.total},null,2));console.log({id,number:doc.number,product:pid,amounts:doc.lines.map((l:{amount:string})=>l.amount),total:doc.total});}
main().catch(e=>{console.error(e);process.exitCode=1}).finally(closeDB);
