import {writeFile} from 'node:fs/promises';
import {randomUUID} from 'node:crypto';
import {query,closeDB} from '../lib/db';
import {saveUser} from '../lib/users';
import {saveMaster} from '../lib/masters';
import {postMovement} from '../lib/inventory';
import {saveCommercial} from '../lib/commercial';
import {quotationDocument} from '../lib/quotation-document';
import {quotationPDF} from '../lib/quotation-pdf';
import type {Actor} from '../lib/permissions';
async function main(){if(process.cwd()!=='/private/tmp/imperial-stage55-app'||process.env.DATABASE_URL)throw new Error('Isolated acceptance only');const owner=(await query<Actor>("SELECT id,name,email,roles FROM users WHERE 'PRESIDENT_ADMIN'=ANY(roles) AND active LIMIT 1")).rows[0];
 const pass='TEST Stage55 acceptance 2026!';const email='stage55.owner@example.test';const existing=(await query<{id:string}>('SELECT id FROM users WHERE email=$1',[email])).rows[0];const uid=existing?.id||await saveUser(owner,{name:'TEST Stage55 Owner',email,roles:['PRESIDENT_ADMIN'],active:true,password:pass,permission_overrides:{}});const actor:Actor={id:uid,name:'TEST Stage55 Owner',email,roles:['PRESIDENT_ADMIN']};
 const cid=(await query<{id:string}>("SELECT id FROM customers WHERE code='TEST-STAGE55'")).rows[0]?.id||await saveMaster(actor,'customers',{code:'TEST-STAGE55',name:'TEST ABC Construction',customer_type:'Contractor',contact_person:'Engr. Reyes',phone:'0917 555 0100',email:'test@example.test',tin:'',billing_address:'TEST 125 Industrial Avenue, Quezon City',delivery_addresses:'',credit_notes:'',account_status:'Active',credit_limit:'0',payment_terms:'30 Days',salesperson_id:'',notes:'TEST quotation acceptance',active:true});
 const products=[];for(const [name,uom,secondary,conversion,price,meter] of [['THHN Wire 2.0mm² (Black)','ROLL','METER','100','1500','15'],['Plug-in Breaker 30A','PCS','','','350',''],['PVC Pipe 20mm','BOX','PCS','10','1200','']]){const id=(await query<{id:string}>('SELECT id FROM products WHERE sku=$1',['TEST-Q55-'+uom])).rows[0]?.id||await saveMaster(actor,'products',{sku:'TEST-Q55-'+uom,name:'TEST '+name,brand:'Imperial TEST',category:'Electrical',primary_uom:uom,secondary_uom:secondary,conversion,base_price:price,supplier_adjustment:'0',standard_cost:'100',vat_status:'VAT',vat_rate:'0.12',retail_price:price,contractor_price:price,wholesale_price:price,meter_price:meter,reorder_level:'1',supplier_id:'',notes:'TEST',active:true,selling_entry_mode:'VAT Exclusive',selling_tax_treatment:'VATable',cost_entry_mode:'VAT Exclusive',cost_tax_treatment:'VATable',cost_input_vat_recoverable:false});await postMovement(actor,{request_id:randomUUID(),product_id:id,kind:'IN',occurred_at:'2026-09-17T00:00:00Z',quantity:'100',uom,unit_cost:'100',cost_entry_mode:'VAT Exclusive',cost_tax_treatment:'VATable',cost_input_vat_recoverable:false,reference:'TEST Stage55'});products.push({id,name,uom,price});}
 const config=(await query<{version:number}>('SELECT version FROM tax_settings LIMIT 1')).rows[0];
 const data={request_id:randomUUID(),kind:'Q',channel:'Wholesale',customer_id:cid,occurred_at:'2026-09-17T00:00:00Z',terms:'30 Days',validity:'2026-10-17',notes:'Prices are subject to change without prior notice*',tax_config_version:config.version,lines:products.map(p=>({id:randomUUID(),product_id:p.id,uom:p.uom,quantity:'3',price:p.price,discount:'-25-5-3',vat_mode:'VAT Exclusive',tax_treatment:'VATable'})),fees:[{id:randomUUID(),description:'Delivery Fee',amount:'1500',vat_mode:'VAT Exclusive',tax_treatment:'VATable'},{id:randomUUID(),description:'Handling Fee',amount:'100',vat_mode:'VAT Inclusive',tax_treatment:'VAT-Exempt'}]};
 const id=await saveCommercial(actor,data),doc=await quotationDocument(actor,id);await writeFile('output/pdf/Imperial_Quotation_acceptance.pdf',await quotationPDF(doc));const long=await saveCommercial(actor,{...data,request_id:randomUUID(),lines:Array.from({length:65},(_,i)=>({...data.lines[i%3],id:randomUUID()}))});await writeFile('output/pdf/Imperial_Quotation_multipage.pdf',await quotationPDF(await quotationDocument(actor,long)));
 await writeFile('test-results/stage55/acceptance.json',JSON.stringify({owner:uid,email,customer:cid,products,quotation:id,longQuotation:long},null,2));console.log('Acceptance records created in isolated restored database only.');}
main().catch(e=>{console.error(e);process.exitCode=1}).finally(closeDB);
