import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {readFile,writeFile} from 'node:fs/promises';
async function main(){assert.equal(process.cwd(),'/private/tmp/imperial-stage55-app');const token=await readFile('/private/tmp/imperial-q55-review-token','utf8');const results=[];
 const pages=[['/','Dashboard'],['/masters/products','Products'],['/inventory','Inventory'],['/stock-in','Stock In'],['/masters/customers','Customers'],['/masters/suppliers','Suppliers'],['/quotations','QUOTATION FORM'],['/quotations/history','Quotation History'],['/quotations?id=f7927631-db39-4693-ac4d-57e86ef14333','Q-000135'],['/orders','Sales Orders'],['/delivery-receipts','Delivery Receipts'],['/sales-invoices','Sales Invoices'],['/sales','Sales'],['/accounts-receivable','Accounts Receivable'],['/collections','Collections'],['/checks','Check'],['/returns','Returns'],['/statements','Statement'],['/administration','Employee'],['/administration/audit','Audit'],['/administration/tax','Tax'],['/administration/sales','Sales &amp; Returns Settings'],['/administration/quotation','Quotation'],['/search?q=TEST','Search']];
 for(const [path,label] of pages){const response=await fetch('http://127.0.0.1:3002'+path,{headers:{cookie:'imperial_session='+token}});const html=await response.text();assert.equal(response.status,200,path);assert(!html.includes('Access restricted'),path+' restricted');assert(!html.includes('NEXT_HTTP_ERROR_FALLBACK'),path+' application error');assert(html.toLowerCase().includes(label.toLowerCase()),path+' heading missing');if(path==='/quotations'){assert(html.includes('Item Description')||html.includes('+ Add Row'));assert(html.includes('Print Quotation'));assert(!html.includes('Valid until'));assert(!html.includes('VAT-exclusive total'));}if(path.includes('id=f792')){assert(html.includes('value="1500.50"'));assert(html.includes('3,392.84'));}results.push({path,status:200,expectedContent:true});}
 const headers={cookie:'imperial_session='+token,origin:'http://127.0.0.1:3002','content-type':'application/json'};
 async function api(data:any){const response=await fetch('http://127.0.0.1:3002/api/commercial',{method:'POST',headers,body:JSON.stringify({operation:'save',data})});return {status:response.status,...await response.json()};}
 const source=(await (await fetch('http://127.0.0.1:3002/api/commercial?id=f7927631-db39-4693-ac4d-57e86ef14333',{headers})).json()).data;
 const input={request_id:randomUUID(),kind:'Q',channel:'Wholesale',company:source.company,customer_id:source.customer_id,salesperson_id:source.salesperson_id,occurred_at:new Date().toISOString(),terms:source.terms,notes:'TEST document workspace HTTP acceptance',disclaimer:source.quotation_snapshot.disclaimer,tax_config_version:source.tax_config.version,fees:source.fees.map((f:any)=>({id:randomUUID(),description:f.description,amount:f.amount,vat_mode:f.vat_mode,tax_treatment:f.tax_treatment})),lines:source.lines.map((l:any)=>({id:randomUUID(),product_id:l.product_id,quantity:l.quantity,uom:l.uom,price:l.entered_price,discount:l.vat_snapshot.discount_expression,adjustment_version:2,vat_mode:l.vat_mode,tax_treatment:l.tax_treatment}))};
 const pair=await Promise.all([api(input),api(input)]);assert.equal(pair[0].status,200);assert.equal(pair[0].id,pair[1].id);const id=pair[0].id;
 const saved=(await (await fetch('http://127.0.0.1:3002/api/commercial?id='+id,{headers})).json()).data;assert.equal(saved.validity,null);assert.equal(saved.gross_total,'3392.84');
 const edit={...input,id,version:1,request_id:randomUUID(),fees:[{...input.fees[0],amount:'0'}]};const race=await Promise.all([api(edit),api({...edit,request_id:randomUUID()})]);assert.equal(race.filter(r=>r.status===200).length,1);assert.match(race.find(r=>r.status!==200).error,/changed.*Reload/);
 let html=await (await fetch('http://127.0.0.1:3002/quotations?id='+id,{headers})).text();assert(html.includes('1,892.34'));assert(html.includes('QUOTATION FORM'));assert(html.includes('value="0"'));
 assert.equal((await api({...input,id,version:2,request_id:randomUUID()})).status,200);html=await (await fetch('http://127.0.0.1:3002/quotations?id='+id,{headers})).text();assert(html.includes('3,392.84'));assert(html.includes('value="1500.50"'));
 await writeFile('test-results/stage55/workspace-save-http.json',JSON.stringify({passed:true,id,number:saved.number,version:3,total:'3392.84',zeroTotal:'1892.34',creationReplay:true,staleEditRejected:true,noNewValidity:true,scope:'Real HTTP endpoint and server-rendered document checks'},null,2));
 const redirect=await fetch('http://127.0.0.1:3002/commercial/new?kind=Q',{headers:{cookie:'imperial_session='+token},redirect:'manual'});assert.equal(redirect.headers.get('location'),'/quotations');
 const pdf=await fetch('http://127.0.0.1:3002/quotation-document/f7927631-db39-4693-ac4d-57e86ef14333?download=1',{headers:{cookie:'imperial_session='+token}});assert.equal(pdf.status,200);await writeFile('output/pdf/Imperial_Quotation_workspace.pdf',new Uint8Array(await pdf.arrayBuffer()));
 await writeFile('test-results/stage55/workspace-http-review.json',JSON.stringify({passed:true,pages:results,legacyRouteRedirect:true,downloadPDF:true,scope:'Authenticated HTTP smoke checks, not interactive browser acceptance'},null,2));console.log(JSON.stringify({passed:true,pages:results.length,legacyRouteRedirect:true,pdf:true}));}
main().catch(e=>{console.error(e);process.exitCode=1});
