import {financeSummary} from '@/lib/finance-read';
import Link from 'next/link';
import {allows} from '@/lib/permissions';
import {listCommercial} from '@/lib/commercial-read';
import {requireUser} from '@/lib/auth';
import {stockBalances} from '@/lib/inventory';
import {listSales} from '@/lib/sales-read';
import {dashboardData} from '@/lib/dashboard-read';
import {quantityText} from '@/lib/format';
import {DashboardPanel,KpiCard,EmptyState,money} from '@/components/dashboard-ui';
import SalesChart from '@/components/sales-chart';
export default async function Dashboard({searchParams}:{searchParams:Promise<{period?:string}>}){
 const actor=await requireUser(),period=(await searchParams).period==='year'?'year':'month';
 const finance=allows(actor,'ar.read')?await financeSummary(actor):null;
 const data=await dashboardData(actor,period),a=data.access;
 const low=a.inventory?await stockBalances(actor,{low:'true'}):[],recent=a.sales?(await listSales(actor)).slice(0,5):[];
 const quotations=allows(actor,'quotations.read')?(await listCommercial(actor,{kind:'Q'})).slice(0,5):[];
 const selector=<form className="period-select"><label className="sr-only" htmlFor="period">Sales period</label><select id="period" name="period" defaultValue={period}><option value="month">This Month</option><option value="year">This Year</option></select><button aria-label="Apply period">Go</button></form>;
 return <div className="dashboard"><div className="dashboard-heading"><h1>Dashboard</h1><p>Welcome back, {actor.name.split(' ')[0]}!</p></div><div className="kpi-grid">
 <KpiCard label="Total Sales (Today)" icon="peso" value={data.totals?money(data.totals.today):'—'} note={a.prices?'Original posted sales':'Access restricted'}/>
 <KpiCard label="Total Sales (This Month)" icon="calendar" value={data.totals?money(data.totals.month):'—'} note={a.prices?'Original posted sales':'Access restricted'}/>
 <KpiCard label="Total Inventory Value" icon="box" value={a.value?money(data.inventoryValue):'—'} note={a.value?'Current stock value':'Access restricted'}/>
 <KpiCard label="Total Customers" icon="users" value={a.customers?Number(data.customerCount).toLocaleString():'—'} note={a.customers?'Customer Master records':'Access restricted'}/>
 <KpiCard label="Pending AR" icon="document" value={finance?money(finance.outstanding):'—'} note={finance?'Authoritative outstanding balance':'Access restricted'}/>
 </div>{finance&&<div className="panel"><Link href="/accounts-receivable">Accounts Receivable →</Link>{finance.overdue!==undefined&&<span> · Overdue {money(finance.overdue)}</span>}{finance.collections_today!==undefined&&<span> · Cleared Collections today {money(finance.collections_today)}</span>}</div>}<div className="dashboard-main-grid">
 <DashboardPanel title="Sales Overview" icon="document" action={a.prices?selector:undefined} className="overview-panel">{!a.prices?<EmptyState>Sales amounts are restricted for your account.</EmptyState>:data.chart.length?<SalesChart rows={data.chart} profit={a.profit} period={period}/>:<EmptyState>No posted sales {period==='year'?'this year':'this month'}.</EmptyState>}<p className="panel-footnote">{a.prices?'Original posted figures before return adjustments.':''}</p></DashboardPanel>
 <DashboardPanel title="Top Selling Products" icon="trophy" action={<span className="period-caption">{period==='year'?'This Year':'This Month'}</span>}>{a.sales?<><table><thead><tr><th>#</th><th>Product</th><th>Qty Sold</th></tr></thead><tbody>{data.top.map((p,i)=><tr key={`${p.product_id}-${p.product_name}-${p.uom}`}><td>{i+1}</td><td>{String(p.product_name)}</td><td>{quantityText(p.quantity)} {String(p.uom)}</td></tr>)}</tbody></table>{!data.top.length&&<EmptyState>No posted product sales yet.</EmptyState>}<p className="panel-footnote">Original sold quantities · grouped by unit</p></>:<EmptyState>Sales access required.</EmptyState>}</DashboardPanel>
 <DashboardPanel title="Low Stock Alerts" icon="alert" action={a.inventory?<Link href="/inventory?low=true">View All</Link>:undefined}>{a.inventory?<><table><thead><tr><th>Product</th><th>Available</th></tr></thead><tbody>{low.slice(0,5).map(p=><tr key={String(p.id)}><td><Link href={`/inventory?product=${p.id}`}>{String(p.name)}</Link></td><td className="low-quantity">{quantityText(p.available)} {String(p.stock_uom)}</td></tr>)}</tbody></table>{!low.length&&<EmptyState>No products are low on stock.</EmptyState>}</>:<EmptyState>Inventory access required.</EmptyState>}</DashboardPanel>
 </div><div className="dashboard-bottom-grid"><DashboardPanel title="Recent Sales" icon="document" action={a.sales?<Link href="/sales">View All</Link>:undefined}>{a.sales?<><div className="compact-scroll"><table><thead><tr><th>#</th><th>Date</th><th>Customer</th>{a.prices&&<th>Amount</th>}<th>Status</th></tr></thead><tbody>{recent.map(s=><tr key={String(s.id)}><td><Link href={`/sales/${s.id}`}>{String(s.number)}</Link></td><td>{new Date(String(s.occurred_at)).toLocaleDateString('en-PH',{timeZone:'Asia/Manila',month:'short',day:'numeric',year:'numeric'})}</td><td>{String((s.customer_snapshot as {name?:string})?.name||'Walk-in')}</td>{a.prices&&<td>{money(s.gross_total)}</td>}<td><span className={`badge ${s.status==='Draft'?'off':s.payment_status==='Paid'?'paid':'pending'}`}>{String(s.status==='Draft'?'Draft':s.activity||s.status)}</span></td></tr>)}</tbody></table></div>{!recent.length&&<EmptyState>No sales yet.</EmptyState>}</>:<EmptyState>Sales access required.</EmptyState>}</DashboardPanel><DashboardPanel title="Recent Quotations" icon="document" action={allows(actor,'quotations.read')?<Link href="/quotations/history">View All</Link>:undefined}><table><thead><tr><th>#</th><th>Customer</th>{allows(actor,'commercial.prices')&&<th>Amount</th>}<th>Status</th></tr></thead><tbody>{quotations.map(q=><tr key={q.id}><td><Link href={'/commercial/'+q.id}>{q.number}</Link></td><td>{q.customer_snapshot.name}</td>{allows(actor,'commercial.prices')&&<td>{money(q.gross_total)}</td>}<td><span className="badge">{q.status}</span></td></tr>)}</tbody></table>{!quotations.length&&<EmptyState>{allows(actor,'quotations.read')?'No quotations yet.':'Quotation access required.'}</EmptyState>}</DashboardPanel></div></div>;
}
